package app

import (
	"context"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/pinealctx/gcode/internal/config"
	"github.com/pinealctx/gcode/internal/model"
	"github.com/pinealctx/gcode/internal/parser"
	"github.com/pinealctx/gcode/internal/source"
)

// RunGenProto implements the gen-proto subcommand: scans the input directory,
// generates intermediate *.update.proto / *.create.proto files into the same
// directory. Original proto files are not copied — they are already present.
func RunGenProto(ctx context.Context, args []string) error {
	cfg, err := config.ParseGenProto(args)
	if err != nil {
		return err
	}

	scanResult, err := source.Scan(cfg.InputDir)
	if err != nil {
		return fmt.Errorf("scan input directory: %w", err)
	}

	if len(scanResult.Files) == 0 {
		return fmt.Errorf("no .proto files found in %q: %w", cfg.InputDir, source.ErrNoProtoFiles)
	}

	files, err := parser.Parse(ctx, []string{scanResult.ImportPath}, scanResult.Files)
	if err != nil {
		return fmt.Errorf("parse proto files: %w", err)
	}

	// Build a FullName → source file path index for cross-file type resolution.
	typeIdx := typeSourceIndex(files)

	// Generate intermediate proto files into the same directory as the input.
	for _, f := range files {
		if err := generateIntermediateProtos(f, scanResult.ImportPath, typeIdx); err != nil {
			return fmt.Errorf("generate intermediate protos for %q: %w", f.Path, err)
		}
	}

	return nil
}

// generateIntermediateProtos generates *.update.proto and *.create.proto files
// for all messages in f that carry update_message or create_message options.
// Any previously generated intermediate proto files for this base name are
// removed first, so that deleting an option from the source proto does not
// leave stale generated files behind.
func generateIntermediateProtos(f model.File, outputDir string, typeIdx map[string]string) error {
	// Collect all messages with options (including nested).
	var updateMsgs []model.Message
	var createMsgs []model.Message
	collectMessages(f.Messages, &updateMsgs, &createMsgs)

	baseName := protoBaseName(f.Path)

	// Remove stale intermediate protos before (re)generating, so that removing
	// an option from the source proto does not leave orphaned files behind.
	updatePath := filepath.Join(outputDir, baseName+".update.proto")
	createPath := filepath.Join(outputDir, baseName+".create.proto")
	for _, stale := range []string{updatePath, createPath} {
		if err := os.Remove(stale); err != nil && !errors.Is(err, fs.ErrNotExist) {
			return fmt.Errorf("remove stale %q: %w", stale, err)
		}
	}

	if len(updateMsgs) > 0 {
		extImports := collectExternalImports(updateMsgs, typeIdx, f.Path)
		content, err := buildUpdateProto(f, f.Path, updateMsgs, extImports)
		if err != nil {
			return fmt.Errorf("build update proto: %w", err)
		}
		if err := os.WriteFile(updatePath, []byte(content), 0o644); err != nil { //nolint:gosec // generated source files should be world-readable
			return fmt.Errorf("write %q: %w", updatePath, err)
		}
	}

	if len(createMsgs) > 0 {
		extImports := collectExternalImports(createMsgs, typeIdx, f.Path)
		content, err := buildCreateProto(f, f.Path, createMsgs, extImports)
		if err != nil {
			return fmt.Errorf("build create proto: %w", err)
		}
		if err := os.WriteFile(createPath, []byte(content), 0o644); err != nil { //nolint:gosec // generated source files should be world-readable
			return fmt.Errorf("write %q: %w", createPath, err)
		}
	}

	return nil
}

// collectMessages recursively collects messages with update/create options.
func collectMessages(msgs []model.Message, updateOut, createOut *[]model.Message) {
	for _, msg := range msgs {
		if len(msg.UpdateOptions) > 0 {
			*updateOut = append(*updateOut, msg)
		}
		if len(msg.CreateOptions) > 0 {
			*createOut = append(*createOut, msg)
		}
		collectMessages(msg.Messages, updateOut, createOut)
	}
}

// buildProtoHeader writes the common header shared by all generated proto files:
// the generated-code notice, syntax declaration, package, go_package option, and imports.
func buildProtoHeader(sb *strings.Builder, f model.File, relPath string, extraImports []string) {
	sb.WriteString("// Code generated by gcode. DO NOT EDIT.\n\n")
	sb.WriteString("syntax = \"proto3\";\n\n")
	if f.Package != "" {
		fmt.Fprintf(sb, "package %s;\n\n", f.Package)
	}
	if f.GoPackage != "" {
		fmt.Fprintf(sb, "option go_package = %q;\n\n", f.GoPackage)
	}
	imports := collectImports(relPath, extraImports)
	for _, imp := range imports {
		fmt.Fprintf(sb, "import %q;\n", imp)
	}
	if len(imports) > 0 {
		sb.WriteString("\n")
	}
}

// buildUpdateProto generates the content of a *.update.proto file.
func buildUpdateProto(f model.File, relPath string, msgs []model.Message, extraImports []string) (string, error) {
	var sb strings.Builder
	buildProtoHeader(&sb, f, relPath, extraImports)
	for _, msg := range msgs {
		for _, opt := range msg.UpdateOptions {
			content, err := buildUpdateMessage(msg, opt)
			if err != nil {
				return "", fmt.Errorf("message %q update_message %q: %w", msg.FullName, opt.Name, err)
			}
			sb.WriteString(content)
			sb.WriteString("\n")
		}
	}
	return sb.String(), nil
}

// buildCreateProto generates the content of a *.create.proto file.
func buildCreateProto(f model.File, relPath string, msgs []model.Message, extraImports []string) (string, error) {
	var sb strings.Builder
	buildProtoHeader(&sb, f, relPath, extraImports)
	for _, msg := range msgs {
		for _, opt := range msg.CreateOptions {
			content, err := buildCreateMessage(msg, opt)
			if err != nil {
				return "", fmt.Errorf("message %q create_message %q: %w", msg.FullName, opt.Name, err)
			}
			sb.WriteString(content)
			sb.WriteString("\n")
		}
	}

	return sb.String(), nil
}

// buildUpdateMessage generates a single update message block.
func buildUpdateMessage(msg model.Message, opt model.UpdateMessageOptions) (string, error) {
	if opt.Name == "" {
		return "", fmt.Errorf("update_message annotation on %q: %w", msg.FullName, ErrNameEmpty)
	}
	if !isProtoIdentifier(opt.Name) {
		return "", fmt.Errorf("update_message annotation on %q: name %q: %w", msg.FullName, opt.Name, ErrInvalidName)
	}
	ignoreSet := stringSet(opt.IgnoreFields)
	conditionSet := stringSet(opt.ConditionFields)

	var sb strings.Builder
	fmt.Fprintf(&sb, "message %s {\n", opt.Name)
	fmt.Fprintf(&sb, "  option (gcode.update_source) = %q;\n\n", msg.Name)

	fieldNum := 1
	for _, f := range msg.Fields {
		if ignoreSet[f.Name] {
			continue
		}
		line, err := protoFieldLine(f, !conditionSet[f.Name], fieldNum)
		if err != nil {
			return "", fmt.Errorf("field %q: %w", f.Name, err)
		}
		fmt.Fprintf(&sb, "  %s\n", line)
		fieldNum++
	}
	sb.WriteString("}\n")
	return sb.String(), nil
}

// buildCreateMessage generates a single create message block.
func buildCreateMessage(msg model.Message, opt model.CreateMessageOptions) (string, error) {
	if opt.Name == "" {
		return "", fmt.Errorf("create_message annotation on %q: %w", msg.FullName, ErrNameEmpty)
	}
	if !isProtoIdentifier(opt.Name) {
		return "", fmt.Errorf("create_message annotation on %q: name %q: %w", msg.FullName, opt.Name, ErrInvalidName)
	}
	ignoreSet := stringSet(opt.IgnoreFields)
	requiredSet := stringSet(opt.RequiredFields)

	var sb strings.Builder
	fmt.Fprintf(&sb, "message %s {\n", opt.Name)
	fmt.Fprintf(&sb, "  option (gcode.create_source) = %q;\n\n", msg.Name)

	fieldNum := 1
	for _, f := range msg.Fields {
		if ignoreSet[f.Name] {
			continue
		}
		// required_fields forces non-optional; otherwise use original optionality.
		makeOptional := !requiredSet[f.Name]
		line, err := protoFieldLine(f, makeOptional, fieldNum)
		if err != nil {
			return "", fmt.Errorf("field %q: %w", f.Name, err)
		}
		fmt.Fprintf(&sb, "  %s\n", line)
		fieldNum++
	}
	sb.WriteString("}\n")
	return sb.String(), nil
}

// protoFieldLine renders a single proto field declaration.
// makeOptional=true adds the "optional" keyword for scalar and enum fields.
// Message-type fields never get "optional" (they are inherently nullable in proto3).
// Repeated fields keep "repeated" regardless of makeOptional.
// Field-level gcode annotations (gorm.column) are preserved in the output.
func protoFieldLine(f model.Field, makeOptional bool, fieldNum int) (string, error) {
	typeStr := protoTypeName(f)

	// Build field-level annotation options.
	var opts []string
	if f.GormOptions != nil && f.GormOptions.Column != "" {
		opts = append(opts, fmt.Sprintf("(gcode.field).gorm.column = %q", f.GormOptions.Column))
	}

	optStr := ""
	if len(opts) > 0 {
		optStr = " [" + strings.Join(opts, ", ") + "]"
	}

	if f.Cardinality == model.CardinalityRepeated {
		return fmt.Sprintf("repeated %s %s = %d%s;", typeStr, f.Name, fieldNum, optStr), nil
	}
	// Message-type fields are inherently nullable (pointer in Go); "optional" has no effect.
	if f.Type.Kind == model.FieldKindMessage {
		return fmt.Sprintf("%s %s = %d%s;", typeStr, f.Name, fieldNum, optStr), nil
	}
	if makeOptional {
		return fmt.Sprintf("optional %s %s = %d%s;", typeStr, f.Name, fieldNum, optStr), nil
	}
	return fmt.Sprintf("%s %s = %d%s;", typeStr, f.Name, fieldNum, optStr), nil
}

// protoTypeName returns the proto type string for a field.
func protoTypeName(f model.Field) string {
	switch f.Type.Kind {
	case model.FieldKindScalar:
		return string(f.Type.Scalar)
	case model.FieldKindEnum:
		return f.Type.Name
	default:
		return f.Type.Name
	}
}

// collectImports builds the import list for a generated proto file.
// Always includes the original proto file and gcode/options.proto.
// extraImports are additional imports needed for cross-file type references.
func collectImports(relPath string, extraImports []string) []string {
	seen := map[string]bool{
		relPath:               true,
		"gcode/options.proto": true,
	}
	result := []string{relPath, "gcode/options.proto"}
	for _, imp := range extraImports {
		if !seen[imp] {
			seen[imp] = true
			result = append(result, imp)
		}
	}
	return result
}

// typeSourceIndex builds a FullName → source proto file path mapping from all
// parsed files. Used by collectExternalImports to resolve cross-file type
// references in derived messages.
func typeSourceIndex(files []model.File) map[string]string {
	idx := make(map[string]string)
	for _, f := range files {
		collectTypeSources(f.Messages, f.Enums, f.Path, idx)
	}
	return idx
}

// collectTypeSources recursively maps message and enum FullNames to their
// source proto file path.
func collectTypeSources(msgs []model.Message, enums []model.Enum, filePath string, idx map[string]string) {
	for _, msg := range msgs {
		idx[msg.FullName] = filePath
		collectTypeSources(msg.Messages, msg.Enums, filePath, idx)
	}
	for _, enum := range enums {
		idx[enum.FullName] = filePath
	}
}

// collectExternalImports scans the fields of derived messages and returns
// the import paths of proto files that define referenced enum or message types
// from other files.
func collectExternalImports(msgs []model.Message, typeIdx map[string]string, selfPath string) []string {
	seen := make(map[string]bool)
	var imports []string
	for _, msg := range msgs {
		for _, f := range msg.Fields {
			if f.Type.Kind != model.FieldKindEnum && f.Type.Kind != model.FieldKindMessage {
				continue
			}
			srcFile, ok := typeIdx[f.Type.FullName]
			if !ok || srcFile == selfPath {
				continue
			}
			if !seen[srcFile] {
				seen[srcFile] = true
				imports = append(imports, srcFile)
			}
		}
	}
	return imports
}

// stringSet converts a slice to a set for O(1) lookup.
func stringSet(ss []string) map[string]bool {
	m := make(map[string]bool, len(ss))
	for _, s := range ss {
		m[s] = true
	}
	return m
}

// protoBaseName strips the .proto suffix from a relative path and returns
// just the base filename without extension (e.g. "subdir/user.proto" → "user").
func protoBaseName(relPath string) string {
	base := filepath.Base(relPath)
	return strings.TrimSuffix(base, ".proto")
}

// protoIdentifierRe matches a valid proto identifier: a letter or underscore
// followed by zero or more letters, digits, or underscores.
var protoIdentifierRe = regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_]*$`)

// isProtoIdentifier reports whether s is a valid proto identifier.
// Used to validate annotation-supplied message names before writing them
// into generated proto source.
func isProtoIdentifier(s string) bool {
	return protoIdentifierRe.MatchString(s)
}
