package app

import (
	"errors"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/pinealctx/gcode/internal/config"
)

func TestRunGenTS_BasicRouting(t *testing.T) {
	t.Parallel()

	inputDir := t.TempDir()
	outputDir := t.TempDir()

	writeFile(t, filepath.Join(inputDir, "user.proto"), `syntax = "proto3";
package test;
option go_package = "test";

message User {
  string name = 1;
  int32  age  = 2;
}
`)

	err := RunGenTS(t.Context(), []string{"-in", inputDir, "-out", outputDir})
	if err != nil {
		t.Fatalf("RunGenTS returned error: %v", err)
	}

	// Verify the generated .pb.ts file exists and contains expected output.
	tsContent, err := os.ReadFile(filepath.Join(outputDir, "user.pb.ts"))
	if err != nil {
		t.Fatalf("failed to read generated file: %v", err)
	}
	s := string(tsContent)
	if !strings.Contains(s, "// Code generated by gcode. DO NOT EDIT.") {
		t.Error("generated file missing header comment")
	}
	if !strings.Contains(s, "export interface User {") {
		t.Error("generated file missing User interface")
	}
	if !strings.Contains(s, "name: string") {
		t.Error("generated file missing name field")
	}
	if !strings.Contains(s, "age: number") {
		t.Error("generated file missing age field")
	}
}

func TestRunGenTS_MissingFlags(t *testing.T) {
	t.Parallel()

	err := RunGenTS(t.Context(), []string{})
	if err == nil {
		t.Fatal("expected error for missing flags, got nil")
	}
	if !errors.Is(err, config.ErrMissingTSInputDir) {
		t.Errorf("error = %q, want ErrMissingTSInputDir", err.Error())
	}
}

func TestRunGenTS_NoProtoFiles(t *testing.T) {
	t.Parallel()

	inputDir := t.TempDir()
	outputDir := t.TempDir()

	err := RunGenTS(t.Context(), []string{"-in", inputDir, "-out", outputDir})
	if err == nil {
		t.Fatal("expected error for empty input directory, got nil")
	}
	if !errors.Is(err, ErrNoProtoFiles) {
		t.Errorf("error = %q, want ErrNoProtoFiles", err.Error())
	}
}

func TestRunGenTS_InvalidProto(t *testing.T) {
	t.Parallel()

	inputDir := t.TempDir()
	outputDir := t.TempDir()

	writeFile(t, filepath.Join(inputDir, "bad.proto"), `this is not valid proto syntax !!!`)

	err := RunGenTS(t.Context(), []string{"-in", inputDir, "-out", outputDir})
	if err == nil {
		t.Fatal("expected error for invalid proto, got nil")
	}
}

func TestRunGenTS_InputDirNotExist(t *testing.T) {
	t.Parallel()

	outputDir := t.TempDir()
	nonExistent := filepath.Join(t.TempDir(), "no-such-dir")

	err := RunGenTS(t.Context(), []string{"-in", nonExistent, "-out", outputDir})
	if err == nil {
		t.Fatal("expected error for non-existent input dir, got nil")
	}
	if !errors.Is(err, fs.ErrNotExist) {
		t.Errorf("expected fs.ErrNotExist, got %T: %v", err, err)
	}
}

func TestTsOutputFileName(t *testing.T) {
	t.Parallel()

	tests := []struct {
		input, want string
	}{
		{"person.proto", "person.pb.ts"},
		{"subdir/person.proto", "subdir/person.pb.ts"},
		{"a/b/c/user_service.proto", "a/b/c/user_service.pb.ts"},
	}
	for _, tt := range tests {
		got := tsOutputFileName(tt.input)
		if got != tt.want {
			t.Errorf("tsOutputFileName(%q) = %q, want %q", tt.input, got, tt.want)
		}
	}
}

// TestRunGenTS_SubdirectorySameBasename verifies that two proto files in different
// subdirectories with the same basename are generated into separate output paths
// (sub1/user.pb.ts and sub2/user.pb.ts) without collision.
func TestRunGenTS_SubdirectorySameBasename(t *testing.T) {
	t.Parallel()

	inputDir := t.TempDir()
	outputDir := t.TempDir()

	sub1 := filepath.Join(inputDir, "sub1")
	sub2 := filepath.Join(inputDir, "sub2")
	if err := os.MkdirAll(sub1, 0o755); err != nil {
		t.Fatalf("mkdir sub1: %v", err)
	}
	if err := os.MkdirAll(sub2, 0o755); err != nil {
		t.Fatalf("mkdir sub2: %v", err)
	}

	writeFile(t, filepath.Join(sub1, "user.proto"), `syntax = "proto3";
package pkg_a;
option go_package = "example.com/test;testpb";
message UserA { string name = 1; }
`)
	writeFile(t, filepath.Join(sub2, "user.proto"), `syntax = "proto3";
package pkg_b;
option go_package = "example.com/test;testpb";
message UserB { int32 id = 1; }
`)

	err := RunGenTS(t.Context(), []string{"-in", inputDir, "-out", outputDir})
	if err != nil {
		t.Fatalf("RunGenTS returned unexpected error: %v", err)
	}

	// Verify both output files exist with correct content in their subdirectories.
	type subCheck struct {
		sub          string
		ifaceName    string
		expectedType string
	}
	for _, sc := range []subCheck{{"sub1", "UserA", "name: string"}, {"sub2", "UserB", "id: number"}} {
		path := filepath.Join(outputDir, sc.sub, "user.pb.ts")
		data, readErr := os.ReadFile(path)
		if readErr != nil {
			t.Fatalf("failed to read %s: %v", path, readErr)
		}
		s := string(data)
		if !strings.Contains(s, "// Code generated by gcode. DO NOT EDIT.") {
			t.Errorf("%s missing generated-code header", path)
		}
		if !strings.Contains(s, "export interface "+sc.ifaceName+" {") {
			t.Errorf("%s missing %s interface", path, sc.ifaceName)
		}
		if !strings.Contains(s, sc.expectedType) {
			t.Errorf("%s missing expected field type %q", path, sc.expectedType)
		}
	}
}
