// Code generated by gcode. DO NOT EDIT.
// source: all_validate.proto

package dao

import (
	"fmt"
	"github.com/pinealctx/gcode/validateruntime"
)

func (x *AllValidate) Validate() error {
	if x.UGte < 1 {
		return &validateruntime.ValidationError{Field: "u_gte", Rule: "gte", Message: validateruntime.MsgOr("", "must be >= 1")}
	}
	if x.ULte > 1000 {
		return &validateruntime.ValidationError{Field: "u_lte", Rule: "lte", Message: validateruntime.MsgOr("", "must be <= 1000")}
	}
	{
		found := false
		for _, v := range []uint32{1, 2, 3} {
			if x.UIn == v {
				found = true
				break
			}
		}
		if !found {
			return &validateruntime.ValidationError{Field: "u_in", Rule: "in", Message: validateruntime.MsgOr("", "must be one of [1, 2, 3]")}
		}
	}
	for _, v := range []uint32{0} {
		if x.UNotIn == v {
			return &validateruntime.ValidationError{Field: "u_not_in", Rule: "not_in", Message: validateruntime.MsgOr("", "must not be one of [0]")}
		}
	}
	if x.FGt <= 0 {
		return &validateruntime.ValidationError{Field: "f_gt", Rule: "gt", Message: validateruntime.MsgOr("", "must be > 0")}
	}
	if x.DLte > 1 {
		return &validateruntime.ValidationError{Field: "d_lte", Rule: "lte", Message: validateruntime.MsgOr("", "must be <= 1")}
	}
	if x.SIn != "" {
		{
			found := false
			for _, v := range []string{"a", "b", "c"} {
				if x.SIn == v {
					found = true
					break
				}
			}
			if !found {
				return &validateruntime.ValidationError{Field: "s_in", Rule: "in", Message: validateruntime.MsgOr("", "must be one of [a, b, c]")}
			}
		}
	}
	if x.SNotIn != "" {
		for _, v := range []string{"x", "y"} {
			if x.SNotIn == v {
				return &validateruntime.ValidationError{Field: "s_not_in", Rule: "not_in", Message: validateruntime.MsgOr("", "must not be one of [x, y]")}
			}
		}
	}
	{
		found := false
		for _, v := range []int32{1, 2, -1} {
			if x.IIn == v {
				found = true
				break
			}
		}
		if !found {
			return &validateruntime.ValidationError{Field: "i_in", Rule: "in", Message: validateruntime.MsgOr("", "must be one of [1, 2, -1]")}
		}
	}
	if x.SUri != "" {
		if !validateruntime.IsURI(x.SUri) {
			return &validateruntime.ValidationError{Field: "s_uri", Rule: "uri", Message: validateruntime.MsgOr("", "must be a valid URI")}
		}
	}
	if x.OStatus != nil {
		switch *x.OStatus {
		case Status_STATUS_UNSPECIFIED, Status_STATUS_ACTIVE, Status_STATUS_INACTIVE:
		// ok
		default:
			return &validateruntime.ValidationError{Field: "o_status", Rule: "defined_only", Message: validateruntime.MsgOr("", "must be a defined enum value")}
		}
	}
	if x.BMinmax != nil {
		if len(x.BMinmax) < 1 {
			return &validateruntime.ValidationError{Field: "b_minmax", Rule: "min_len", Message: validateruntime.MsgOr("", "length must be >= 1")}
		}
		if len(x.BMinmax) > 100 {
			return &validateruntime.ValidationError{Field: "b_minmax", Rule: "max_len", Message: validateruntime.MsgOr("", "length must be <= 100")}
		}
	}
	if len(x.RItems) < 1 {
		return &validateruntime.ValidationError{Field: "r_items", Rule: "min_items", Message: validateruntime.MsgOr("", "must have at least 1 item(s)")}
	}
	if len(x.RItems) > 5 {
		return &validateruntime.ValidationError{Field: "r_items", Rule: "max_items", Message: validateruntime.MsgOr("", "must have at most 5 item(s)")}
	}
	for i, v := range x.RItems {
		if v < 0 {
			return &validateruntime.ValidationError{Field: fmt.Sprintf("r_items[%d]", i), Rule: "gte", Message: validateruntime.MsgOr("", "must be >= 0")}
		}
	}
	for i, v := range x.RStrIn {
		{
			found := false
			for _, sv := range []string{"foo", "bar"} {
				if v == sv {
					found = true
					break
				}
			}
			if !found {
				return &validateruntime.ValidationError{Field: fmt.Sprintf("r_str_in[%d]", i), Rule: "in", Message: validateruntime.MsgOr("", "must be one of [foo, bar]")}
			}
		}
	}
	for i, v := range x.RStrNotIn {
		for _, sv := range []string{"bad"} {
			if v == sv {
				return &validateruntime.ValidationError{Field: fmt.Sprintf("r_str_not_in[%d]", i), Rule: "not_in", Message: validateruntime.MsgOr("", "must not be one of [bad]")}
			}
		}
	}
	for i, v := range x.RIntIn {
		{
			found := false
			for _, iv := range []int32{1, 2, 3} {
				if v == iv {
					found = true
					break
				}
			}
			if !found {
				return &validateruntime.ValidationError{Field: fmt.Sprintf("r_int_in[%d]", i), Rule: "in", Message: validateruntime.MsgOr("", "must be one of [1, 2, 3]")}
			}
		}
	}
	for i, v := range x.RUintNotIn {
		for _, uv := range []uint32{0} {
			if v == uv {
				return &validateruntime.ValidationError{Field: fmt.Sprintf("r_uint_not_in[%d]", i), Rule: "not_in", Message: validateruntime.MsgOr("", "must not be one of [0]")}
			}
		}
	}
	if x.IGtLt <= -10 {
		return &validateruntime.ValidationError{Field: "i_gt_lt", Rule: "gt", Message: validateruntime.MsgOr("", "must be > -10")}
	}
	if x.IGtLt >= 10 {
		return &validateruntime.ValidationError{Field: "i_gt_lt", Rule: "lt", Message: validateruntime.MsgOr("", "must be < 10")}
	}
	if x.UGtLt <= 5 {
		return &validateruntime.ValidationError{Field: "u_gt_lt", Rule: "gt", Message: validateruntime.MsgOr("", "must be > 5")}
	}
	if x.UGtLt >= 100 {
		return &validateruntime.ValidationError{Field: "u_gt_lt", Rule: "lt", Message: validateruntime.MsgOr("", "must be < 100")}
	}
	if x.FLt >= 99.5 {
		return &validateruntime.ValidationError{Field: "f_lt", Rule: "lt", Message: validateruntime.MsgOr("", "must be < 99.5")}
	}
	if x.DGt <= -1 {
		return &validateruntime.ValidationError{Field: "d_gt", Rule: "gt", Message: validateruntime.MsgOr("", "must be > -1")}
	}
	if x.SPattern != "" {
		if !validateruntime.MatchPattern(x.SPattern, "^[A-Z][a-z]+$") {
			return &validateruntime.ValidationError{Field: "s_pattern", Rule: "pattern", Message: validateruntime.MsgOr("", "must match pattern ^[A-Z][a-z]+$")}
		}
	}
	return nil
}
