// Code generated by gcode. DO NOT EDIT.
// source: all_types.create.proto

package dao

import (
	"fmt"
	"github.com/pinealctx/gcode/runtime"
	"math"
)

type AllScalarsCreate struct {
	FSint32   *int32   `json:"fSint32" gorm:"column:f_sint32"`
	FSint64   *int64   `json:"fSint64" gorm:"column:f_sint64"`
	FSfixed32 *int32   `json:"fSfixed32" gorm:"column:f_sfixed32"`
	FSfixed64 *int64   `json:"fSfixed64" gorm:"column:f_sfixed64"`
	FFixed32  *uint32  `json:"fFixed32" gorm:"column:f_fixed32"`
	FFixed64  *uint64  `json:"fFixed64" gorm:"column:f_fixed64"`
	FUint32   *uint32  `json:"fUint32" gorm:"column:f_uint32"`
	FUint64   *uint64  `json:"fUint64" gorm:"column:f_uint64"`
	FFloat    *float32 `json:"fFloat" gorm:"column:f_float"`
	FBytes    []byte   `json:"fBytes" gorm:"column:f_bytes_col"`
}

func (AllScalarsCreate) TableName() string { return "all_scalars" }

// Size returns the protobuf wire size of AllScalarsCreate.
func (a *AllScalarsCreate) Size() int {
	if a == nil {
		return 0
	}
	var n int
	if a.FSint32 != nil {
		n += 1 + runtime.SizeSint32(*a.FSint32)
	}
	if a.FSint64 != nil {
		n += 1 + runtime.SizeSint64(*a.FSint64)
	}
	if a.FSfixed32 != nil {
		n += 1 + 4
	}
	if a.FSfixed64 != nil {
		n += 1 + 8
	}
	if a.FFixed32 != nil {
		n += 1 + 4
	}
	if a.FFixed64 != nil {
		n += 1 + 8
	}
	if a.FUint32 != nil {
		n += 1 + runtime.SizeUint32(*a.FUint32)
	}
	if a.FUint64 != nil {
		n += 1 + runtime.SizeUint64(*a.FUint64)
	}
	if a.FFloat != nil {
		n += 1 + 4
	}
	if a.FBytes != nil {
		n += 1 + runtime.SizeBytes(a.FBytes)
	}
	return n
}

// MarshalBinary implements encoding.BinaryMarshaler.
func (a *AllScalarsCreate) MarshalBinary() ([]byte, error) {
	return a.MarshalAppend(make([]byte, 0, a.Size()))
}

// MarshalAppend appends the protobuf wire encoding of AllScalarsCreate to b.
func (a *AllScalarsCreate) MarshalAppend(b []byte) ([]byte, error) {
	if a.FSint32 != nil {
		b = runtime.AppendTag(b, 1, runtime.WireVarint)
		b = runtime.AppendSint32(b, *a.FSint32)
	}
	if a.FSint64 != nil {
		b = runtime.AppendTag(b, 2, runtime.WireVarint)
		b = runtime.AppendSint64(b, *a.FSint64)
	}
	if a.FSfixed32 != nil {
		b = runtime.AppendTag(b, 3, runtime.WireFixed32)
		b = runtime.AppendFixed32(b, uint32(*a.FSfixed32))
	}
	if a.FSfixed64 != nil {
		b = runtime.AppendTag(b, 4, runtime.WireFixed64)
		b = runtime.AppendFixed64(b, uint64(*a.FSfixed64))
	}
	if a.FFixed32 != nil {
		b = runtime.AppendTag(b, 5, runtime.WireFixed32)
		b = runtime.AppendFixed32(b, *a.FFixed32)
	}
	if a.FFixed64 != nil {
		b = runtime.AppendTag(b, 6, runtime.WireFixed64)
		b = runtime.AppendFixed64(b, *a.FFixed64)
	}
	if a.FUint32 != nil {
		b = runtime.AppendTag(b, 7, runtime.WireVarint)
		b = runtime.AppendVarint(b, uint64(*a.FUint32))
	}
	if a.FUint64 != nil {
		b = runtime.AppendTag(b, 8, runtime.WireVarint)
		b = runtime.AppendVarint(b, *a.FUint64)
	}
	if a.FFloat != nil {
		b = runtime.AppendTag(b, 9, runtime.WireFixed32)
		b = runtime.AppendFloat(b, *a.FFloat)
	}
	if a.FBytes != nil {
		b = runtime.AppendTag(b, 10, runtime.WireBytes)
		b = runtime.AppendBytes(b, a.FBytes)
	}
	return b, nil
}

// unmarshalFrom decodes a protobuf wire-format message from b.
// Returns the number of bytes consumed.
// If lenient is true, duplicate non-repeated fields use last-one-wins.
// depth is the remaining nesting budget; callers pass runtime.DefaultRecursionLimit.
func (a *AllScalarsCreate) unmarshalFrom(b []byte, lenient bool, depth int) (int, error) {
	if depth <= 0 {
		return 0, runtime.ErrNestingDepth
	}
	var seen [2]uint64
	off := 0
	for off < len(b) {
		fieldNum, wireType, n := runtime.ConsumeTag(b[off:])
		if n < 0 {
			if n == -2 {
				return 0, fmt.Errorf("field tag: %w", runtime.ErrOverflow)
			}
			return 0, fmt.Errorf("field tag: %w", runtime.ErrTruncated)
		}
		off += n

		switch fieldNum {
		case 1:
			if seen[0]&1 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 1: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 1
			if wireType != runtime.WireVarint {
				return 0, fmt.Errorf("field 1: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeVarint(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 1: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 1: %w", runtime.ErrTruncated)
			}
			tmp := runtime.DecodeZigZag32(v)
			a.FSint32 = &tmp
			off += n
		case 2:
			if seen[0]&2 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 2: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 2
			if wireType != runtime.WireVarint {
				return 0, fmt.Errorf("field 2: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeVarint(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 2: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 2: %w", runtime.ErrTruncated)
			}
			tmp := runtime.DecodeZigZag64(v)
			a.FSint64 = &tmp
			off += n
		case 3:
			if seen[0]&4 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 3: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 4
			if wireType != runtime.WireFixed32 {
				return 0, fmt.Errorf("field 3: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeFixed32(b[off:])
			if n < 0 {
				return 0, fmt.Errorf("field 3: %w", runtime.ErrTruncated)
			}
			tmp := int32(v)
			a.FSfixed32 = &tmp
			off += n
		case 4:
			if seen[0]&8 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 4: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 8
			if wireType != runtime.WireFixed64 {
				return 0, fmt.Errorf("field 4: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeFixed64(b[off:])
			if n < 0 {
				return 0, fmt.Errorf("field 4: %w", runtime.ErrTruncated)
			}
			tmp := int64(v)
			a.FSfixed64 = &tmp
			off += n
		case 5:
			if seen[0]&16 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 5: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 16
			if wireType != runtime.WireFixed32 {
				return 0, fmt.Errorf("field 5: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeFixed32(b[off:])
			if n < 0 {
				return 0, fmt.Errorf("field 5: %w", runtime.ErrTruncated)
			}
			tmp := v
			a.FFixed32 = &tmp
			off += n
		case 6:
			if seen[0]&32 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 6: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 32
			if wireType != runtime.WireFixed64 {
				return 0, fmt.Errorf("field 6: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeFixed64(b[off:])
			if n < 0 {
				return 0, fmt.Errorf("field 6: %w", runtime.ErrTruncated)
			}
			tmp := v
			a.FFixed64 = &tmp
			off += n
		case 7:
			if seen[0]&64 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 7: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 64
			if wireType != runtime.WireVarint {
				return 0, fmt.Errorf("field 7: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeVarint(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 7: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 7: %w", runtime.ErrTruncated)
			}
			tmp := uint32(v)
			a.FUint32 = &tmp
			off += n
		case 8:
			if seen[0]&128 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 8: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 128
			if wireType != runtime.WireVarint {
				return 0, fmt.Errorf("field 8: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeVarint(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 8: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 8: %w", runtime.ErrTruncated)
			}
			tmp := v
			a.FUint64 = &tmp
			off += n
		case 9:
			if seen[0]&256 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 9: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 256
			if wireType != runtime.WireFixed32 {
				return 0, fmt.Errorf("field 9: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeFixed32(b[off:])
			if n < 0 {
				return 0, fmt.Errorf("field 9: %w", runtime.ErrTruncated)
			}
			tmp := math.Float32frombits(v)
			a.FFloat = &tmp
			off += n
		case 10:
			if seen[0]&512 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 10: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 512
			if wireType != runtime.WireBytes {
				return 0, fmt.Errorf("field 10: %w", runtime.ErrWireType)
			}
			payload, n := runtime.ConsumeBytes(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 10: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 10: %w", runtime.ErrTruncated)
			}
			tmp := make([]byte, len(payload))
			copy(tmp, payload)
			a.FBytes = tmp
			off += n
		default:
			n = runtime.SkipField(b[off:], wireType)
			if n < 0 {
				if n == -3 {
					return 0, fmt.Errorf("unknown field %d: %w", fieldNum, runtime.ErrUnknownWireType)
				}
				return 0, fmt.Errorf("unknown field %d (wire type %d): %w", fieldNum, wireType, runtime.ErrTruncated)
			}
			off += n
		}
	}
	return off, nil
}

// UnmarshalBinary implements encoding.BinaryUnmarshaler.
// Duplicate non-repeated fields return an error.
func (a *AllScalarsCreate) UnmarshalBinary(data []byte) error {
	_, err := a.unmarshalFrom(data, false, runtime.DefaultRecursionLimit)
	return err
}

// UnmarshalBinaryLenient unmarshals like UnmarshalBinary but allows
// duplicate non-repeated fields, keeping the last value.
func (a *AllScalarsCreate) UnmarshalBinaryLenient(data []byte) error {
	_, err := a.unmarshalFrom(data, true, runtime.DefaultRecursionLimit)
	return err
}
