// Code generated by gcode. DO NOT EDIT.
// source: all_validate.proto

package dao

import (
	"fmt"
	"github.com/pinealctx/gcode/runtime"
	"math"
)

// AllValidate covers validate constraint types not present in person.proto.
type AllValidate struct {
	UGte    uint32  `json:"uGte"`
	ULte    uint64  `json:"uLte"`
	UIn     uint32  `json:"uIn"`
	UNotIn  uint32  `json:"uNotIn"`
	FGt     float32 `json:"fGt"`
	DLte    float64 `json:"dLte"`
	SIn     string  `json:"sIn"`
	SNotIn  string  `json:"sNotIn"`
	IIn     int32   `json:"iIn"`
	SUri    string  `json:"sUri"`
	OStatus *Status `json:"oStatus"`
	BMinmax []byte  `json:"bMinmax"`
	RItems  []int32 `json:"rItems"`
	// exclusive bounds for signed int
	IGtLt int32 `json:"iGtLt"`
	// exclusive bounds for unsigned int
	UGtLt uint32 `json:"uGtLt"`
	// exclusiveMaximum for float
	FLt float32 `json:"fLt"`
	// exclusiveMinimum for double
	DGt float64 `json:"dGt"`
	// pattern for string
	SPattern string `json:"sPattern"`
}

// Size returns the protobuf wire size of AllValidate.
func (x *AllValidate) Size() int {
	if x == nil {
		return 0
	}
	var n int
	if x.UGte != 0 {
		n += 1 + runtime.SizeUint32(x.UGte)
	}
	if x.ULte != 0 {
		n += 1 + runtime.SizeUint64(x.ULte)
	}
	if x.UIn != 0 {
		n += 1 + runtime.SizeUint32(x.UIn)
	}
	if x.UNotIn != 0 {
		n += 1 + runtime.SizeUint32(x.UNotIn)
	}
	if !runtime.IsZeroFloat(x.FGt) {
		n += 1 + 4
	}
	if !runtime.IsZeroDouble(x.DLte) {
		n += 1 + 8
	}
	if len(x.SIn) > 0 {
		n += 1 + runtime.SizeString(x.SIn)
	}
	if len(x.SNotIn) > 0 {
		n += 1 + runtime.SizeString(x.SNotIn)
	}
	if x.IIn != 0 {
		n += 1 + runtime.SizeInt32(x.IIn)
	}
	if len(x.SUri) > 0 {
		n += 1 + runtime.SizeString(x.SUri)
	}
	if x.OStatus != nil {
		n += 1 + runtime.SizeEnum(int32(*x.OStatus))
	}
	if len(x.BMinmax) > 0 {
		n += 1 + runtime.SizeBytes(x.BMinmax)
	}
	if len(x.RItems) > 0 {
		var es int
		for _, v := range x.RItems {
			es += runtime.SizeInt32(v)
		}
		n += 1 + runtime.SizeVarint(uint64(es)) + es
	}
	if x.IGtLt != 0 {
		n += 1 + runtime.SizeInt32(x.IGtLt)
	}
	if x.UGtLt != 0 {
		n += 1 + runtime.SizeUint32(x.UGtLt)
	}
	if !runtime.IsZeroFloat(x.FLt) {
		n += 2 + 4
	}
	if !runtime.IsZeroDouble(x.DGt) {
		n += 2 + 8
	}
	if len(x.SPattern) > 0 {
		n += 2 + runtime.SizeString(x.SPattern)
	}
	return n
}

// MarshalBinary implements encoding.BinaryMarshaler.
func (x *AllValidate) MarshalBinary() ([]byte, error) {
	return x.MarshalAppend(make([]byte, 0, x.Size()))
}

// MarshalAppend appends the protobuf wire encoding of AllValidate to b.
func (x *AllValidate) MarshalAppend(b []byte) ([]byte, error) {
	if x.UGte != 0 {
		b = runtime.AppendTag(b, 1, runtime.WireVarint)
		b = runtime.AppendVarint(b, uint64(x.UGte))
	}
	if x.ULte != 0 {
		b = runtime.AppendTag(b, 2, runtime.WireVarint)
		b = runtime.AppendVarint(b, x.ULte)
	}
	if x.UIn != 0 {
		b = runtime.AppendTag(b, 3, runtime.WireVarint)
		b = runtime.AppendVarint(b, uint64(x.UIn))
	}
	if x.UNotIn != 0 {
		b = runtime.AppendTag(b, 4, runtime.WireVarint)
		b = runtime.AppendVarint(b, uint64(x.UNotIn))
	}
	if !runtime.IsZeroFloat(x.FGt) {
		b = runtime.AppendTag(b, 5, runtime.WireFixed32)
		b = runtime.AppendFloat(b, x.FGt)
	}
	if !runtime.IsZeroDouble(x.DLte) {
		b = runtime.AppendTag(b, 6, runtime.WireFixed64)
		b = runtime.AppendDouble(b, x.DLte)
	}
	if len(x.SIn) > 0 {
		b = runtime.AppendTag(b, 7, runtime.WireBytes)
		b = runtime.AppendString(b, x.SIn)
	}
	if len(x.SNotIn) > 0 {
		b = runtime.AppendTag(b, 8, runtime.WireBytes)
		b = runtime.AppendString(b, x.SNotIn)
	}
	if x.IIn != 0 {
		b = runtime.AppendTag(b, 9, runtime.WireVarint)
		b = runtime.AppendVarint(b, uint64(x.IIn))
	}
	if len(x.SUri) > 0 {
		b = runtime.AppendTag(b, 10, runtime.WireBytes)
		b = runtime.AppendString(b, x.SUri)
	}
	if x.OStatus != nil {
		b = runtime.AppendTag(b, 11, runtime.WireVarint)
		b = runtime.AppendVarint(b, uint64(*x.OStatus))
	}
	if len(x.BMinmax) > 0 {
		b = runtime.AppendTag(b, 12, runtime.WireBytes)
		b = runtime.AppendBytes(b, x.BMinmax)
	}
	if len(x.RItems) > 0 {
		b = runtime.AppendTag(b, 13, runtime.WireBytes)
		var es int
		for _, v := range x.RItems {
			es += runtime.SizeInt32(v)
		}
		b = runtime.AppendVarint(b, uint64(es))
		for _, v := range x.RItems {
			b = runtime.AppendVarint(b, uint64(v))
		}
	}
	if x.IGtLt != 0 {
		b = runtime.AppendTag(b, 14, runtime.WireVarint)
		b = runtime.AppendVarint(b, uint64(x.IGtLt))
	}
	if x.UGtLt != 0 {
		b = runtime.AppendTag(b, 15, runtime.WireVarint)
		b = runtime.AppendVarint(b, uint64(x.UGtLt))
	}
	if !runtime.IsZeroFloat(x.FLt) {
		b = runtime.AppendTag(b, 16, runtime.WireFixed32)
		b = runtime.AppendFloat(b, x.FLt)
	}
	if !runtime.IsZeroDouble(x.DGt) {
		b = runtime.AppendTag(b, 17, runtime.WireFixed64)
		b = runtime.AppendDouble(b, x.DGt)
	}
	if len(x.SPattern) > 0 {
		b = runtime.AppendTag(b, 18, runtime.WireBytes)
		b = runtime.AppendString(b, x.SPattern)
	}
	return b, nil
}

// DeepClone returns a deep copy of AllValidate with no shared memory.
func (x *AllValidate) DeepClone() *AllValidate {
	if x == nil {
		return nil
	}
	clone := *x
	if x.OStatus != nil {
		v := *x.OStatus
		clone.OStatus = &v
	}
	if x.BMinmax != nil {
		clone.BMinmax = make([]byte, len(x.BMinmax))
		copy(clone.BMinmax, x.BMinmax)
	}
	if x.RItems != nil {
		clone.RItems = make([]int32, len(x.RItems))
		copy(clone.RItems, x.RItems)
	}
	return &clone
}

// unmarshalFrom decodes a protobuf wire-format message from b.
// Returns the number of bytes consumed.
// If lenient is true, duplicate non-repeated fields use last-one-wins.
// depth is the remaining nesting budget; callers pass runtime.DefaultRecursionLimit.
func (x *AllValidate) unmarshalFrom(b []byte, lenient bool, depth int) (int, error) {
	if depth <= 0 {
		return 0, runtime.ErrNestingDepth
	}
	var seen [2]uint64
	off := 0
	for off < len(b) {
		fieldNum, wireType, n := runtime.ConsumeTag(b[off:])
		if n < 0 {
			if n == -2 {
				return 0, fmt.Errorf("field tag: %w", runtime.ErrOverflow)
			}
			return 0, fmt.Errorf("field tag: %w", runtime.ErrTruncated)
		}
		off += n

		switch fieldNum {
		case 1:
			if seen[0]&1 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 1: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 1
			if wireType != runtime.WireVarint {
				return 0, fmt.Errorf("field 1: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeVarint(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 1: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 1: %w", runtime.ErrTruncated)
			}
			x.UGte = uint32(v)
			off += n
		case 2:
			if seen[0]&2 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 2: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 2
			if wireType != runtime.WireVarint {
				return 0, fmt.Errorf("field 2: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeVarint(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 2: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 2: %w", runtime.ErrTruncated)
			}
			x.ULte = v
			off += n
		case 3:
			if seen[0]&4 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 3: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 4
			if wireType != runtime.WireVarint {
				return 0, fmt.Errorf("field 3: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeVarint(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 3: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 3: %w", runtime.ErrTruncated)
			}
			x.UIn = uint32(v)
			off += n
		case 4:
			if seen[0]&8 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 4: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 8
			if wireType != runtime.WireVarint {
				return 0, fmt.Errorf("field 4: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeVarint(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 4: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 4: %w", runtime.ErrTruncated)
			}
			x.UNotIn = uint32(v)
			off += n
		case 5:
			if seen[0]&16 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 5: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 16
			if wireType != runtime.WireFixed32 {
				return 0, fmt.Errorf("field 5: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeFixed32(b[off:])
			if n < 0 {
				return 0, fmt.Errorf("field 5: %w", runtime.ErrTruncated)
			}
			x.FGt = math.Float32frombits(v)
			off += n
		case 6:
			if seen[0]&32 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 6: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 32
			if wireType != runtime.WireFixed64 {
				return 0, fmt.Errorf("field 6: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeFixed64(b[off:])
			if n < 0 {
				return 0, fmt.Errorf("field 6: %w", runtime.ErrTruncated)
			}
			x.DLte = math.Float64frombits(v)
			off += n
		case 7:
			if seen[0]&64 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 7: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 64
			if wireType != runtime.WireBytes {
				return 0, fmt.Errorf("field 7: %w", runtime.ErrWireType)
			}
			payload, n := runtime.ConsumeBytes(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 7: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 7: %w", runtime.ErrTruncated)
			}
			x.SIn = string(payload)
			off += n
		case 8:
			if seen[0]&128 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 8: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 128
			if wireType != runtime.WireBytes {
				return 0, fmt.Errorf("field 8: %w", runtime.ErrWireType)
			}
			payload, n := runtime.ConsumeBytes(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 8: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 8: %w", runtime.ErrTruncated)
			}
			x.SNotIn = string(payload)
			off += n
		case 9:
			if seen[0]&256 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 9: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 256
			if wireType != runtime.WireVarint {
				return 0, fmt.Errorf("field 9: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeVarint(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 9: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 9: %w", runtime.ErrTruncated)
			}
			x.IIn = int32(v)
			off += n
		case 10:
			if seen[0]&512 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 10: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 512
			if wireType != runtime.WireBytes {
				return 0, fmt.Errorf("field 10: %w", runtime.ErrWireType)
			}
			payload, n := runtime.ConsumeBytes(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 10: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 10: %w", runtime.ErrTruncated)
			}
			x.SUri = string(payload)
			off += n
		case 11:
			if seen[0]&1024 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 11: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 1024
			if wireType != runtime.WireVarint {
				return 0, fmt.Errorf("field 11: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeVarint(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 11: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 11: %w", runtime.ErrTruncated)
			}
			tmp := Status(v)
			x.OStatus = &tmp
			off += n
		case 12:
			if seen[0]&2048 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 12: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 2048
			if wireType != runtime.WireBytes {
				return 0, fmt.Errorf("field 12: %w", runtime.ErrWireType)
			}
			payload, n := runtime.ConsumeBytes(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 12: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 12: %w", runtime.ErrTruncated)
			}
			tmp := make([]byte, len(payload))
			copy(tmp, payload)
			x.BMinmax = tmp
			off += n
		case 13:
			if wireType != runtime.WireBytes {
				return 0, fmt.Errorf("field 13: %w", runtime.ErrWireType)
			}
			packed, n := runtime.ConsumeBytes(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 13: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 13: %w", runtime.ErrTruncated)
			}
			off += n
			for pi := 0; pi < len(packed); {
				v, pn := runtime.ConsumeVarint(packed[pi:])
				if pn < 0 {
					if pn == -2 {
						return 0, fmt.Errorf("field 13: %w", runtime.ErrOverflow)
					}
					return 0, fmt.Errorf("field 13: %w", runtime.ErrTruncated)
				}
				x.RItems = append(x.RItems, int32(v))
				pi += pn
			}
		case 14:
			if seen[0]&4096 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 14: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 4096
			if wireType != runtime.WireVarint {
				return 0, fmt.Errorf("field 14: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeVarint(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 14: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 14: %w", runtime.ErrTruncated)
			}
			x.IGtLt = int32(v)
			off += n
		case 15:
			if seen[0]&8192 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 15: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 8192
			if wireType != runtime.WireVarint {
				return 0, fmt.Errorf("field 15: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeVarint(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 15: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 15: %w", runtime.ErrTruncated)
			}
			x.UGtLt = uint32(v)
			off += n
		case 16:
			if seen[0]&16384 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 16: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 16384
			if wireType != runtime.WireFixed32 {
				return 0, fmt.Errorf("field 16: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeFixed32(b[off:])
			if n < 0 {
				return 0, fmt.Errorf("field 16: %w", runtime.ErrTruncated)
			}
			x.FLt = math.Float32frombits(v)
			off += n
		case 17:
			if seen[0]&32768 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 17: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 32768
			if wireType != runtime.WireFixed64 {
				return 0, fmt.Errorf("field 17: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeFixed64(b[off:])
			if n < 0 {
				return 0, fmt.Errorf("field 17: %w", runtime.ErrTruncated)
			}
			x.DGt = math.Float64frombits(v)
			off += n
		case 18:
			if seen[0]&65536 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 18: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 65536
			if wireType != runtime.WireBytes {
				return 0, fmt.Errorf("field 18: %w", runtime.ErrWireType)
			}
			payload, n := runtime.ConsumeBytes(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 18: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 18: %w", runtime.ErrTruncated)
			}
			x.SPattern = string(payload)
			off += n
		default:
			n = runtime.SkipField(b[off:], wireType)
			if n < 0 {
				if n == -3 {
					return 0, fmt.Errorf("unknown field %d: %w", fieldNum, runtime.ErrUnknownWireType)
				}
				return 0, fmt.Errorf("unknown field %d (wire type %d): %w", fieldNum, wireType, runtime.ErrTruncated)
			}
			off += n
		}
	}
	return off, nil
}

// UnmarshalBinary implements encoding.BinaryUnmarshaler.
// Duplicate non-repeated fields return an error.
func (x *AllValidate) UnmarshalBinary(data []byte) error {
	_, err := x.unmarshalFrom(data, false, runtime.DefaultRecursionLimit)
	return err
}

// UnmarshalBinaryLenient unmarshals like UnmarshalBinary but allows
// duplicate non-repeated fields, keeping the last value.
func (x *AllValidate) UnmarshalBinaryLenient(data []byte) error {
	_, err := x.unmarshalFrom(data, true, runtime.DefaultRecursionLimit)
	return err
}
