// Code generated by gcode. DO NOT EDIT.
// source: all_types.entity.proto

package dao

func (x *AllScalars) Validate() error {
	return nil
}

func (x *AllRepeated) Validate() error {
	for _, v := range x.RMessage {
		if err := v.Validate(); err != nil {
			return err
		}
	}
	return nil
}

func (x *TreeNode) Validate() error {
	if x.Child != nil {
		if err := x.Child.Validate(); err != nil {
			return err
		}
	}
	return nil
}
