// Code generated by gcode. DO NOT EDIT.
// source: all_types.update.proto

package dao

import (
	"fmt"
	"github.com/pinealctx/gcode/runtime"
	"math"
)

type AllScalarsUpdate struct {
	FSint32   int32    `json:"fSint32"`
	FSint64   *int64   `json:"fSint64"`
	FSfixed32 *int32   `json:"fSfixed32"`
	FSfixed64 *int64   `json:"fSfixed64"`
	FDouble   *float64 `json:"fDouble"`
	FFixed32  *uint32  `json:"fFixed32"`
	FFixed64  *uint64  `json:"fFixed64"`
	FUint32   *uint32  `json:"fUint32"`
	FUint64   *uint64  `json:"fUint64"`
	FFloat    *float32 `json:"fFloat"`
	FBytes    []byte   `json:"fBytes"`
}

// Size returns the protobuf wire size of AllScalarsUpdate.
func (x *AllScalarsUpdate) Size() int {
	if x == nil {
		return 0
	}
	var n int
	if x.FSint32 != 0 {
		n += 1 + runtime.SizeSint32(x.FSint32)
	}
	if x.FSint64 != nil {
		n += 1 + runtime.SizeSint64(*x.FSint64)
	}
	if x.FSfixed32 != nil {
		n += 1 + 4
	}
	if x.FSfixed64 != nil {
		n += 1 + 8
	}
	if x.FDouble != nil {
		n += 1 + 8
	}
	if x.FFixed32 != nil {
		n += 1 + 4
	}
	if x.FFixed64 != nil {
		n += 1 + 8
	}
	if x.FUint32 != nil {
		n += 1 + runtime.SizeUint32(*x.FUint32)
	}
	if x.FUint64 != nil {
		n += 1 + runtime.SizeUint64(*x.FUint64)
	}
	if x.FFloat != nil {
		n += 1 + 4
	}
	if x.FBytes != nil {
		n += 1 + runtime.SizeBytes(x.FBytes)
	}
	return n
}

// MarshalBinary implements encoding.BinaryMarshaler.
func (x *AllScalarsUpdate) MarshalBinary() ([]byte, error) {
	return x.MarshalAppend(make([]byte, 0, x.Size()))
}

// MarshalAppend appends the protobuf wire encoding of AllScalarsUpdate to b.
func (x *AllScalarsUpdate) MarshalAppend(b []byte) ([]byte, error) {
	if x.FSint32 != 0 {
		b = runtime.AppendTag(b, 1, runtime.WireVarint)
		b = runtime.AppendSint32(b, x.FSint32)
	}
	if x.FSint64 != nil {
		b = runtime.AppendTag(b, 2, runtime.WireVarint)
		b = runtime.AppendSint64(b, *x.FSint64)
	}
	if x.FSfixed32 != nil {
		b = runtime.AppendTag(b, 3, runtime.WireFixed32)
		b = runtime.AppendFixed32(b, uint32(*x.FSfixed32))
	}
	if x.FSfixed64 != nil {
		b = runtime.AppendTag(b, 4, runtime.WireFixed64)
		b = runtime.AppendFixed64(b, uint64(*x.FSfixed64))
	}
	if x.FDouble != nil {
		b = runtime.AppendTag(b, 5, runtime.WireFixed64)
		b = runtime.AppendDouble(b, *x.FDouble)
	}
	if x.FFixed32 != nil {
		b = runtime.AppendTag(b, 6, runtime.WireFixed32)
		b = runtime.AppendFixed32(b, *x.FFixed32)
	}
	if x.FFixed64 != nil {
		b = runtime.AppendTag(b, 7, runtime.WireFixed64)
		b = runtime.AppendFixed64(b, *x.FFixed64)
	}
	if x.FUint32 != nil {
		b = runtime.AppendTag(b, 8, runtime.WireVarint)
		b = runtime.AppendVarint(b, uint64(*x.FUint32))
	}
	if x.FUint64 != nil {
		b = runtime.AppendTag(b, 9, runtime.WireVarint)
		b = runtime.AppendVarint(b, *x.FUint64)
	}
	if x.FFloat != nil {
		b = runtime.AppendTag(b, 10, runtime.WireFixed32)
		b = runtime.AppendFloat(b, *x.FFloat)
	}
	if x.FBytes != nil {
		b = runtime.AppendTag(b, 11, runtime.WireBytes)
		b = runtime.AppendBytes(b, x.FBytes)
	}
	return b, nil
}

// unmarshalFrom decodes a protobuf wire-format message from b.
// Returns the number of bytes consumed.
// If lenient is true, duplicate non-repeated fields use last-one-wins.
// depth is the remaining nesting budget; callers pass runtime.DefaultRecursionLimit.
func (x *AllScalarsUpdate) unmarshalFrom(b []byte, lenient bool, depth int) (int, error) {
	if depth <= 0 {
		return 0, runtime.ErrNestingDepth
	}
	var seen [2]uint64
	off := 0
	for off < len(b) {
		fieldNum, wireType, n := runtime.ConsumeTag(b[off:])
		if n < 0 {
			if n == -2 {
				return 0, fmt.Errorf("field tag: %w", runtime.ErrOverflow)
			}
			return 0, fmt.Errorf("field tag: %w", runtime.ErrTruncated)
		}
		off += n

		switch fieldNum {
		case 1:
			if seen[0]&1 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 1: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 1
			if wireType != runtime.WireVarint {
				return 0, fmt.Errorf("field 1: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeVarint(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 1: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 1: %w", runtime.ErrTruncated)
			}
			x.FSint32 = runtime.DecodeZigZag32(v)
			off += n
		case 2:
			if seen[0]&2 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 2: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 2
			if wireType != runtime.WireVarint {
				return 0, fmt.Errorf("field 2: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeVarint(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 2: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 2: %w", runtime.ErrTruncated)
			}
			tmp := runtime.DecodeZigZag64(v)
			x.FSint64 = &tmp
			off += n
		case 3:
			if seen[0]&4 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 3: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 4
			if wireType != runtime.WireFixed32 {
				return 0, fmt.Errorf("field 3: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeFixed32(b[off:])
			if n < 0 {
				return 0, fmt.Errorf("field 3: %w", runtime.ErrTruncated)
			}
			tmp := int32(v)
			x.FSfixed32 = &tmp
			off += n
		case 4:
			if seen[0]&8 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 4: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 8
			if wireType != runtime.WireFixed64 {
				return 0, fmt.Errorf("field 4: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeFixed64(b[off:])
			if n < 0 {
				return 0, fmt.Errorf("field 4: %w", runtime.ErrTruncated)
			}
			tmp := int64(v)
			x.FSfixed64 = &tmp
			off += n
		case 5:
			if seen[0]&16 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 5: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 16
			if wireType != runtime.WireFixed64 {
				return 0, fmt.Errorf("field 5: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeFixed64(b[off:])
			if n < 0 {
				return 0, fmt.Errorf("field 5: %w", runtime.ErrTruncated)
			}
			tmp := math.Float64frombits(v)
			x.FDouble = &tmp
			off += n
		case 6:
			if seen[0]&32 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 6: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 32
			if wireType != runtime.WireFixed32 {
				return 0, fmt.Errorf("field 6: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeFixed32(b[off:])
			if n < 0 {
				return 0, fmt.Errorf("field 6: %w", runtime.ErrTruncated)
			}
			tmp := v
			x.FFixed32 = &tmp
			off += n
		case 7:
			if seen[0]&64 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 7: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 64
			if wireType != runtime.WireFixed64 {
				return 0, fmt.Errorf("field 7: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeFixed64(b[off:])
			if n < 0 {
				return 0, fmt.Errorf("field 7: %w", runtime.ErrTruncated)
			}
			tmp := v
			x.FFixed64 = &tmp
			off += n
		case 8:
			if seen[0]&128 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 8: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 128
			if wireType != runtime.WireVarint {
				return 0, fmt.Errorf("field 8: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeVarint(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 8: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 8: %w", runtime.ErrTruncated)
			}
			tmp := uint32(v)
			x.FUint32 = &tmp
			off += n
		case 9:
			if seen[0]&256 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 9: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 256
			if wireType != runtime.WireVarint {
				return 0, fmt.Errorf("field 9: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeVarint(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 9: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 9: %w", runtime.ErrTruncated)
			}
			tmp := v
			x.FUint64 = &tmp
			off += n
		case 10:
			if seen[0]&512 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 10: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 512
			if wireType != runtime.WireFixed32 {
				return 0, fmt.Errorf("field 10: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeFixed32(b[off:])
			if n < 0 {
				return 0, fmt.Errorf("field 10: %w", runtime.ErrTruncated)
			}
			tmp := math.Float32frombits(v)
			x.FFloat = &tmp
			off += n
		case 11:
			if seen[0]&1024 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 11: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 1024
			if wireType != runtime.WireBytes {
				return 0, fmt.Errorf("field 11: %w", runtime.ErrWireType)
			}
			payload, n := runtime.ConsumeBytes(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 11: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 11: %w", runtime.ErrTruncated)
			}
			tmp := make([]byte, len(payload))
			copy(tmp, payload)
			x.FBytes = tmp
			off += n
		default:
			n = runtime.SkipField(b[off:], wireType)
			if n < 0 {
				if n == -3 {
					return 0, fmt.Errorf("unknown field %d: %w", fieldNum, runtime.ErrUnknownWireType)
				}
				return 0, fmt.Errorf("unknown field %d (wire type %d): %w", fieldNum, wireType, runtime.ErrTruncated)
			}
			off += n
		}
	}
	return off, nil
}

// UnmarshalBinary implements encoding.BinaryUnmarshaler.
// Duplicate non-repeated fields return an error.
func (x *AllScalarsUpdate) UnmarshalBinary(data []byte) error {
	_, err := x.unmarshalFrom(data, false, runtime.DefaultRecursionLimit)
	return err
}

// UnmarshalBinaryLenient unmarshals like UnmarshalBinary but allows
// duplicate non-repeated fields, keeping the last value.
func (x *AllScalarsUpdate) UnmarshalBinaryLenient(data []byte) error {
	_, err := x.unmarshalFrom(data, true, runtime.DefaultRecursionLimit)
	return err
}

// ToMap converts AllScalarsUpdate to map[string]any for partial update APIs (e.g. GORM Updates).
// Only non-nil fields are included.
func (x *AllScalarsUpdate) ToMap() map[string]any {
	um := make(map[string]any)
	if x.FSint64 != nil {
		um["f_sint64"] = *x.FSint64
	}
	if x.FSfixed32 != nil {
		um["f_sfixed32"] = *x.FSfixed32
	}
	if x.FSfixed64 != nil {
		um["f_sfixed64"] = *x.FSfixed64
	}
	if x.FDouble != nil {
		um["f_double"] = *x.FDouble
	}
	if x.FFixed32 != nil {
		um["f_fixed32"] = *x.FFixed32
	}
	if x.FFixed64 != nil {
		um["f_fixed64"] = *x.FFixed64
	}
	if x.FUint32 != nil {
		um["f_uint32"] = *x.FUint32
	}
	if x.FUint64 != nil {
		um["f_uint64"] = *x.FUint64
	}
	if x.FFloat != nil {
		um["f_float"] = *x.FFloat
	}
	return um
}

// ApplyTo merges non-nil fields from AllScalarsUpdate into p.
// Condition fields are skipped.
func (x *AllScalarsUpdate) ApplyTo(p *AllScalars) {
	if x.FSint64 != nil {
		p.FSint64 = *x.FSint64
	}
	if x.FSfixed32 != nil {
		p.FSfixed32 = *x.FSfixed32
	}
	if x.FSfixed64 != nil {
		p.FSfixed64 = *x.FSfixed64
	}
	if x.FDouble != nil {
		p.FDouble = *x.FDouble
	}
	if x.FFixed32 != nil {
		p.FFixed32 = *x.FFixed32
	}
	if x.FFixed64 != nil {
		p.FFixed64 = *x.FFixed64
	}
	if x.FUint32 != nil {
		p.FUint32 = *x.FUint32
	}
	if x.FUint64 != nil {
		p.FUint64 = *x.FUint64
	}
	if x.FFloat != nil {
		p.FFloat = *x.FFloat
	}
}
