// Code generated by gcode. DO NOT EDIT.
// source: all_types.proto

package dao

import (
	"fmt"
	"github.com/pinealctx/gcode/validateruntime"
)

func (a *AllScalars) Validate() error {
	return nil
}

func (a *AllRepeated) Validate() error {
	return nil
}

func (a *AllValidate) Validate() error {
	if a.UGte < 1 {
		return &validateruntime.ValidationError{Field: "u_gte", Rule: "gte", Message: validateruntime.MsgOr("", "must be >= 1")}
	}
	if a.ULte > 1000 {
		return &validateruntime.ValidationError{Field: "u_lte", Rule: "lte", Message: validateruntime.MsgOr("", "must be <= 1000")}
	}
	{
		found := false
		for _, v := range []uint32{1, 2, 3} {
			if a.UIn == v {
				found = true
				break
			}
		}
		if !found {
			return &validateruntime.ValidationError{Field: "u_in", Rule: "in", Message: validateruntime.MsgOr("", "must be one of [1, 2, 3]")}
		}
	}
	for _, v := range []uint32{0} {
		if a.UNotIn == v {
			return &validateruntime.ValidationError{Field: "u_not_in", Rule: "not_in", Message: validateruntime.MsgOr("", "must not be one of [0]")}
		}
	}
	if a.FGt <= 0 {
		return &validateruntime.ValidationError{Field: "f_gt", Rule: "gt", Message: validateruntime.MsgOr("", "must be > 0")}
	}
	if a.DLte > 1 {
		return &validateruntime.ValidationError{Field: "d_lte", Rule: "lte", Message: validateruntime.MsgOr("", "must be <= 1")}
	}
	if a.SIn != "" {
		{
			found := false
			for _, v := range []string{"a", "b", "c"} {
				if a.SIn == v {
					found = true
					break
				}
			}
			if !found {
				return &validateruntime.ValidationError{Field: "s_in", Rule: "in", Message: validateruntime.MsgOr("", "must be one of [a, b, c]")}
			}
		}
	}
	if a.SNotIn != "" {
		for _, v := range []string{"x", "y"} {
			if a.SNotIn == v {
				return &validateruntime.ValidationError{Field: "s_not_in", Rule: "not_in", Message: validateruntime.MsgOr("", "must not be one of [x, y]")}
			}
		}
	}
	{
		found := false
		for _, v := range []int32{1, 2, -1} {
			if a.IIn == v {
				found = true
				break
			}
		}
		if !found {
			return &validateruntime.ValidationError{Field: "i_in", Rule: "in", Message: validateruntime.MsgOr("", "must be one of [1, 2, -1]")}
		}
	}
	if a.SUri != "" {
		if !validateruntime.IsURI(a.SUri) {
			return &validateruntime.ValidationError{Field: "s_uri", Rule: "uri", Message: validateruntime.MsgOr("", "must be a valid URI")}
		}
	}
	if a.OStatus != nil {
	}
	if a.BMinmax != nil {
		if len(a.BMinmax) < 1 {
			return &validateruntime.ValidationError{Field: "b_minmax", Rule: "min_len", Message: validateruntime.MsgOr("", "length must be >= 1")}
		}
		if len(a.BMinmax) > 100 {
			return &validateruntime.ValidationError{Field: "b_minmax", Rule: "max_len", Message: validateruntime.MsgOr("", "length must be <= 100")}
		}
	}
	for i, v := range a.RItems {
		if v < 0 {
			return &validateruntime.ValidationError{Field: fmt.Sprintf("r_items[%d]", i), Rule: "gte", Message: validateruntime.MsgOr("", "must be >= 0")}
		}
	}
	return nil
}
