// Code generated by gcode. DO NOT EDIT.
// source: common.proto

package dao

import (
	"github.com/pinealctx/gcode/validateruntime"
)

func (x *Dimensions) Validate() error {
	if x.Width < 0 {
		return &validateruntime.ValidationError{Field: "width", Rule: "gte", Message: validateruntime.MsgOr("", "must be >= 0")}
	}
	if x.Height < 0 {
		return &validateruntime.ValidationError{Field: "height", Rule: "gte", Message: validateruntime.MsgOr("", "must be >= 0")}
	}
	return nil
}
