// Code generated by gcode. DO NOT EDIT.
// source: common.proto

package dao

import (
	"fmt"
	"github.com/pinealctx/gcode/runtime"
	"math"
)

// Dimensions holds physical size information shared across item types.
// Defined in a separate file to test cross-file message import in gen-proto.
type Dimensions struct {
	Width  float32 `json:"width"`
	Height float32 `json:"height"`
}

// Size returns the protobuf wire size of Dimensions.
func (x *Dimensions) Size() int {
	if x == nil {
		return 0
	}
	var n int
	if !runtime.IsZeroFloat(x.Width) {
		n += 1 + 4
	}
	if !runtime.IsZeroFloat(x.Height) {
		n += 1 + 4
	}
	return n
}

// MarshalBinary implements encoding.BinaryMarshaler.
func (x *Dimensions) MarshalBinary() ([]byte, error) {
	return x.MarshalAppend(make([]byte, 0, x.Size()))
}

// MarshalAppend appends the protobuf wire encoding of Dimensions to b.
func (x *Dimensions) MarshalAppend(b []byte) ([]byte, error) {
	if !runtime.IsZeroFloat(x.Width) {
		b = runtime.AppendTag(b, 1, runtime.WireFixed32)
		b = runtime.AppendFloat(b, x.Width)
	}
	if !runtime.IsZeroFloat(x.Height) {
		b = runtime.AppendTag(b, 2, runtime.WireFixed32)
		b = runtime.AppendFloat(b, x.Height)
	}
	return b, nil
}

// DeepClone returns a deep copy of Dimensions with no shared memory.
func (x *Dimensions) DeepClone() *Dimensions {
	if x == nil {
		return nil
	}
	clone := *x
	return &clone
}

// unmarshalFrom decodes a protobuf wire-format message from b.
// Returns the number of bytes consumed.
// If lenient is true, duplicate non-repeated fields use last-one-wins.
// depth is the remaining nesting budget; callers pass runtime.DefaultRecursionLimit.
func (x *Dimensions) unmarshalFrom(b []byte, lenient bool, depth int) (int, error) {
	if depth <= 0 {
		return 0, runtime.ErrNestingDepth
	}
	var seen [2]uint64
	off := 0
	for off < len(b) {
		fieldNum, wireType, n := runtime.ConsumeTag(b[off:])
		if n < 0 {
			if n == -2 {
				return 0, fmt.Errorf("field tag: %w", runtime.ErrOverflow)
			}
			return 0, fmt.Errorf("field tag: %w", runtime.ErrTruncated)
		}
		off += n

		switch fieldNum {
		case 1:
			if seen[0]&1 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 1: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 1
			if wireType != runtime.WireFixed32 {
				return 0, fmt.Errorf("field 1: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeFixed32(b[off:])
			if n < 0 {
				return 0, fmt.Errorf("field 1: %w", runtime.ErrTruncated)
			}
			x.Width = math.Float32frombits(v)
			off += n
		case 2:
			if seen[0]&2 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 2: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 2
			if wireType != runtime.WireFixed32 {
				return 0, fmt.Errorf("field 2: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeFixed32(b[off:])
			if n < 0 {
				return 0, fmt.Errorf("field 2: %w", runtime.ErrTruncated)
			}
			x.Height = math.Float32frombits(v)
			off += n
		default:
			n = runtime.SkipField(b[off:], wireType)
			if n < 0 {
				if n == -3 {
					return 0, fmt.Errorf("unknown field %d: %w", fieldNum, runtime.ErrUnknownWireType)
				}
				return 0, fmt.Errorf("unknown field %d (wire type %d): %w", fieldNum, wireType, runtime.ErrTruncated)
			}
			off += n
		}
	}
	return off, nil
}

// UnmarshalBinary implements encoding.BinaryUnmarshaler.
// Duplicate non-repeated fields return an error.
func (x *Dimensions) UnmarshalBinary(data []byte) error {
	_, err := x.unmarshalFrom(data, false, runtime.DefaultRecursionLimit)
	return err
}

// UnmarshalBinaryLenient unmarshals like UnmarshalBinary but allows
// duplicate non-repeated fields, keeping the last value.
func (x *Dimensions) UnmarshalBinaryLenient(data []byte) error {
	_, err := x.unmarshalFrom(data, true, runtime.DefaultRecursionLimit)
	return err
}

// ItemKind categorizes an item by its type.
// Defined in a separate file to test cross-file enum import in gen-proto.
type ItemKind int32

const (
	ItemKind_ITEM_KIND_UNSPECIFIED ItemKind = 0
	ItemKind_ITEM_KIND_PHYSICAL    ItemKind = 1
	ItemKind_ITEM_KIND_DIGITAL     ItemKind = 2
)
