// Code generated by gcode. DO NOT EDIT.
// source: item.create.proto

package dao

import (
	"github.com/pinealctx/gcode/validateruntime"
)

func (x *ItemCreate) Validate() error {
	if len(x.Name) < 1 {
		return &validateruntime.ValidationError{Field: "name", Rule: "min_len", Message: validateruntime.MsgOr("", "length must be >= 1")}
	}
	if len(x.Name) > 200 {
		return &validateruntime.ValidationError{Field: "name", Rule: "max_len", Message: validateruntime.MsgOr("", "length must be <= 200")}
	}
	switch x.Kind {
	case ItemKind_ITEM_KIND_UNSPECIFIED, ItemKind_ITEM_KIND_PHYSICAL, ItemKind_ITEM_KIND_DIGITAL:
	// ok
	default:
		return &validateruntime.ValidationError{Field: "kind", Rule: "defined_only", Message: validateruntime.MsgOr("", "must be a defined enum value")}
	}
	if x.Dimensions == nil {
		return &validateruntime.ValidationError{Field: "dimensions", Rule: "required", Message: validateruntime.MsgOr("", "is required")}
	}
	if err := x.Dimensions.Validate(); err != nil {
		return err
	}
	return nil
}
