// Code generated by gcode. DO NOT EDIT.
// source: item.create.proto

package dao

import (
	"fmt"
	"github.com/pinealctx/gcode/runtime"
)

type ItemCreate struct {
	Name       string      `json:"name" gorm:"column:name"`
	Kind       ItemKind    `json:"kind" gorm:"column:kind"`
	Dimensions *Dimensions `json:"dimensions" gorm:"column:dimensions"`
}

func (ItemCreate) TableName() string { return "items" }

// Size returns the protobuf wire size of ItemCreate.
func (x *ItemCreate) Size() int {
	if x == nil {
		return 0
	}
	var n int
	if len(x.Name) > 0 {
		n += 1 + runtime.SizeString(x.Name)
	}
	if x.Kind != 0 {
		n += 1 + runtime.SizeEnum(int32(x.Kind))
	}
	if x.Dimensions != nil {
		s := x.Dimensions.Size()
		n += 1 + runtime.SizeVarint(uint64(s)) + s
	}
	return n
}

// MarshalBinary implements encoding.BinaryMarshaler.
func (x *ItemCreate) MarshalBinary() ([]byte, error) {
	return x.MarshalAppend(make([]byte, 0, x.Size()))
}

// MarshalAppend appends the protobuf wire encoding of ItemCreate to b.
func (x *ItemCreate) MarshalAppend(b []byte) ([]byte, error) {
	if len(x.Name) > 0 {
		b = runtime.AppendTag(b, 1, runtime.WireBytes)
		b = runtime.AppendString(b, x.Name)
	}
	if x.Kind != 0 {
		b = runtime.AppendTag(b, 2, runtime.WireVarint)
		b = runtime.AppendVarint(b, uint64(x.Kind))
	}
	if x.Dimensions != nil {
		b = runtime.AppendTag(b, 3, runtime.WireBytes)
		b = runtime.AppendVarint(b, uint64(x.Dimensions.Size()))
		var err error
		b, err = x.Dimensions.MarshalAppend(b)
		if err != nil {
			return nil, err
		}
	}
	return b, nil
}

// DeepClone returns a deep copy of ItemCreate with no shared memory.
func (x *ItemCreate) DeepClone() *ItemCreate {
	if x == nil {
		return nil
	}
	clone := *x
	if x.Dimensions != nil {
		clone.Dimensions = x.Dimensions.DeepClone()
	}
	return &clone
}

// unmarshalFrom decodes a protobuf wire-format message from b.
// Returns the number of bytes consumed.
// If lenient is true, duplicate non-repeated fields use last-one-wins.
// depth is the remaining nesting budget; callers pass runtime.DefaultRecursionLimit.
func (x *ItemCreate) unmarshalFrom(b []byte, lenient bool, depth int) (int, error) {
	if depth <= 0 {
		return 0, runtime.ErrNestingDepth
	}
	var seen [2]uint64
	off := 0
	for off < len(b) {
		fieldNum, wireType, n := runtime.ConsumeTag(b[off:])
		if n < 0 {
			if n == -2 {
				return 0, fmt.Errorf("field tag: %w", runtime.ErrOverflow)
			}
			return 0, fmt.Errorf("field tag: %w", runtime.ErrTruncated)
		}
		off += n

		switch fieldNum {
		case 1:
			if seen[0]&1 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 1: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 1
			if wireType != runtime.WireBytes {
				return 0, fmt.Errorf("field 1: %w", runtime.ErrWireType)
			}
			payload, n := runtime.ConsumeBytes(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 1: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 1: %w", runtime.ErrTruncated)
			}
			x.Name = string(payload)
			off += n
		case 2:
			if seen[0]&2 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 2: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 2
			if wireType != runtime.WireVarint {
				return 0, fmt.Errorf("field 2: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeVarint(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 2: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 2: %w", runtime.ErrTruncated)
			}
			x.Kind = ItemKind(v)
			off += n
		case 3:
			if seen[0]&4 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 3: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 4
			if wireType != runtime.WireBytes {
				return 0, fmt.Errorf("field 3: %w", runtime.ErrWireType)
			}
			payload, n := runtime.ConsumeBytes(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 3: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 3: %w", runtime.ErrTruncated)
			}
			if x.Dimensions == nil {
				x.Dimensions = new(Dimensions)
			}
			if _, err := x.Dimensions.unmarshalFrom(payload, lenient, depth-1); err != nil {
				return 0, fmt.Errorf("field 3: %w", err)
			}
			off += n
		default:
			n = runtime.SkipField(b[off:], wireType)
			if n < 0 {
				if n == -3 {
					return 0, fmt.Errorf("unknown field %d: %w", fieldNum, runtime.ErrUnknownWireType)
				}
				return 0, fmt.Errorf("unknown field %d (wire type %d): %w", fieldNum, wireType, runtime.ErrTruncated)
			}
			off += n
		}
	}
	return off, nil
}

// UnmarshalBinary implements encoding.BinaryUnmarshaler.
// Duplicate non-repeated fields return an error.
func (x *ItemCreate) UnmarshalBinary(data []byte) error {
	_, err := x.unmarshalFrom(data, false, runtime.DefaultRecursionLimit)
	return err
}

// UnmarshalBinaryLenient unmarshals like UnmarshalBinary but allows
// duplicate non-repeated fields, keeping the last value.
func (x *ItemCreate) UnmarshalBinaryLenient(data []byte) error {
	_, err := x.unmarshalFrom(data, true, runtime.DefaultRecursionLimit)
	return err
}

// ToEntity converts ItemCreate to Item.
func (x *ItemCreate) ToEntity() *Item {
	var p Item
	p.Name = x.Name
	p.Kind = x.Kind
	if x.Dimensions != nil {
		p.Dimensions = x.Dimensions
	}
	return &p
}
