// Code generated by gcode. DO NOT EDIT.
// source: item.entity.proto

package dao

func (x *Item) Validate() error {
	if x.Dimensions != nil {
		if err := x.Dimensions.Validate(); err != nil {
			return err
		}
	}
	return nil
}
