// Code generated by gcode. DO NOT EDIT.
// source: person.entity.proto

package dao

import (
	"fmt"
	"github.com/pinealctx/gcode/runtime"
	"math"
)

type Address struct {
	Street string `json:"street"`
	City   string `json:"city"`
}

type Person struct {
	Name        string   `json:"name" gorm:"column:name"`
	Age         int32    `json:"age" gorm:"column:age"`
	Active      bool     `json:"active" gorm:"column:active"`
	Status      Status   `json:"status" gorm:"column:status"`
	Address     *Address `json:"address" gorm:"column:address"`
	Scores      []int32  `json:"scores" gorm:"column:scores"`
	Tags        []string `json:"tags" gorm:"column:tags"`
	Rating      float32  `json:"rating" gorm:"column:rating"`
	CreatedAt   int64    `json:"createdAt" gorm:"column:created_ts"`
	Avatar      []byte   `json:"avatar" gorm:"column:avatar"`
	Nickname    *string  `json:"nickname" gorm:"column:nickname"`
	Level       *int32   `json:"level" gorm:"column:level"`
	Verified    *bool    `json:"verified" gorm:"column:verified"`
	Score       *float32 `json:"score" gorm:"column:score"`
	UpdatedAt   *int64   `json:"updatedAt" gorm:"column:updated_at"`
	PrevStatus  *Status  `json:"prevStatus" gorm:"column:prev_status"`
	Fingerprint []byte   `json:"fingerprint" gorm:"column:fingerprint"`
	Email       string   `json:"email" gorm:"column:email"`
	Role        string   `json:"role" gorm:"column:role"`
	TypeId      int32    `json:"typeId" gorm:"column:type_id"`
}

func (Person) TableName() string { return "persons" }

// Size returns the protobuf wire size of Address.
func (x *Address) Size() int {
	if x == nil {
		return 0
	}
	var n int
	if len(x.Street) > 0 {
		n += 1 + runtime.SizeString(x.Street)
	}
	if len(x.City) > 0 {
		n += 1 + runtime.SizeString(x.City)
	}
	return n
}

// MarshalBinary implements encoding.BinaryMarshaler.
func (x *Address) MarshalBinary() ([]byte, error) {
	return x.MarshalAppend(make([]byte, 0, x.Size()))
}

// MarshalAppend appends the protobuf wire encoding of Address to b.
func (x *Address) MarshalAppend(b []byte) ([]byte, error) {
	if len(x.Street) > 0 {
		b = runtime.AppendTag(b, 1, runtime.WireBytes)
		b = runtime.AppendString(b, x.Street)
	}
	if len(x.City) > 0 {
		b = runtime.AppendTag(b, 2, runtime.WireBytes)
		b = runtime.AppendString(b, x.City)
	}
	return b, nil
}

// Size returns the protobuf wire size of Person.
func (x *Person) Size() int {
	if x == nil {
		return 0
	}
	var n int
	if len(x.Name) > 0 {
		n += 1 + runtime.SizeString(x.Name)
	}
	if x.Age != 0 {
		n += 1 + runtime.SizeInt32(x.Age)
	}
	if x.Active {
		n += 1 + 1
	}
	if x.Status != 0 {
		n += 1 + runtime.SizeEnum(int32(x.Status))
	}
	if x.Address != nil {
		s := x.Address.Size()
		n += 1 + runtime.SizeVarint(uint64(s)) + s
	}
	if len(x.Scores) > 0 {
		var es int
		for _, v := range x.Scores {
			es += runtime.SizeInt32(v)
		}
		n += 1 + runtime.SizeVarint(uint64(es)) + es
	}
	if len(x.Tags) > 0 {
		for _, v := range x.Tags {
			n += 1 + runtime.SizeString(v)
		}
	}
	if !runtime.IsZeroFloat(x.Rating) {
		n += 1 + 4
	}
	if x.CreatedAt != 0 {
		n += 1 + runtime.SizeInt64(x.CreatedAt)
	}
	if len(x.Avatar) > 0 {
		n += 1 + runtime.SizeBytes(x.Avatar)
	}
	if x.Nickname != nil {
		n += 1 + runtime.SizeString(*x.Nickname)
	}
	if x.Level != nil {
		n += 1 + runtime.SizeInt32(*x.Level)
	}
	if x.Verified != nil {
		n += 1 + 1
	}
	if x.Score != nil {
		n += 1 + 4
	}
	if x.UpdatedAt != nil {
		n += 1 + runtime.SizeInt64(*x.UpdatedAt)
	}
	if x.PrevStatus != nil {
		n += 2 + runtime.SizeEnum(int32(*x.PrevStatus))
	}
	if x.Fingerprint != nil {
		n += 2 + runtime.SizeBytes(x.Fingerprint)
	}
	if len(x.Email) > 0 {
		n += 2 + runtime.SizeString(x.Email)
	}
	if len(x.Role) > 0 {
		n += 2 + runtime.SizeString(x.Role)
	}
	if x.TypeId != 0 {
		n += 2 + runtime.SizeInt32(x.TypeId)
	}
	return n
}

// MarshalBinary implements encoding.BinaryMarshaler.
func (x *Person) MarshalBinary() ([]byte, error) {
	return x.MarshalAppend(make([]byte, 0, x.Size()))
}

// MarshalAppend appends the protobuf wire encoding of Person to b.
func (x *Person) MarshalAppend(b []byte) ([]byte, error) {
	if len(x.Name) > 0 {
		b = runtime.AppendTag(b, 1, runtime.WireBytes)
		b = runtime.AppendString(b, x.Name)
	}
	if x.Age != 0 {
		b = runtime.AppendTag(b, 2, runtime.WireVarint)
		b = runtime.AppendVarint(b, uint64(x.Age))
	}
	if x.Active {
		b = runtime.AppendTag(b, 3, runtime.WireVarint)
		b = runtime.AppendBool(b, x.Active)
	}
	if x.Status != 0 {
		b = runtime.AppendTag(b, 4, runtime.WireVarint)
		b = runtime.AppendVarint(b, uint64(x.Status))
	}
	if x.Address != nil {
		b = runtime.AppendTag(b, 5, runtime.WireBytes)
		b = runtime.AppendVarint(b, uint64(x.Address.Size()))
		var err error
		b, err = x.Address.MarshalAppend(b)
		if err != nil {
			return nil, err
		}
	}
	if len(x.Scores) > 0 {
		b = runtime.AppendTag(b, 6, runtime.WireBytes)
		var es int
		for _, v := range x.Scores {
			es += runtime.SizeInt32(v)
		}
		b = runtime.AppendVarint(b, uint64(es))
		for _, v := range x.Scores {
			b = runtime.AppendVarint(b, uint64(v))
		}
	}
	if len(x.Tags) > 0 {
		for _, v := range x.Tags {
			b = runtime.AppendTag(b, 7, runtime.WireBytes)
			b = runtime.AppendString(b, v)
		}
	}
	if !runtime.IsZeroFloat(x.Rating) {
		b = runtime.AppendTag(b, 8, runtime.WireFixed32)
		b = runtime.AppendFloat(b, x.Rating)
	}
	if x.CreatedAt != 0 {
		b = runtime.AppendTag(b, 9, runtime.WireVarint)
		b = runtime.AppendVarint(b, uint64(x.CreatedAt))
	}
	if len(x.Avatar) > 0 {
		b = runtime.AppendTag(b, 10, runtime.WireBytes)
		b = runtime.AppendBytes(b, x.Avatar)
	}
	if x.Nickname != nil {
		b = runtime.AppendTag(b, 11, runtime.WireBytes)
		b = runtime.AppendString(b, *x.Nickname)
	}
	if x.Level != nil {
		b = runtime.AppendTag(b, 12, runtime.WireVarint)
		b = runtime.AppendVarint(b, uint64(*x.Level))
	}
	if x.Verified != nil {
		b = runtime.AppendTag(b, 13, runtime.WireVarint)
		b = runtime.AppendBool(b, *x.Verified)
	}
	if x.Score != nil {
		b = runtime.AppendTag(b, 14, runtime.WireFixed32)
		b = runtime.AppendFloat(b, *x.Score)
	}
	if x.UpdatedAt != nil {
		b = runtime.AppendTag(b, 15, runtime.WireVarint)
		b = runtime.AppendVarint(b, uint64(*x.UpdatedAt))
	}
	if x.PrevStatus != nil {
		b = runtime.AppendTag(b, 16, runtime.WireVarint)
		b = runtime.AppendVarint(b, uint64(*x.PrevStatus))
	}
	if x.Fingerprint != nil {
		b = runtime.AppendTag(b, 17, runtime.WireBytes)
		b = runtime.AppendBytes(b, x.Fingerprint)
	}
	if len(x.Email) > 0 {
		b = runtime.AppendTag(b, 18, runtime.WireBytes)
		b = runtime.AppendString(b, x.Email)
	}
	if len(x.Role) > 0 {
		b = runtime.AppendTag(b, 19, runtime.WireBytes)
		b = runtime.AppendString(b, x.Role)
	}
	if x.TypeId != 0 {
		b = runtime.AppendTag(b, 20, runtime.WireVarint)
		b = runtime.AppendVarint(b, uint64(x.TypeId))
	}
	return b, nil
}

// DeepClone returns a deep copy of Address with no shared memory.
func (x *Address) DeepClone() *Address {
	if x == nil {
		return nil
	}
	clone := *x
	return &clone
}

// DeepClone returns a deep copy of Person with no shared memory.
func (x *Person) DeepClone() *Person {
	if x == nil {
		return nil
	}
	clone := *x
	if x.Address != nil {
		clone.Address = x.Address.DeepClone()
	}
	if x.Scores != nil {
		clone.Scores = make([]int32, len(x.Scores))
		copy(clone.Scores, x.Scores)
	}
	if x.Tags != nil {
		clone.Tags = make([]string, len(x.Tags))
		copy(clone.Tags, x.Tags)
	}
	if x.Avatar != nil {
		clone.Avatar = make([]byte, len(x.Avatar))
		copy(clone.Avatar, x.Avatar)
	}
	if x.Nickname != nil {
		v := *x.Nickname
		clone.Nickname = &v
	}
	if x.Level != nil {
		v := *x.Level
		clone.Level = &v
	}
	if x.Verified != nil {
		v := *x.Verified
		clone.Verified = &v
	}
	if x.Score != nil {
		v := *x.Score
		clone.Score = &v
	}
	if x.UpdatedAt != nil {
		v := *x.UpdatedAt
		clone.UpdatedAt = &v
	}
	if x.PrevStatus != nil {
		v := *x.PrevStatus
		clone.PrevStatus = &v
	}
	if x.Fingerprint != nil {
		clone.Fingerprint = make([]byte, len(x.Fingerprint))
		copy(clone.Fingerprint, x.Fingerprint)
	}
	return &clone
}

// unmarshalFrom decodes a protobuf wire-format message from b.
// Returns the number of bytes consumed.
// If lenient is true, duplicate non-repeated fields use last-one-wins.
// depth is the remaining nesting budget; callers pass runtime.DefaultRecursionLimit.
func (x *Address) unmarshalFrom(b []byte, lenient bool, depth int) (int, error) {
	if depth <= 0 {
		return 0, runtime.ErrNestingDepth
	}
	var seen [2]uint64
	off := 0
	for off < len(b) {
		fieldNum, wireType, n := runtime.ConsumeTag(b[off:])
		if n < 0 {
			if n == -2 {
				return 0, fmt.Errorf("field tag: %w", runtime.ErrOverflow)
			}
			return 0, fmt.Errorf("field tag: %w", runtime.ErrTruncated)
		}
		off += n

		switch fieldNum {
		case 1:
			if seen[0]&1 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 1: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 1
			if wireType != runtime.WireBytes {
				return 0, fmt.Errorf("field 1: %w", runtime.ErrWireType)
			}
			payload, n := runtime.ConsumeBytes(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 1: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 1: %w", runtime.ErrTruncated)
			}
			x.Street = string(payload)
			off += n
		case 2:
			if seen[0]&2 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 2: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 2
			if wireType != runtime.WireBytes {
				return 0, fmt.Errorf("field 2: %w", runtime.ErrWireType)
			}
			payload, n := runtime.ConsumeBytes(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 2: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 2: %w", runtime.ErrTruncated)
			}
			x.City = string(payload)
			off += n
		default:
			n = runtime.SkipField(b[off:], wireType)
			if n < 0 {
				if n == -3 {
					return 0, fmt.Errorf("unknown field %d: %w", fieldNum, runtime.ErrUnknownWireType)
				}
				return 0, fmt.Errorf("unknown field %d (wire type %d): %w", fieldNum, wireType, runtime.ErrTruncated)
			}
			off += n
		}
	}
	return off, nil
}

// UnmarshalBinary implements encoding.BinaryUnmarshaler.
// Duplicate non-repeated fields return an error.
func (x *Address) UnmarshalBinary(data []byte) error {
	_, err := x.unmarshalFrom(data, false, runtime.DefaultRecursionLimit)
	return err
}

// UnmarshalBinaryLenient unmarshals like UnmarshalBinary but allows
// duplicate non-repeated fields, keeping the last value.
func (x *Address) UnmarshalBinaryLenient(data []byte) error {
	_, err := x.unmarshalFrom(data, true, runtime.DefaultRecursionLimit)
	return err
}

// unmarshalFrom decodes a protobuf wire-format message from b.
// Returns the number of bytes consumed.
// If lenient is true, duplicate non-repeated fields use last-one-wins.
// depth is the remaining nesting budget; callers pass runtime.DefaultRecursionLimit.
func (x *Person) unmarshalFrom(b []byte, lenient bool, depth int) (int, error) {
	if depth <= 0 {
		return 0, runtime.ErrNestingDepth
	}
	var seen [2]uint64
	off := 0
	for off < len(b) {
		fieldNum, wireType, n := runtime.ConsumeTag(b[off:])
		if n < 0 {
			if n == -2 {
				return 0, fmt.Errorf("field tag: %w", runtime.ErrOverflow)
			}
			return 0, fmt.Errorf("field tag: %w", runtime.ErrTruncated)
		}
		off += n

		switch fieldNum {
		case 1:
			if seen[0]&1 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 1: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 1
			if wireType != runtime.WireBytes {
				return 0, fmt.Errorf("field 1: %w", runtime.ErrWireType)
			}
			payload, n := runtime.ConsumeBytes(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 1: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 1: %w", runtime.ErrTruncated)
			}
			x.Name = string(payload)
			off += n
		case 2:
			if seen[0]&2 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 2: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 2
			if wireType != runtime.WireVarint {
				return 0, fmt.Errorf("field 2: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeVarint(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 2: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 2: %w", runtime.ErrTruncated)
			}
			x.Age = int32(v)
			off += n
		case 3:
			if seen[0]&4 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 3: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 4
			if wireType != runtime.WireVarint {
				return 0, fmt.Errorf("field 3: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeVarint(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 3: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 3: %w", runtime.ErrTruncated)
			}
			x.Active = v != 0
			off += n
		case 4:
			if seen[0]&8 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 4: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 8
			if wireType != runtime.WireVarint {
				return 0, fmt.Errorf("field 4: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeVarint(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 4: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 4: %w", runtime.ErrTruncated)
			}
			x.Status = Status(v)
			off += n
		case 5:
			if seen[0]&16 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 5: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 16
			if wireType != runtime.WireBytes {
				return 0, fmt.Errorf("field 5: %w", runtime.ErrWireType)
			}
			payload, n := runtime.ConsumeBytes(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 5: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 5: %w", runtime.ErrTruncated)
			}
			if x.Address == nil {
				x.Address = new(Address)
			}
			if _, err := x.Address.unmarshalFrom(payload, lenient, depth-1); err != nil {
				return 0, fmt.Errorf("field 5: %w", err)
			}
			off += n
		case 6:
			if wireType != runtime.WireBytes {
				return 0, fmt.Errorf("field 6: %w", runtime.ErrWireType)
			}
			packed, n := runtime.ConsumeBytes(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 6: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 6: %w", runtime.ErrTruncated)
			}
			off += n
			for pi := 0; pi < len(packed); {
				v, pn := runtime.ConsumeVarint(packed[pi:])
				if pn < 0 {
					if pn == -2 {
						return 0, fmt.Errorf("field 6: %w", runtime.ErrOverflow)
					}
					return 0, fmt.Errorf("field 6: %w", runtime.ErrTruncated)
				}
				x.Scores = append(x.Scores, int32(v))
				pi += pn
			}
		case 7:
			if wireType != runtime.WireBytes {
				return 0, fmt.Errorf("field 7: %w", runtime.ErrWireType)
			}
			payload, n := runtime.ConsumeBytes(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 7: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 7: %w", runtime.ErrTruncated)
			}
			x.Tags = append(x.Tags, string(payload))
			off += n
		case 8:
			if seen[0]&32 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 8: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 32
			if wireType != runtime.WireFixed32 {
				return 0, fmt.Errorf("field 8: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeFixed32(b[off:])
			if n < 0 {
				return 0, fmt.Errorf("field 8: %w", runtime.ErrTruncated)
			}
			x.Rating = math.Float32frombits(v)
			off += n
		case 9:
			if seen[0]&64 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 9: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 64
			if wireType != runtime.WireVarint {
				return 0, fmt.Errorf("field 9: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeVarint(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 9: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 9: %w", runtime.ErrTruncated)
			}
			x.CreatedAt = int64(v)
			off += n
		case 10:
			if seen[0]&128 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 10: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 128
			if wireType != runtime.WireBytes {
				return 0, fmt.Errorf("field 10: %w", runtime.ErrWireType)
			}
			payload, n := runtime.ConsumeBytes(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 10: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 10: %w", runtime.ErrTruncated)
			}
			tmp := make([]byte, len(payload))
			copy(tmp, payload)
			x.Avatar = tmp
			off += n
		case 11:
			if seen[0]&256 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 11: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 256
			if wireType != runtime.WireBytes {
				return 0, fmt.Errorf("field 11: %w", runtime.ErrWireType)
			}
			payload, n := runtime.ConsumeBytes(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 11: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 11: %w", runtime.ErrTruncated)
			}
			tmp := string(payload)
			x.Nickname = &tmp
			off += n
		case 12:
			if seen[0]&512 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 12: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 512
			if wireType != runtime.WireVarint {
				return 0, fmt.Errorf("field 12: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeVarint(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 12: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 12: %w", runtime.ErrTruncated)
			}
			tmp := int32(v)
			x.Level = &tmp
			off += n
		case 13:
			if seen[0]&1024 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 13: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 1024
			if wireType != runtime.WireVarint {
				return 0, fmt.Errorf("field 13: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeVarint(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 13: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 13: %w", runtime.ErrTruncated)
			}
			tmp := v != 0
			x.Verified = &tmp
			off += n
		case 14:
			if seen[0]&2048 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 14: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 2048
			if wireType != runtime.WireFixed32 {
				return 0, fmt.Errorf("field 14: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeFixed32(b[off:])
			if n < 0 {
				return 0, fmt.Errorf("field 14: %w", runtime.ErrTruncated)
			}
			tmp := math.Float32frombits(v)
			x.Score = &tmp
			off += n
		case 15:
			if seen[0]&4096 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 15: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 4096
			if wireType != runtime.WireVarint {
				return 0, fmt.Errorf("field 15: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeVarint(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 15: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 15: %w", runtime.ErrTruncated)
			}
			tmp := int64(v)
			x.UpdatedAt = &tmp
			off += n
		case 16:
			if seen[0]&8192 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 16: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 8192
			if wireType != runtime.WireVarint {
				return 0, fmt.Errorf("field 16: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeVarint(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 16: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 16: %w", runtime.ErrTruncated)
			}
			tmp := Status(v)
			x.PrevStatus = &tmp
			off += n
		case 17:
			if seen[0]&16384 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 17: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 16384
			if wireType != runtime.WireBytes {
				return 0, fmt.Errorf("field 17: %w", runtime.ErrWireType)
			}
			payload, n := runtime.ConsumeBytes(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 17: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 17: %w", runtime.ErrTruncated)
			}
			tmp := make([]byte, len(payload))
			copy(tmp, payload)
			x.Fingerprint = tmp
			off += n
		case 18:
			if seen[0]&32768 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 18: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 32768
			if wireType != runtime.WireBytes {
				return 0, fmt.Errorf("field 18: %w", runtime.ErrWireType)
			}
			payload, n := runtime.ConsumeBytes(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 18: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 18: %w", runtime.ErrTruncated)
			}
			x.Email = string(payload)
			off += n
		case 19:
			if seen[0]&65536 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 19: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 65536
			if wireType != runtime.WireBytes {
				return 0, fmt.Errorf("field 19: %w", runtime.ErrWireType)
			}
			payload, n := runtime.ConsumeBytes(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 19: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 19: %w", runtime.ErrTruncated)
			}
			x.Role = string(payload)
			off += n
		case 20:
			if seen[0]&131072 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 20: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 131072
			if wireType != runtime.WireVarint {
				return 0, fmt.Errorf("field 20: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeVarint(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 20: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 20: %w", runtime.ErrTruncated)
			}
			x.TypeId = int32(v)
			off += n
		default:
			n = runtime.SkipField(b[off:], wireType)
			if n < 0 {
				if n == -3 {
					return 0, fmt.Errorf("unknown field %d: %w", fieldNum, runtime.ErrUnknownWireType)
				}
				return 0, fmt.Errorf("unknown field %d (wire type %d): %w", fieldNum, wireType, runtime.ErrTruncated)
			}
			off += n
		}
	}
	return off, nil
}

// UnmarshalBinary implements encoding.BinaryUnmarshaler.
// Duplicate non-repeated fields return an error.
func (x *Person) UnmarshalBinary(data []byte) error {
	_, err := x.unmarshalFrom(data, false, runtime.DefaultRecursionLimit)
	return err
}

// UnmarshalBinaryLenient unmarshals like UnmarshalBinary but allows
// duplicate non-repeated fields, keeping the last value.
func (x *Person) UnmarshalBinaryLenient(data []byte) error {
	_, err := x.unmarshalFrom(data, true, runtime.DefaultRecursionLimit)
	return err
}

type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_STATUS_ACTIVE      Status = 1
	Status_STATUS_INACTIVE    Status = 2
)
