// Code generated by gcode. DO NOT EDIT.
// source: person.create.proto

package dao

import (
	"github.com/pinealctx/gcode/validateruntime"
)

func (x *PersonCreate) Validate() error {
	if x.Name != nil {
		if *x.Name != "" {
			if len(*x.Name) < 1 {
				return &validateruntime.ValidationError{Field: "name", Rule: "min_len", Message: validateruntime.MsgOr("", "length must be >= 1")}
			}
			if len(*x.Name) > 100 {
				return &validateruntime.ValidationError{Field: "name", Rule: "max_len", Message: validateruntime.MsgOr("", "length must be <= 100")}
			}
		}
	}
	if x.Age != nil {
		if *x.Age < 0 {
			return &validateruntime.ValidationError{Field: "age", Rule: "gte", Message: validateruntime.MsgOr("", "must be >= 0")}
		}
		if *x.Age > 150 {
			return &validateruntime.ValidationError{Field: "age", Rule: "lte", Message: validateruntime.MsgOr("", "must be <= 150")}
		}
	}
	if x.Status != nil {
		switch *x.Status {
		case Status_STATUS_UNSPECIFIED, Status_STATUS_ACTIVE, Status_STATUS_INACTIVE:
		// ok
		default:
			return &validateruntime.ValidationError{Field: "status", Rule: "defined_only", Message: validateruntime.MsgOr("", "must be a defined enum value")}
		}
	}
	if len(x.Nickname) < 1 {
		return &validateruntime.ValidationError{Field: "nickname", Rule: "min_len", Message: validateruntime.MsgOr("", "length must be >= 1")}
	}
	if len(x.Nickname) > 10 {
		return &validateruntime.ValidationError{Field: "nickname", Rule: "max_len", Message: validateruntime.MsgOr("", "length must be <= 10")}
	}
	if x.Email != nil {
		if *x.Email != "" {
			if !validateruntime.IsEmail(*x.Email) {
				return &validateruntime.ValidationError{Field: "email", Rule: "email", Message: validateruntime.MsgOr("invalid email address", "must be a valid email address")}
			}
		}
	}
	if x.Role != nil {
		if *x.Role != "" {
			{
				found := false
				for _, v := range []string{"admin", "user", "guest"} {
					if *x.Role == v {
						found = true
						break
					}
				}
				if !found {
					return &validateruntime.ValidationError{Field: "role", Rule: "in", Message: validateruntime.MsgOr("", "must be one of [admin, user, guest]")}
				}
			}
		}
	}
	if x.TypeId != nil {
		for _, v := range []int32{0, -1} {
			if *x.TypeId == v {
				return &validateruntime.ValidationError{Field: "type_id", Rule: "not_in", Message: validateruntime.MsgOr("", "must not be one of [0, -1]")}
			}
		}
	}
	return nil
}
