// Code generated by gcode. DO NOT EDIT.
// source: person_service.proto

package dao

import (
	"github.com/gin-gonic/gin"
	"github.com/pinealctx/x/handlerx"

	"github.com/pinealctx/gcode/httpruntime"
)

// CreatePerson creates a new person record.
func CreatePersonHandler(svc PersonService, interceptors ...handlerx.Interceptor[*PersonCreate, *CreatePersonResponse]) gin.HandlerFunc {
	return httpruntime.NewHandler(svc.CreatePerson, interceptors...)
}

func GetPersonHandler(svc PersonService, interceptors ...handlerx.Interceptor[*GetPersonRequest, *GetPersonResponse]) gin.HandlerFunc {
	return httpruntime.NewHandler(svc.GetPerson, interceptors...)
}

// UpdatePerson updates an existing person record by name.
func UpdatePersonHandler(svc PersonService, interceptors ...handlerx.Interceptor[*PersonUpdateByName, *UpdatePersonResponse]) gin.HandlerFunc {
	return httpruntime.NewHandler(svc.UpdatePerson, interceptors...)
}

func DeletePersonHandler(svc PersonService, interceptors ...handlerx.Interceptor[*DeletePersonRequest, *DeletePersonResponse]) gin.HandlerFunc {
	return httpruntime.NewHandler(svc.DeletePerson, interceptors...)
}
