// Code generated by gcode. DO NOT EDIT.
// source: person.proto

package dao

import (
	"fmt"
	"github.com/pinealctx/gcode/runtime"
	"math"
)

type Address struct {
	Street string `json:"street"`
	City   string `json:"city"`
}

type Person struct {
	Name        string   `json:"name" gorm:"column:name"`
	Age         int32    `json:"age" gorm:"column:age"`
	Active      bool     `json:"active" gorm:"column:active"`
	Status      Status   `json:"status" gorm:"column:status"`
	Address     *Address `json:"address" gorm:"column:address"`
	Scores      []int32  `json:"scores" gorm:"column:scores"`
	Tags        []string `json:"tags" gorm:"column:tags"`
	Rating      float32  `json:"rating" gorm:"column:rating"`
	CreatedAt   int64    `json:"createdAt" gorm:"column:created_ts"`
	Avatar      []byte   `json:"avatar" gorm:"column:avatar"`
	Nickname    *string  `json:"nickname" gorm:"column:nickname"`
	Level       *int32   `json:"level" gorm:"column:level"`
	Verified    *bool    `json:"verified" gorm:"column:verified"`
	Score       *float32 `json:"score" gorm:"column:score"`
	UpdatedAt   *int64   `json:"updatedAt" gorm:"column:updated_at"`
	PrevStatus  *Status  `json:"prevStatus" gorm:"column:prev_status"`
	Fingerprint []byte   `json:"fingerprint" gorm:"column:fingerprint"`
	Email       string   `json:"email" gorm:"column:email"`
	Role        string   `json:"role" gorm:"column:role"`
	TypeId      int32    `json:"typeId" gorm:"column:type_id"`
}

func (Person) TableName() string { return "persons" }

// Size returns the protobuf wire size of Address.
func (a *Address) Size() int {
	if a == nil {
		return 0
	}
	var n int
	if len(a.Street) > 0 {
		n += 1 + runtime.SizeString(a.Street)
	}
	if len(a.City) > 0 {
		n += 1 + runtime.SizeString(a.City)
	}
	return n
}

// MarshalBinary implements encoding.BinaryMarshaler.
func (a *Address) MarshalBinary() ([]byte, error) {
	return a.MarshalAppend(make([]byte, 0, a.Size()))
}

// MarshalAppend appends the protobuf wire encoding of Address to b.
func (a *Address) MarshalAppend(b []byte) ([]byte, error) {
	if len(a.Street) > 0 {
		b = runtime.AppendTag(b, 1, runtime.WireBytes)
		b = runtime.AppendString(b, a.Street)
	}
	if len(a.City) > 0 {
		b = runtime.AppendTag(b, 2, runtime.WireBytes)
		b = runtime.AppendString(b, a.City)
	}
	return b, nil
}

// Size returns the protobuf wire size of Person.
func (p *Person) Size() int {
	if p == nil {
		return 0
	}
	var n int
	if len(p.Name) > 0 {
		n += 1 + runtime.SizeString(p.Name)
	}
	if p.Age != 0 {
		n += 1 + runtime.SizeInt32(p.Age)
	}
	if p.Active {
		n += 1 + 1
	}
	if p.Status != 0 {
		n += 1 + runtime.SizeEnum(int32(p.Status))
	}
	if p.Address != nil {
		s := p.Address.Size()
		n += 1 + runtime.SizeVarint(uint64(s)) + s
	}
	if len(p.Scores) > 0 {
		var es int
		for _, v := range p.Scores {
			es += runtime.SizeInt32(v)
		}
		n += 1 + runtime.SizeVarint(uint64(es)) + es
	}
	if len(p.Tags) > 0 {
		for _, v := range p.Tags {
			n += 1 + runtime.SizeString(v)
		}
	}
	if !runtime.IsZeroFloat(p.Rating) {
		n += 1 + 4
	}
	if p.CreatedAt != 0 {
		n += 1 + runtime.SizeInt64(p.CreatedAt)
	}
	if len(p.Avatar) > 0 {
		n += 1 + runtime.SizeBytes(p.Avatar)
	}
	if p.Nickname != nil {
		n += 1 + runtime.SizeString(*p.Nickname)
	}
	if p.Level != nil {
		n += 1 + runtime.SizeInt32(*p.Level)
	}
	if p.Verified != nil {
		n += 1 + 1
	}
	if p.Score != nil {
		n += 1 + 4
	}
	if p.UpdatedAt != nil {
		n += 1 + runtime.SizeInt64(*p.UpdatedAt)
	}
	if p.PrevStatus != nil {
		n += 2 + runtime.SizeEnum(int32(*p.PrevStatus))
	}
	if p.Fingerprint != nil {
		n += 2 + runtime.SizeBytes(p.Fingerprint)
	}
	if len(p.Email) > 0 {
		n += 2 + runtime.SizeString(p.Email)
	}
	if len(p.Role) > 0 {
		n += 2 + runtime.SizeString(p.Role)
	}
	if p.TypeId != 0 {
		n += 2 + runtime.SizeInt32(p.TypeId)
	}
	return n
}

// MarshalBinary implements encoding.BinaryMarshaler.
func (p *Person) MarshalBinary() ([]byte, error) {
	return p.MarshalAppend(make([]byte, 0, p.Size()))
}

// MarshalAppend appends the protobuf wire encoding of Person to b.
func (p *Person) MarshalAppend(b []byte) ([]byte, error) {
	if len(p.Name) > 0 {
		b = runtime.AppendTag(b, 1, runtime.WireBytes)
		b = runtime.AppendString(b, p.Name)
	}
	if p.Age != 0 {
		b = runtime.AppendTag(b, 2, runtime.WireVarint)
		b = runtime.AppendVarint(b, uint64(p.Age))
	}
	if p.Active {
		b = runtime.AppendTag(b, 3, runtime.WireVarint)
		b = runtime.AppendBool(b, p.Active)
	}
	if p.Status != 0 {
		b = runtime.AppendTag(b, 4, runtime.WireVarint)
		b = runtime.AppendVarint(b, uint64(p.Status))
	}
	if p.Address != nil {
		b = runtime.AppendTag(b, 5, runtime.WireBytes)
		b = runtime.AppendVarint(b, uint64(p.Address.Size()))
		var err error
		b, err = p.Address.MarshalAppend(b)
		if err != nil {
			return nil, err
		}
	}
	if len(p.Scores) > 0 {
		b = runtime.AppendTag(b, 6, runtime.WireBytes)
		var es int
		for _, v := range p.Scores {
			es += runtime.SizeInt32(v)
		}
		b = runtime.AppendVarint(b, uint64(es))
		for _, v := range p.Scores {
			b = runtime.AppendVarint(b, uint64(v))
		}
	}
	if len(p.Tags) > 0 {
		for _, v := range p.Tags {
			b = runtime.AppendTag(b, 7, runtime.WireBytes)
			b = runtime.AppendString(b, v)
		}
	}
	if !runtime.IsZeroFloat(p.Rating) {
		b = runtime.AppendTag(b, 8, runtime.WireFixed32)
		b = runtime.AppendFloat(b, p.Rating)
	}
	if p.CreatedAt != 0 {
		b = runtime.AppendTag(b, 9, runtime.WireVarint)
		b = runtime.AppendVarint(b, uint64(p.CreatedAt))
	}
	if len(p.Avatar) > 0 {
		b = runtime.AppendTag(b, 10, runtime.WireBytes)
		b = runtime.AppendBytes(b, p.Avatar)
	}
	if p.Nickname != nil {
		b = runtime.AppendTag(b, 11, runtime.WireBytes)
		b = runtime.AppendString(b, *p.Nickname)
	}
	if p.Level != nil {
		b = runtime.AppendTag(b, 12, runtime.WireVarint)
		b = runtime.AppendVarint(b, uint64(*p.Level))
	}
	if p.Verified != nil {
		b = runtime.AppendTag(b, 13, runtime.WireVarint)
		b = runtime.AppendBool(b, *p.Verified)
	}
	if p.Score != nil {
		b = runtime.AppendTag(b, 14, runtime.WireFixed32)
		b = runtime.AppendFloat(b, *p.Score)
	}
	if p.UpdatedAt != nil {
		b = runtime.AppendTag(b, 15, runtime.WireVarint)
		b = runtime.AppendVarint(b, uint64(*p.UpdatedAt))
	}
	if p.PrevStatus != nil {
		b = runtime.AppendTag(b, 16, runtime.WireVarint)
		b = runtime.AppendVarint(b, uint64(*p.PrevStatus))
	}
	if p.Fingerprint != nil {
		b = runtime.AppendTag(b, 17, runtime.WireBytes)
		b = runtime.AppendBytes(b, p.Fingerprint)
	}
	if len(p.Email) > 0 {
		b = runtime.AppendTag(b, 18, runtime.WireBytes)
		b = runtime.AppendString(b, p.Email)
	}
	if len(p.Role) > 0 {
		b = runtime.AppendTag(b, 19, runtime.WireBytes)
		b = runtime.AppendString(b, p.Role)
	}
	if p.TypeId != 0 {
		b = runtime.AppendTag(b, 20, runtime.WireVarint)
		b = runtime.AppendVarint(b, uint64(p.TypeId))
	}
	return b, nil
}

// unmarshalFrom decodes a protobuf wire-format message from b.
// Returns the number of bytes consumed.
// If lenient is true, duplicate non-repeated fields use last-one-wins.
// depth is the remaining nesting budget; callers pass runtime.DefaultRecursionLimit.
func (a *Address) unmarshalFrom(b []byte, lenient bool, depth int) (int, error) {
	if depth <= 0 {
		return 0, runtime.ErrNestingDepth
	}
	var seen [2]uint64
	off := 0
	for off < len(b) {
		fieldNum, wireType, n := runtime.ConsumeTag(b[off:])
		if n < 0 {
			if n == -2 {
				return 0, fmt.Errorf("field tag: %w", runtime.ErrOverflow)
			}
			return 0, fmt.Errorf("field tag: %w", runtime.ErrTruncated)
		}
		off += n

		switch fieldNum {
		case 1:
			if seen[0]&1 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 1: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 1
			if wireType != runtime.WireBytes {
				return 0, fmt.Errorf("field 1: %w", runtime.ErrWireType)
			}
			payload, n := runtime.ConsumeBytes(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 1: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 1: %w", runtime.ErrTruncated)
			}
			a.Street = string(payload)
			off += n
		case 2:
			if seen[0]&2 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 2: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 2
			if wireType != runtime.WireBytes {
				return 0, fmt.Errorf("field 2: %w", runtime.ErrWireType)
			}
			payload, n := runtime.ConsumeBytes(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 2: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 2: %w", runtime.ErrTruncated)
			}
			a.City = string(payload)
			off += n
		default:
			n = runtime.SkipField(b[off:], wireType)
			if n < 0 {
				if n == -3 {
					return 0, fmt.Errorf("unknown field %d: %w", fieldNum, runtime.ErrUnknownWireType)
				}
				return 0, fmt.Errorf("unknown field %d (wire type %d): %w", fieldNum, wireType, runtime.ErrTruncated)
			}
			off += n
		}
	}
	return off, nil
}

// UnmarshalBinary implements encoding.BinaryUnmarshaler.
// Duplicate non-repeated fields return an error.
func (a *Address) UnmarshalBinary(data []byte) error {
	_, err := a.unmarshalFrom(data, false, runtime.DefaultRecursionLimit)
	return err
}

// UnmarshalBinaryLenient unmarshals like UnmarshalBinary but allows
// duplicate non-repeated fields, keeping the last value.
func (a *Address) UnmarshalBinaryLenient(data []byte) error {
	_, err := a.unmarshalFrom(data, true, runtime.DefaultRecursionLimit)
	return err
}

// unmarshalFrom decodes a protobuf wire-format message from b.
// Returns the number of bytes consumed.
// If lenient is true, duplicate non-repeated fields use last-one-wins.
// depth is the remaining nesting budget; callers pass runtime.DefaultRecursionLimit.
func (p *Person) unmarshalFrom(b []byte, lenient bool, depth int) (int, error) {
	if depth <= 0 {
		return 0, runtime.ErrNestingDepth
	}
	var seen [2]uint64
	off := 0
	for off < len(b) {
		fieldNum, wireType, n := runtime.ConsumeTag(b[off:])
		if n < 0 {
			if n == -2 {
				return 0, fmt.Errorf("field tag: %w", runtime.ErrOverflow)
			}
			return 0, fmt.Errorf("field tag: %w", runtime.ErrTruncated)
		}
		off += n

		switch fieldNum {
		case 1:
			if seen[0]&1 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 1: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 1
			if wireType != runtime.WireBytes {
				return 0, fmt.Errorf("field 1: %w", runtime.ErrWireType)
			}
			payload, n := runtime.ConsumeBytes(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 1: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 1: %w", runtime.ErrTruncated)
			}
			p.Name = string(payload)
			off += n
		case 2:
			if seen[0]&2 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 2: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 2
			if wireType != runtime.WireVarint {
				return 0, fmt.Errorf("field 2: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeVarint(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 2: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 2: %w", runtime.ErrTruncated)
			}
			p.Age = int32(v)
			off += n
		case 3:
			if seen[0]&4 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 3: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 4
			if wireType != runtime.WireVarint {
				return 0, fmt.Errorf("field 3: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeVarint(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 3: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 3: %w", runtime.ErrTruncated)
			}
			p.Active = v != 0
			off += n
		case 4:
			if seen[0]&8 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 4: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 8
			if wireType != runtime.WireVarint {
				return 0, fmt.Errorf("field 4: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeVarint(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 4: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 4: %w", runtime.ErrTruncated)
			}
			p.Status = Status(v)
			off += n
		case 5:
			if seen[0]&16 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 5: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 16
			if wireType != runtime.WireBytes {
				return 0, fmt.Errorf("field 5: %w", runtime.ErrWireType)
			}
			payload, n := runtime.ConsumeBytes(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 5: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 5: %w", runtime.ErrTruncated)
			}
			if p.Address == nil {
				p.Address = new(Address)
			}
			if _, err := p.Address.unmarshalFrom(payload, lenient, depth-1); err != nil {
				return 0, fmt.Errorf("field 5: %w", err)
			}
			off += n
		case 6:
			if wireType != runtime.WireBytes {
				return 0, fmt.Errorf("field 6: %w", runtime.ErrWireType)
			}
			packed, n := runtime.ConsumeBytes(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 6: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 6: %w", runtime.ErrTruncated)
			}
			off += n
			for pi := 0; pi < len(packed); {
				v, pn := runtime.ConsumeVarint(packed[pi:])
				if pn < 0 {
					if pn == -2 {
						return 0, fmt.Errorf("field 6: %w", runtime.ErrOverflow)
					}
					return 0, fmt.Errorf("field 6: %w", runtime.ErrTruncated)
				}
				p.Scores = append(p.Scores, int32(v))
				pi += pn
			}
		case 7:
			if wireType != runtime.WireBytes {
				return 0, fmt.Errorf("field 7: %w", runtime.ErrWireType)
			}
			payload, n := runtime.ConsumeBytes(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 7: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 7: %w", runtime.ErrTruncated)
			}
			p.Tags = append(p.Tags, string(payload))
			off += n
		case 8:
			if seen[0]&32 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 8: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 32
			if wireType != runtime.WireFixed32 {
				return 0, fmt.Errorf("field 8: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeFixed32(b[off:])
			if n < 0 {
				return 0, fmt.Errorf("field 8: %w", runtime.ErrTruncated)
			}
			p.Rating = math.Float32frombits(v)
			off += n
		case 9:
			if seen[0]&64 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 9: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 64
			if wireType != runtime.WireVarint {
				return 0, fmt.Errorf("field 9: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeVarint(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 9: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 9: %w", runtime.ErrTruncated)
			}
			p.CreatedAt = int64(v)
			off += n
		case 10:
			if seen[0]&128 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 10: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 128
			if wireType != runtime.WireBytes {
				return 0, fmt.Errorf("field 10: %w", runtime.ErrWireType)
			}
			payload, n := runtime.ConsumeBytes(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 10: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 10: %w", runtime.ErrTruncated)
			}
			tmp := make([]byte, len(payload))
			copy(tmp, payload)
			p.Avatar = tmp
			off += n
		case 11:
			if seen[0]&256 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 11: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 256
			if wireType != runtime.WireBytes {
				return 0, fmt.Errorf("field 11: %w", runtime.ErrWireType)
			}
			payload, n := runtime.ConsumeBytes(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 11: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 11: %w", runtime.ErrTruncated)
			}
			tmp := string(payload)
			p.Nickname = &tmp
			off += n
		case 12:
			if seen[0]&512 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 12: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 512
			if wireType != runtime.WireVarint {
				return 0, fmt.Errorf("field 12: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeVarint(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 12: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 12: %w", runtime.ErrTruncated)
			}
			tmp := int32(v)
			p.Level = &tmp
			off += n
		case 13:
			if seen[0]&1024 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 13: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 1024
			if wireType != runtime.WireVarint {
				return 0, fmt.Errorf("field 13: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeVarint(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 13: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 13: %w", runtime.ErrTruncated)
			}
			tmp := v != 0
			p.Verified = &tmp
			off += n
		case 14:
			if seen[0]&2048 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 14: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 2048
			if wireType != runtime.WireFixed32 {
				return 0, fmt.Errorf("field 14: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeFixed32(b[off:])
			if n < 0 {
				return 0, fmt.Errorf("field 14: %w", runtime.ErrTruncated)
			}
			tmp := math.Float32frombits(v)
			p.Score = &tmp
			off += n
		case 15:
			if seen[0]&4096 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 15: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 4096
			if wireType != runtime.WireVarint {
				return 0, fmt.Errorf("field 15: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeVarint(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 15: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 15: %w", runtime.ErrTruncated)
			}
			tmp := int64(v)
			p.UpdatedAt = &tmp
			off += n
		case 16:
			if seen[0]&8192 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 16: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 8192
			if wireType != runtime.WireVarint {
				return 0, fmt.Errorf("field 16: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeVarint(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 16: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 16: %w", runtime.ErrTruncated)
			}
			tmp := Status(v)
			p.PrevStatus = &tmp
			off += n
		case 17:
			if seen[0]&16384 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 17: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 16384
			if wireType != runtime.WireBytes {
				return 0, fmt.Errorf("field 17: %w", runtime.ErrWireType)
			}
			payload, n := runtime.ConsumeBytes(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 17: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 17: %w", runtime.ErrTruncated)
			}
			tmp := make([]byte, len(payload))
			copy(tmp, payload)
			p.Fingerprint = tmp
			off += n
		case 18:
			if seen[0]&32768 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 18: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 32768
			if wireType != runtime.WireBytes {
				return 0, fmt.Errorf("field 18: %w", runtime.ErrWireType)
			}
			payload, n := runtime.ConsumeBytes(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 18: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 18: %w", runtime.ErrTruncated)
			}
			p.Email = string(payload)
			off += n
		case 19:
			if seen[0]&65536 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 19: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 65536
			if wireType != runtime.WireBytes {
				return 0, fmt.Errorf("field 19: %w", runtime.ErrWireType)
			}
			payload, n := runtime.ConsumeBytes(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 19: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 19: %w", runtime.ErrTruncated)
			}
			p.Role = string(payload)
			off += n
		case 20:
			if seen[0]&131072 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 20: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 131072
			if wireType != runtime.WireVarint {
				return 0, fmt.Errorf("field 20: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeVarint(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 20: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 20: %w", runtime.ErrTruncated)
			}
			p.TypeId = int32(v)
			off += n
		default:
			n = runtime.SkipField(b[off:], wireType)
			if n < 0 {
				if n == -3 {
					return 0, fmt.Errorf("unknown field %d: %w", fieldNum, runtime.ErrUnknownWireType)
				}
				return 0, fmt.Errorf("unknown field %d (wire type %d): %w", fieldNum, wireType, runtime.ErrTruncated)
			}
			off += n
		}
	}
	return off, nil
}

// UnmarshalBinary implements encoding.BinaryUnmarshaler.
// Duplicate non-repeated fields return an error.
func (p *Person) UnmarshalBinary(data []byte) error {
	_, err := p.unmarshalFrom(data, false, runtime.DefaultRecursionLimit)
	return err
}

// UnmarshalBinaryLenient unmarshals like UnmarshalBinary but allows
// duplicate non-repeated fields, keeping the last value.
func (p *Person) UnmarshalBinaryLenient(data []byte) error {
	_, err := p.unmarshalFrom(data, true, runtime.DefaultRecursionLimit)
	return err
}

// Status represents the lifecycle state of a person record.
// See also: https://example.com/docs/status */ for details.
type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_STATUS_ACTIVE      Status = 1
	Status_STATUS_INACTIVE    Status = 2
)
