// Code generated by gcode. DO NOT EDIT.
// source: person.entity.proto

package dao

func (x *Address) Validate() error {
	return nil
}

func (x *Person) Validate() error {
	if x.Address != nil {
		if err := x.Address.Validate(); err != nil {
			return err
		}
	}
	return nil
}
