// Code generated by gcode. DO NOT EDIT.
// source: person_service.proto

package dao

import (
	"fmt"
	"github.com/pinealctx/gcode/runtime"
)

type CreatePersonResponse struct {
	Id string `json:"id"`
}

type GetPersonRequest struct {
	Id string `json:"id"`
}

type GetPersonResponse struct {
	Name string `json:"name"`
	Age  int32  `json:"age"`
}

type UpdatePersonResponse struct {
	Ok bool `json:"ok"`
}

type DeletePersonRequest struct {
	Id string `json:"id"`
}

type DeletePersonResponse struct {
	Ok bool `json:"ok"`
}

// Size returns the protobuf wire size of CreatePersonResponse.
func (c *CreatePersonResponse) Size() int {
	if c == nil {
		return 0
	}
	var n int
	if len(c.Id) > 0 {
		n += 1 + runtime.SizeString(c.Id)
	}
	return n
}

// MarshalBinary implements encoding.BinaryMarshaler.
func (c *CreatePersonResponse) MarshalBinary() ([]byte, error) {
	return c.MarshalAppend(make([]byte, 0, c.Size()))
}

// MarshalAppend appends the protobuf wire encoding of CreatePersonResponse to b.
func (c *CreatePersonResponse) MarshalAppend(b []byte) ([]byte, error) {
	if len(c.Id) > 0 {
		b = runtime.AppendTag(b, 1, runtime.WireBytes)
		b = runtime.AppendString(b, c.Id)
	}
	return b, nil
}

// Size returns the protobuf wire size of GetPersonRequest.
func (g *GetPersonRequest) Size() int {
	if g == nil {
		return 0
	}
	var n int
	if len(g.Id) > 0 {
		n += 1 + runtime.SizeString(g.Id)
	}
	return n
}

// MarshalBinary implements encoding.BinaryMarshaler.
func (g *GetPersonRequest) MarshalBinary() ([]byte, error) {
	return g.MarshalAppend(make([]byte, 0, g.Size()))
}

// MarshalAppend appends the protobuf wire encoding of GetPersonRequest to b.
func (g *GetPersonRequest) MarshalAppend(b []byte) ([]byte, error) {
	if len(g.Id) > 0 {
		b = runtime.AppendTag(b, 1, runtime.WireBytes)
		b = runtime.AppendString(b, g.Id)
	}
	return b, nil
}

// Size returns the protobuf wire size of GetPersonResponse.
func (g *GetPersonResponse) Size() int {
	if g == nil {
		return 0
	}
	var n int
	if len(g.Name) > 0 {
		n += 1 + runtime.SizeString(g.Name)
	}
	if g.Age != 0 {
		n += 1 + runtime.SizeInt32(g.Age)
	}
	return n
}

// MarshalBinary implements encoding.BinaryMarshaler.
func (g *GetPersonResponse) MarshalBinary() ([]byte, error) {
	return g.MarshalAppend(make([]byte, 0, g.Size()))
}

// MarshalAppend appends the protobuf wire encoding of GetPersonResponse to b.
func (g *GetPersonResponse) MarshalAppend(b []byte) ([]byte, error) {
	if len(g.Name) > 0 {
		b = runtime.AppendTag(b, 1, runtime.WireBytes)
		b = runtime.AppendString(b, g.Name)
	}
	if g.Age != 0 {
		b = runtime.AppendTag(b, 2, runtime.WireVarint)
		b = runtime.AppendVarint(b, uint64(g.Age))
	}
	return b, nil
}

// Size returns the protobuf wire size of UpdatePersonResponse.
func (u *UpdatePersonResponse) Size() int {
	if u == nil {
		return 0
	}
	var n int
	if u.Ok {
		n += 1 + 1
	}
	return n
}

// MarshalBinary implements encoding.BinaryMarshaler.
func (u *UpdatePersonResponse) MarshalBinary() ([]byte, error) {
	return u.MarshalAppend(make([]byte, 0, u.Size()))
}

// MarshalAppend appends the protobuf wire encoding of UpdatePersonResponse to b.
func (u *UpdatePersonResponse) MarshalAppend(b []byte) ([]byte, error) {
	if u.Ok {
		b = runtime.AppendTag(b, 1, runtime.WireVarint)
		b = runtime.AppendBool(b, u.Ok)
	}
	return b, nil
}

// Size returns the protobuf wire size of DeletePersonRequest.
func (d *DeletePersonRequest) Size() int {
	if d == nil {
		return 0
	}
	var n int
	if len(d.Id) > 0 {
		n += 1 + runtime.SizeString(d.Id)
	}
	return n
}

// MarshalBinary implements encoding.BinaryMarshaler.
func (d *DeletePersonRequest) MarshalBinary() ([]byte, error) {
	return d.MarshalAppend(make([]byte, 0, d.Size()))
}

// MarshalAppend appends the protobuf wire encoding of DeletePersonRequest to b.
func (d *DeletePersonRequest) MarshalAppend(b []byte) ([]byte, error) {
	if len(d.Id) > 0 {
		b = runtime.AppendTag(b, 1, runtime.WireBytes)
		b = runtime.AppendString(b, d.Id)
	}
	return b, nil
}

// Size returns the protobuf wire size of DeletePersonResponse.
func (d *DeletePersonResponse) Size() int {
	if d == nil {
		return 0
	}
	var n int
	if d.Ok {
		n += 1 + 1
	}
	return n
}

// MarshalBinary implements encoding.BinaryMarshaler.
func (d *DeletePersonResponse) MarshalBinary() ([]byte, error) {
	return d.MarshalAppend(make([]byte, 0, d.Size()))
}

// MarshalAppend appends the protobuf wire encoding of DeletePersonResponse to b.
func (d *DeletePersonResponse) MarshalAppend(b []byte) ([]byte, error) {
	if d.Ok {
		b = runtime.AppendTag(b, 1, runtime.WireVarint)
		b = runtime.AppendBool(b, d.Ok)
	}
	return b, nil
}

// unmarshalFrom decodes a protobuf wire-format message from b.
// Returns the number of bytes consumed.
// If lenient is true, duplicate non-repeated fields use last-one-wins.
func (c *CreatePersonResponse) unmarshalFrom(b []byte, lenient bool) (int, error) {
	var seen [2]uint64
	off := 0
	for off < len(b) {
		fieldNum, wireType, n := runtime.ConsumeTag(b[off:])
		if n < 0 {
			if n == -2 {
				return 0, fmt.Errorf("field tag: %w", runtime.ErrOverflow)
			}
			return 0, fmt.Errorf("field tag: %w", runtime.ErrTruncated)
		}
		off += n

		switch fieldNum {
		case 1:
			if seen[0]&1 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 1: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 1
			if wireType != runtime.WireBytes {
				return 0, fmt.Errorf("field 1: %w", runtime.ErrWireType)
			}
			payload, n := runtime.ConsumeBytes(b[off:])
			if n < 0 {
				return 0, fmt.Errorf("field 1: %w", runtime.ErrTruncated)
			}
			c.Id = string(payload)
			off += n
		default:
			n = runtime.SkipField(b[off:], wireType)
			if n < 0 {
				return 0, fmt.Errorf("unknown field %d: %w", fieldNum, runtime.ErrTruncated)
			}
			off += n
		}
	}
	return off, nil
}

// UnmarshalBinary implements encoding.BinaryUnmarshaler.
// Duplicate non-repeated fields return an error.
func (c *CreatePersonResponse) UnmarshalBinary(data []byte) error {
	_, err := c.unmarshalFrom(data, false)
	return err
}

// UnmarshalBinaryLenient unmarshals like UnmarshalBinary but allows
// duplicate non-repeated fields, keeping the last value.
func (c *CreatePersonResponse) UnmarshalBinaryLenient(data []byte) error {
	_, err := c.unmarshalFrom(data, true)
	return err
}

// unmarshalFrom decodes a protobuf wire-format message from b.
// Returns the number of bytes consumed.
// If lenient is true, duplicate non-repeated fields use last-one-wins.
func (g *GetPersonRequest) unmarshalFrom(b []byte, lenient bool) (int, error) {
	var seen [2]uint64
	off := 0
	for off < len(b) {
		fieldNum, wireType, n := runtime.ConsumeTag(b[off:])
		if n < 0 {
			if n == -2 {
				return 0, fmt.Errorf("field tag: %w", runtime.ErrOverflow)
			}
			return 0, fmt.Errorf("field tag: %w", runtime.ErrTruncated)
		}
		off += n

		switch fieldNum {
		case 1:
			if seen[0]&1 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 1: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 1
			if wireType != runtime.WireBytes {
				return 0, fmt.Errorf("field 1: %w", runtime.ErrWireType)
			}
			payload, n := runtime.ConsumeBytes(b[off:])
			if n < 0 {
				return 0, fmt.Errorf("field 1: %w", runtime.ErrTruncated)
			}
			g.Id = string(payload)
			off += n
		default:
			n = runtime.SkipField(b[off:], wireType)
			if n < 0 {
				return 0, fmt.Errorf("unknown field %d: %w", fieldNum, runtime.ErrTruncated)
			}
			off += n
		}
	}
	return off, nil
}

// UnmarshalBinary implements encoding.BinaryUnmarshaler.
// Duplicate non-repeated fields return an error.
func (g *GetPersonRequest) UnmarshalBinary(data []byte) error {
	_, err := g.unmarshalFrom(data, false)
	return err
}

// UnmarshalBinaryLenient unmarshals like UnmarshalBinary but allows
// duplicate non-repeated fields, keeping the last value.
func (g *GetPersonRequest) UnmarshalBinaryLenient(data []byte) error {
	_, err := g.unmarshalFrom(data, true)
	return err
}

// unmarshalFrom decodes a protobuf wire-format message from b.
// Returns the number of bytes consumed.
// If lenient is true, duplicate non-repeated fields use last-one-wins.
func (g *GetPersonResponse) unmarshalFrom(b []byte, lenient bool) (int, error) {
	var seen [2]uint64
	off := 0
	for off < len(b) {
		fieldNum, wireType, n := runtime.ConsumeTag(b[off:])
		if n < 0 {
			if n == -2 {
				return 0, fmt.Errorf("field tag: %w", runtime.ErrOverflow)
			}
			return 0, fmt.Errorf("field tag: %w", runtime.ErrTruncated)
		}
		off += n

		switch fieldNum {
		case 1:
			if seen[0]&1 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 1: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 1
			if wireType != runtime.WireBytes {
				return 0, fmt.Errorf("field 1: %w", runtime.ErrWireType)
			}
			payload, n := runtime.ConsumeBytes(b[off:])
			if n < 0 {
				return 0, fmt.Errorf("field 1: %w", runtime.ErrTruncated)
			}
			g.Name = string(payload)
			off += n
		case 2:
			if seen[0]&2 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 2: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 2
			if wireType != runtime.WireVarint {
				return 0, fmt.Errorf("field 2: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeVarint(b[off:])
			if n < 0 {
				return 0, fmt.Errorf("field 2: %w", runtime.ErrTruncated)
			}
			g.Age = int32(v)
			off += n
		default:
			n = runtime.SkipField(b[off:], wireType)
			if n < 0 {
				return 0, fmt.Errorf("unknown field %d: %w", fieldNum, runtime.ErrTruncated)
			}
			off += n
		}
	}
	return off, nil
}

// UnmarshalBinary implements encoding.BinaryUnmarshaler.
// Duplicate non-repeated fields return an error.
func (g *GetPersonResponse) UnmarshalBinary(data []byte) error {
	_, err := g.unmarshalFrom(data, false)
	return err
}

// UnmarshalBinaryLenient unmarshals like UnmarshalBinary but allows
// duplicate non-repeated fields, keeping the last value.
func (g *GetPersonResponse) UnmarshalBinaryLenient(data []byte) error {
	_, err := g.unmarshalFrom(data, true)
	return err
}

// unmarshalFrom decodes a protobuf wire-format message from b.
// Returns the number of bytes consumed.
// If lenient is true, duplicate non-repeated fields use last-one-wins.
func (u *UpdatePersonResponse) unmarshalFrom(b []byte, lenient bool) (int, error) {
	var seen [2]uint64
	off := 0
	for off < len(b) {
		fieldNum, wireType, n := runtime.ConsumeTag(b[off:])
		if n < 0 {
			if n == -2 {
				return 0, fmt.Errorf("field tag: %w", runtime.ErrOverflow)
			}
			return 0, fmt.Errorf("field tag: %w", runtime.ErrTruncated)
		}
		off += n

		switch fieldNum {
		case 1:
			if seen[0]&1 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 1: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 1
			if wireType != runtime.WireVarint {
				return 0, fmt.Errorf("field 1: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeVarint(b[off:])
			if n < 0 {
				return 0, fmt.Errorf("field 1: %w", runtime.ErrTruncated)
			}
			u.Ok = v != 0
			off += n
		default:
			n = runtime.SkipField(b[off:], wireType)
			if n < 0 {
				return 0, fmt.Errorf("unknown field %d: %w", fieldNum, runtime.ErrTruncated)
			}
			off += n
		}
	}
	return off, nil
}

// UnmarshalBinary implements encoding.BinaryUnmarshaler.
// Duplicate non-repeated fields return an error.
func (u *UpdatePersonResponse) UnmarshalBinary(data []byte) error {
	_, err := u.unmarshalFrom(data, false)
	return err
}

// UnmarshalBinaryLenient unmarshals like UnmarshalBinary but allows
// duplicate non-repeated fields, keeping the last value.
func (u *UpdatePersonResponse) UnmarshalBinaryLenient(data []byte) error {
	_, err := u.unmarshalFrom(data, true)
	return err
}

// unmarshalFrom decodes a protobuf wire-format message from b.
// Returns the number of bytes consumed.
// If lenient is true, duplicate non-repeated fields use last-one-wins.
func (d *DeletePersonRequest) unmarshalFrom(b []byte, lenient bool) (int, error) {
	var seen [2]uint64
	off := 0
	for off < len(b) {
		fieldNum, wireType, n := runtime.ConsumeTag(b[off:])
		if n < 0 {
			if n == -2 {
				return 0, fmt.Errorf("field tag: %w", runtime.ErrOverflow)
			}
			return 0, fmt.Errorf("field tag: %w", runtime.ErrTruncated)
		}
		off += n

		switch fieldNum {
		case 1:
			if seen[0]&1 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 1: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 1
			if wireType != runtime.WireBytes {
				return 0, fmt.Errorf("field 1: %w", runtime.ErrWireType)
			}
			payload, n := runtime.ConsumeBytes(b[off:])
			if n < 0 {
				return 0, fmt.Errorf("field 1: %w", runtime.ErrTruncated)
			}
			d.Id = string(payload)
			off += n
		default:
			n = runtime.SkipField(b[off:], wireType)
			if n < 0 {
				return 0, fmt.Errorf("unknown field %d: %w", fieldNum, runtime.ErrTruncated)
			}
			off += n
		}
	}
	return off, nil
}

// UnmarshalBinary implements encoding.BinaryUnmarshaler.
// Duplicate non-repeated fields return an error.
func (d *DeletePersonRequest) UnmarshalBinary(data []byte) error {
	_, err := d.unmarshalFrom(data, false)
	return err
}

// UnmarshalBinaryLenient unmarshals like UnmarshalBinary but allows
// duplicate non-repeated fields, keeping the last value.
func (d *DeletePersonRequest) UnmarshalBinaryLenient(data []byte) error {
	_, err := d.unmarshalFrom(data, true)
	return err
}

// unmarshalFrom decodes a protobuf wire-format message from b.
// Returns the number of bytes consumed.
// If lenient is true, duplicate non-repeated fields use last-one-wins.
func (d *DeletePersonResponse) unmarshalFrom(b []byte, lenient bool) (int, error) {
	var seen [2]uint64
	off := 0
	for off < len(b) {
		fieldNum, wireType, n := runtime.ConsumeTag(b[off:])
		if n < 0 {
			if n == -2 {
				return 0, fmt.Errorf("field tag: %w", runtime.ErrOverflow)
			}
			return 0, fmt.Errorf("field tag: %w", runtime.ErrTruncated)
		}
		off += n

		switch fieldNum {
		case 1:
			if seen[0]&1 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 1: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 1
			if wireType != runtime.WireVarint {
				return 0, fmt.Errorf("field 1: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeVarint(b[off:])
			if n < 0 {
				return 0, fmt.Errorf("field 1: %w", runtime.ErrTruncated)
			}
			d.Ok = v != 0
			off += n
		default:
			n = runtime.SkipField(b[off:], wireType)
			if n < 0 {
				return 0, fmt.Errorf("unknown field %d: %w", fieldNum, runtime.ErrTruncated)
			}
			off += n
		}
	}
	return off, nil
}

// UnmarshalBinary implements encoding.BinaryUnmarshaler.
// Duplicate non-repeated fields return an error.
func (d *DeletePersonResponse) UnmarshalBinary(data []byte) error {
	_, err := d.unmarshalFrom(data, false)
	return err
}

// UnmarshalBinaryLenient unmarshals like UnmarshalBinary but allows
// duplicate non-repeated fields, keeping the last value.
func (d *DeletePersonResponse) UnmarshalBinaryLenient(data []byte) error {
	_, err := d.unmarshalFrom(data, true)
	return err
}
