// Code generated by gcode. DO NOT EDIT.
// source: person_service.proto

package dao

import (
	"github.com/pinealctx/gcode/validateruntime"
)

func (x *CreatePersonResponse) Validate() error {
	return nil
}

func (x *GetPersonRequest) Validate() error {
	if x.Id != "" {
		if len(x.Id) < 1 {
			return &validateruntime.ValidationError{Field: "id", Rule: "min_len", Message: validateruntime.MsgOr("", "length must be >= 1")}
		}
		if len(x.Id) > 64 {
			return &validateruntime.ValidationError{Field: "id", Rule: "max_len", Message: validateruntime.MsgOr("", "length must be <= 64")}
		}
	}
	return nil
}

func (x *GetPersonResponse) Validate() error {
	return nil
}

func (x *UpdatePersonResponse) Validate() error {
	return nil
}

func (x *DeletePersonRequest) Validate() error {
	if x.Id != "" {
		if len(x.Id) < 1 {
			return &validateruntime.ValidationError{Field: "id", Rule: "min_len", Message: validateruntime.MsgOr("", "length must be >= 1")}
		}
		if len(x.Id) > 64 {
			return &validateruntime.ValidationError{Field: "id", Rule: "max_len", Message: validateruntime.MsgOr("", "length must be <= 64")}
		}
	}
	return nil
}

func (x *DeletePersonResponse) Validate() error {
	return nil
}
