// Code generated by gcode. DO NOT EDIT.
// source: person.update.proto

package dao

import (
	"fmt"
	"github.com/pinealctx/gcode/runtime"
	"math"
)

type PersonUpdateByName struct {
	Name       string   `json:"name"`
	Age        *int32   `json:"age"`
	Active     *bool    `json:"active"`
	Status     *Status  `json:"status"`
	Rating     *float32 `json:"rating"`
	CreatedAt  *int64   `json:"createdAt"`
	Nickname   *string  `json:"nickname"`
	Level      *int32   `json:"level"`
	Verified   *bool    `json:"verified"`
	Score      *float32 `json:"score"`
	UpdatedAt  *int64   `json:"updatedAt"`
	PrevStatus *Status  `json:"prevStatus"`
	Email      *string  `json:"email"`
	Role       *string  `json:"role"`
	TypeId     *int32   `json:"typeId"`
}

// Size returns the protobuf wire size of PersonUpdateByName.
func (x *PersonUpdateByName) Size() int {
	if x == nil {
		return 0
	}
	var n int
	if len(x.Name) > 0 {
		n += 1 + runtime.SizeString(x.Name)
	}
	if x.Age != nil {
		n += 1 + runtime.SizeInt32(*x.Age)
	}
	if x.Active != nil {
		n += 1 + 1
	}
	if x.Status != nil {
		n += 1 + runtime.SizeEnum(int32(*x.Status))
	}
	if x.Rating != nil {
		n += 1 + 4
	}
	if x.CreatedAt != nil {
		n += 1 + runtime.SizeInt64(*x.CreatedAt)
	}
	if x.Nickname != nil {
		n += 1 + runtime.SizeString(*x.Nickname)
	}
	if x.Level != nil {
		n += 1 + runtime.SizeInt32(*x.Level)
	}
	if x.Verified != nil {
		n += 1 + 1
	}
	if x.Score != nil {
		n += 1 + 4
	}
	if x.UpdatedAt != nil {
		n += 1 + runtime.SizeInt64(*x.UpdatedAt)
	}
	if x.PrevStatus != nil {
		n += 1 + runtime.SizeEnum(int32(*x.PrevStatus))
	}
	if x.Email != nil {
		n += 1 + runtime.SizeString(*x.Email)
	}
	if x.Role != nil {
		n += 1 + runtime.SizeString(*x.Role)
	}
	if x.TypeId != nil {
		n += 1 + runtime.SizeInt32(*x.TypeId)
	}
	return n
}

// MarshalBinary implements encoding.BinaryMarshaler.
func (x *PersonUpdateByName) MarshalBinary() ([]byte, error) {
	return x.MarshalAppend(make([]byte, 0, x.Size()))
}

// MarshalAppend appends the protobuf wire encoding of PersonUpdateByName to b.
func (x *PersonUpdateByName) MarshalAppend(b []byte) ([]byte, error) {
	if len(x.Name) > 0 {
		b = runtime.AppendTag(b, 1, runtime.WireBytes)
		b = runtime.AppendString(b, x.Name)
	}
	if x.Age != nil {
		b = runtime.AppendTag(b, 2, runtime.WireVarint)
		b = runtime.AppendVarint(b, uint64(*x.Age))
	}
	if x.Active != nil {
		b = runtime.AppendTag(b, 3, runtime.WireVarint)
		b = runtime.AppendBool(b, *x.Active)
	}
	if x.Status != nil {
		b = runtime.AppendTag(b, 4, runtime.WireVarint)
		b = runtime.AppendVarint(b, uint64(*x.Status))
	}
	if x.Rating != nil {
		b = runtime.AppendTag(b, 5, runtime.WireFixed32)
		b = runtime.AppendFloat(b, *x.Rating)
	}
	if x.CreatedAt != nil {
		b = runtime.AppendTag(b, 6, runtime.WireVarint)
		b = runtime.AppendVarint(b, uint64(*x.CreatedAt))
	}
	if x.Nickname != nil {
		b = runtime.AppendTag(b, 7, runtime.WireBytes)
		b = runtime.AppendString(b, *x.Nickname)
	}
	if x.Level != nil {
		b = runtime.AppendTag(b, 8, runtime.WireVarint)
		b = runtime.AppendVarint(b, uint64(*x.Level))
	}
	if x.Verified != nil {
		b = runtime.AppendTag(b, 9, runtime.WireVarint)
		b = runtime.AppendBool(b, *x.Verified)
	}
	if x.Score != nil {
		b = runtime.AppendTag(b, 10, runtime.WireFixed32)
		b = runtime.AppendFloat(b, *x.Score)
	}
	if x.UpdatedAt != nil {
		b = runtime.AppendTag(b, 11, runtime.WireVarint)
		b = runtime.AppendVarint(b, uint64(*x.UpdatedAt))
	}
	if x.PrevStatus != nil {
		b = runtime.AppendTag(b, 12, runtime.WireVarint)
		b = runtime.AppendVarint(b, uint64(*x.PrevStatus))
	}
	if x.Email != nil {
		b = runtime.AppendTag(b, 13, runtime.WireBytes)
		b = runtime.AppendString(b, *x.Email)
	}
	if x.Role != nil {
		b = runtime.AppendTag(b, 14, runtime.WireBytes)
		b = runtime.AppendString(b, *x.Role)
	}
	if x.TypeId != nil {
		b = runtime.AppendTag(b, 15, runtime.WireVarint)
		b = runtime.AppendVarint(b, uint64(*x.TypeId))
	}
	return b, nil
}

// unmarshalFrom decodes a protobuf wire-format message from b.
// Returns the number of bytes consumed.
// If lenient is true, duplicate non-repeated fields use last-one-wins.
// depth is the remaining nesting budget; callers pass runtime.DefaultRecursionLimit.
func (x *PersonUpdateByName) unmarshalFrom(b []byte, lenient bool, depth int) (int, error) {
	if depth <= 0 {
		return 0, runtime.ErrNestingDepth
	}
	var seen [2]uint64
	off := 0
	for off < len(b) {
		fieldNum, wireType, n := runtime.ConsumeTag(b[off:])
		if n < 0 {
			if n == -2 {
				return 0, fmt.Errorf("field tag: %w", runtime.ErrOverflow)
			}
			return 0, fmt.Errorf("field tag: %w", runtime.ErrTruncated)
		}
		off += n

		switch fieldNum {
		case 1:
			if seen[0]&1 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 1: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 1
			if wireType != runtime.WireBytes {
				return 0, fmt.Errorf("field 1: %w", runtime.ErrWireType)
			}
			payload, n := runtime.ConsumeBytes(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 1: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 1: %w", runtime.ErrTruncated)
			}
			x.Name = string(payload)
			off += n
		case 2:
			if seen[0]&2 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 2: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 2
			if wireType != runtime.WireVarint {
				return 0, fmt.Errorf("field 2: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeVarint(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 2: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 2: %w", runtime.ErrTruncated)
			}
			tmp := int32(v)
			x.Age = &tmp
			off += n
		case 3:
			if seen[0]&4 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 3: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 4
			if wireType != runtime.WireVarint {
				return 0, fmt.Errorf("field 3: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeVarint(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 3: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 3: %w", runtime.ErrTruncated)
			}
			tmp := v != 0
			x.Active = &tmp
			off += n
		case 4:
			if seen[0]&8 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 4: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 8
			if wireType != runtime.WireVarint {
				return 0, fmt.Errorf("field 4: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeVarint(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 4: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 4: %w", runtime.ErrTruncated)
			}
			tmp := Status(v)
			x.Status = &tmp
			off += n
		case 5:
			if seen[0]&16 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 5: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 16
			if wireType != runtime.WireFixed32 {
				return 0, fmt.Errorf("field 5: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeFixed32(b[off:])
			if n < 0 {
				return 0, fmt.Errorf("field 5: %w", runtime.ErrTruncated)
			}
			tmp := math.Float32frombits(v)
			x.Rating = &tmp
			off += n
		case 6:
			if seen[0]&32 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 6: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 32
			if wireType != runtime.WireVarint {
				return 0, fmt.Errorf("field 6: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeVarint(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 6: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 6: %w", runtime.ErrTruncated)
			}
			tmp := int64(v)
			x.CreatedAt = &tmp
			off += n
		case 7:
			if seen[0]&64 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 7: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 64
			if wireType != runtime.WireBytes {
				return 0, fmt.Errorf("field 7: %w", runtime.ErrWireType)
			}
			payload, n := runtime.ConsumeBytes(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 7: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 7: %w", runtime.ErrTruncated)
			}
			tmp := string(payload)
			x.Nickname = &tmp
			off += n
		case 8:
			if seen[0]&128 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 8: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 128
			if wireType != runtime.WireVarint {
				return 0, fmt.Errorf("field 8: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeVarint(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 8: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 8: %w", runtime.ErrTruncated)
			}
			tmp := int32(v)
			x.Level = &tmp
			off += n
		case 9:
			if seen[0]&256 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 9: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 256
			if wireType != runtime.WireVarint {
				return 0, fmt.Errorf("field 9: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeVarint(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 9: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 9: %w", runtime.ErrTruncated)
			}
			tmp := v != 0
			x.Verified = &tmp
			off += n
		case 10:
			if seen[0]&512 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 10: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 512
			if wireType != runtime.WireFixed32 {
				return 0, fmt.Errorf("field 10: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeFixed32(b[off:])
			if n < 0 {
				return 0, fmt.Errorf("field 10: %w", runtime.ErrTruncated)
			}
			tmp := math.Float32frombits(v)
			x.Score = &tmp
			off += n
		case 11:
			if seen[0]&1024 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 11: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 1024
			if wireType != runtime.WireVarint {
				return 0, fmt.Errorf("field 11: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeVarint(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 11: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 11: %w", runtime.ErrTruncated)
			}
			tmp := int64(v)
			x.UpdatedAt = &tmp
			off += n
		case 12:
			if seen[0]&2048 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 12: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 2048
			if wireType != runtime.WireVarint {
				return 0, fmt.Errorf("field 12: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeVarint(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 12: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 12: %w", runtime.ErrTruncated)
			}
			tmp := Status(v)
			x.PrevStatus = &tmp
			off += n
		case 13:
			if seen[0]&4096 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 13: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 4096
			if wireType != runtime.WireBytes {
				return 0, fmt.Errorf("field 13: %w", runtime.ErrWireType)
			}
			payload, n := runtime.ConsumeBytes(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 13: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 13: %w", runtime.ErrTruncated)
			}
			tmp := string(payload)
			x.Email = &tmp
			off += n
		case 14:
			if seen[0]&8192 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 14: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 8192
			if wireType != runtime.WireBytes {
				return 0, fmt.Errorf("field 14: %w", runtime.ErrWireType)
			}
			payload, n := runtime.ConsumeBytes(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 14: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 14: %w", runtime.ErrTruncated)
			}
			tmp := string(payload)
			x.Role = &tmp
			off += n
		case 15:
			if seen[0]&16384 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 15: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 16384
			if wireType != runtime.WireVarint {
				return 0, fmt.Errorf("field 15: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeVarint(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 15: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 15: %w", runtime.ErrTruncated)
			}
			tmp := int32(v)
			x.TypeId = &tmp
			off += n
		default:
			n = runtime.SkipField(b[off:], wireType)
			if n < 0 {
				if n == -3 {
					return 0, fmt.Errorf("unknown field %d: %w", fieldNum, runtime.ErrUnknownWireType)
				}
				return 0, fmt.Errorf("unknown field %d (wire type %d): %w", fieldNum, wireType, runtime.ErrTruncated)
			}
			off += n
		}
	}
	return off, nil
}

// UnmarshalBinary implements encoding.BinaryUnmarshaler.
// Duplicate non-repeated fields return an error.
func (x *PersonUpdateByName) UnmarshalBinary(data []byte) error {
	_, err := x.unmarshalFrom(data, false, runtime.DefaultRecursionLimit)
	return err
}

// UnmarshalBinaryLenient unmarshals like UnmarshalBinary but allows
// duplicate non-repeated fields, keeping the last value.
func (x *PersonUpdateByName) UnmarshalBinaryLenient(data []byte) error {
	_, err := x.unmarshalFrom(data, true, runtime.DefaultRecursionLimit)
	return err
}

// ToMap converts PersonUpdateByName to map[string]any for partial update APIs (e.g. GORM Updates).
// Only non-nil fields are included.
func (x *PersonUpdateByName) ToMap() map[string]any {
	um := make(map[string]any)
	if x.Age != nil {
		um["age"] = *x.Age
	}
	if x.Active != nil {
		um["active"] = *x.Active
	}
	if x.Status != nil {
		um["status"] = *x.Status
	}
	if x.Rating != nil {
		um["rating"] = *x.Rating
	}
	if x.CreatedAt != nil {
		um["created_ts"] = *x.CreatedAt
	}
	if x.Nickname != nil {
		um["nickname"] = *x.Nickname
	}
	if x.Level != nil {
		um["level"] = *x.Level
	}
	if x.Verified != nil {
		um["verified"] = *x.Verified
	}
	if x.Score != nil {
		um["score"] = *x.Score
	}
	if x.UpdatedAt != nil {
		um["updated_at"] = *x.UpdatedAt
	}
	if x.PrevStatus != nil {
		um["prev_status"] = *x.PrevStatus
	}
	if x.Email != nil {
		um["email"] = *x.Email
	}
	if x.Role != nil {
		um["role"] = *x.Role
	}
	if x.TypeId != nil {
		um["type_id"] = *x.TypeId
	}
	return um
}
