// Code generated by gcode. DO NOT EDIT.
// source: person_service.proto

package dao

import (
	"github.com/pinealctx/gcode/validateruntime"
)

func (c *CreatePersonResponse) Validate() error {
	return nil
}

func (g *GetPersonRequest) Validate() error {
	if g.Id != "" {
		if len(g.Id) < 1 {
			return &validateruntime.ValidationError{Field: "id", Rule: "min_len", Message: validateruntime.MsgOr("", "length must be >= 1")}
		}
		if len(g.Id) > 64 {
			return &validateruntime.ValidationError{Field: "id", Rule: "max_len", Message: validateruntime.MsgOr("", "length must be <= 64")}
		}
	}
	return nil
}

func (g *GetPersonResponse) Validate() error {
	return nil
}

func (u *UpdatePersonResponse) Validate() error {
	return nil
}

func (d *DeletePersonRequest) Validate() error {
	if d.Id != "" {
		if len(d.Id) < 1 {
			return &validateruntime.ValidationError{Field: "id", Rule: "min_len", Message: validateruntime.MsgOr("", "length must be >= 1")}
		}
		if len(d.Id) > 64 {
			return &validateruntime.ValidationError{Field: "id", Rule: "max_len", Message: validateruntime.MsgOr("", "length must be <= 64")}
		}
	}
	return nil
}

func (d *DeletePersonResponse) Validate() error {
	return nil
}
