// Code generated by gcode. DO NOT EDIT.
// source: person.proto

package dao

import (
	"fmt"
	"github.com/pinealctx/gcode/validateruntime"
)

func (x *Address) Validate() error {
	return nil
}

func (x *Person) Validate() error {
	if x.Name != "" {
		if len(x.Name) < 1 {
			return &validateruntime.ValidationError{Field: "name", Rule: "min_len", Message: validateruntime.MsgOr("", "length must be >= 1")}
		}
		if len(x.Name) > 100 {
			return &validateruntime.ValidationError{Field: "name", Rule: "max_len", Message: validateruntime.MsgOr("", "length must be <= 100")}
		}
	}
	if x.Age < 0 {
		return &validateruntime.ValidationError{Field: "age", Rule: "gte", Message: validateruntime.MsgOr("", "must be >= 0")}
	}
	if x.Age > 150 {
		return &validateruntime.ValidationError{Field: "age", Rule: "lte", Message: validateruntime.MsgOr("", "must be <= 150")}
	}
	switch x.Status {
	case Status_STATUS_UNSPECIFIED, Status_STATUS_ACTIVE, Status_STATUS_INACTIVE:
	// ok
	default:
		return &validateruntime.ValidationError{Field: "status", Rule: "defined_only", Message: validateruntime.MsgOr("", "must be a defined enum value")}
	}
	if x.Address == nil {
		return &validateruntime.ValidationError{Field: "address", Rule: "required", Message: validateruntime.MsgOr("", "is required")}
	}
	if err := x.Address.Validate(); err != nil {
		return err
	}
	if len(x.Scores) < 1 {
		return &validateruntime.ValidationError{Field: "scores", Rule: "min_items", Message: validateruntime.MsgOr("", "must have at least 1 item(s)")}
	}
	if len(x.Scores) > 100 {
		return &validateruntime.ValidationError{Field: "scores", Rule: "max_items", Message: validateruntime.MsgOr("", "must have at most 100 item(s)")}
	}
	if len(x.Tags) < 1 {
		return &validateruntime.ValidationError{Field: "tags", Rule: "min_items", Message: validateruntime.MsgOr("", "must have at least 1 item(s)")}
	}
	for i, v := range x.Tags {
		if len(v) < 1 {
			return &validateruntime.ValidationError{Field: fmt.Sprintf("tags[%d]", i), Rule: "min_len", Message: validateruntime.MsgOr("", "length must be >= 1")}
		}
	}
	if x.Avatar == nil {
		return &validateruntime.ValidationError{Field: "avatar", Rule: "required", Message: validateruntime.MsgOr("", "is required")}
	}
	if len(x.Avatar) < 1 {
		return &validateruntime.ValidationError{Field: "avatar", Rule: "min_len", Message: validateruntime.MsgOr("", "length must be >= 1")}
	}
	if x.Nickname != nil {
		if *x.Nickname != "" {
			if len(*x.Nickname) < 1 {
				return &validateruntime.ValidationError{Field: "nickname", Rule: "min_len", Message: validateruntime.MsgOr("", "length must be >= 1")}
			}
			if len(*x.Nickname) > 10 {
				return &validateruntime.ValidationError{Field: "nickname", Rule: "max_len", Message: validateruntime.MsgOr("", "length must be <= 10")}
			}
		}
	}
	if x.Email != "" {
		if !validateruntime.IsEmail(x.Email) {
			return &validateruntime.ValidationError{Field: "email", Rule: "email", Message: validateruntime.MsgOr("", "must be a valid email address")}
		}
	}
	if x.Role != "" {
		{
			found := false
			for _, v := range []string{"admin", "user", "guest"} {
				if x.Role == v {
					found = true
					break
				}
			}
			if !found {
				return &validateruntime.ValidationError{Field: "role", Rule: "in", Message: validateruntime.MsgOr("", "must be one of [admin, user, guest]")}
			}
		}
	}
	for _, v := range []int32{0, -1} {
		if x.TypeId == v {
			return &validateruntime.ValidationError{Field: "type_id", Rule: "not_in", Message: validateruntime.MsgOr("", "must not be one of [0, -1]")}
		}
	}
	return nil
}
