// Code generated by gcode. DO NOT EDIT.
// source: person.create.proto

package dao

import (
	"fmt"
	"github.com/pinealctx/gcode/runtime"
	"math"
)

type PersonCreate struct {
	Name       *string  `json:"name" gorm:"column:name"`
	Age        *int32   `json:"age" gorm:"column:age"`
	Active     *bool    `json:"active" gorm:"column:active"`
	Status     *Status  `json:"status" gorm:"column:status"`
	Rating     *float32 `json:"rating" gorm:"column:rating"`
	Nickname   string   `json:"nickname" gorm:"column:nickname"`
	Level      *int32   `json:"level" gorm:"column:level"`
	Verified   *bool    `json:"verified" gorm:"column:verified"`
	Score      *float32 `json:"score" gorm:"column:score"`
	UpdatedAt  *int64   `json:"updatedAt" gorm:"column:updated_at"`
	PrevStatus *Status  `json:"prevStatus" gorm:"column:prev_status"`
	Email      *string  `json:"email" gorm:"column:email"`
	Role       *string  `json:"role" gorm:"column:role"`
	TypeId     *int32   `json:"typeId" gorm:"column:type_id"`
}

func (PersonCreate) TableName() string { return "persons" }

// Size returns the protobuf wire size of PersonCreate.
func (x *PersonCreate) Size() int {
	if x == nil {
		return 0
	}
	var n int
	if x.Name != nil {
		n += 1 + runtime.SizeString(*x.Name)
	}
	if x.Age != nil {
		n += 1 + runtime.SizeInt32(*x.Age)
	}
	if x.Active != nil {
		n += 1 + 1
	}
	if x.Status != nil {
		n += 1 + runtime.SizeEnum(int32(*x.Status))
	}
	if x.Rating != nil {
		n += 1 + 4
	}
	if len(x.Nickname) > 0 {
		n += 1 + runtime.SizeString(x.Nickname)
	}
	if x.Level != nil {
		n += 1 + runtime.SizeInt32(*x.Level)
	}
	if x.Verified != nil {
		n += 1 + 1
	}
	if x.Score != nil {
		n += 1 + 4
	}
	if x.UpdatedAt != nil {
		n += 1 + runtime.SizeInt64(*x.UpdatedAt)
	}
	if x.PrevStatus != nil {
		n += 1 + runtime.SizeEnum(int32(*x.PrevStatus))
	}
	if x.Email != nil {
		n += 1 + runtime.SizeString(*x.Email)
	}
	if x.Role != nil {
		n += 1 + runtime.SizeString(*x.Role)
	}
	if x.TypeId != nil {
		n += 1 + runtime.SizeInt32(*x.TypeId)
	}
	return n
}

// MarshalBinary implements encoding.BinaryMarshaler.
func (x *PersonCreate) MarshalBinary() ([]byte, error) {
	return x.MarshalAppend(make([]byte, 0, x.Size()))
}

// MarshalAppend appends the protobuf wire encoding of PersonCreate to b.
func (x *PersonCreate) MarshalAppend(b []byte) ([]byte, error) {
	if x.Name != nil {
		b = runtime.AppendTag(b, 1, runtime.WireBytes)
		b = runtime.AppendString(b, *x.Name)
	}
	if x.Age != nil {
		b = runtime.AppendTag(b, 2, runtime.WireVarint)
		b = runtime.AppendVarint(b, uint64(*x.Age))
	}
	if x.Active != nil {
		b = runtime.AppendTag(b, 3, runtime.WireVarint)
		b = runtime.AppendBool(b, *x.Active)
	}
	if x.Status != nil {
		b = runtime.AppendTag(b, 4, runtime.WireVarint)
		b = runtime.AppendVarint(b, uint64(*x.Status))
	}
	if x.Rating != nil {
		b = runtime.AppendTag(b, 5, runtime.WireFixed32)
		b = runtime.AppendFloat(b, *x.Rating)
	}
	if len(x.Nickname) > 0 {
		b = runtime.AppendTag(b, 6, runtime.WireBytes)
		b = runtime.AppendString(b, x.Nickname)
	}
	if x.Level != nil {
		b = runtime.AppendTag(b, 7, runtime.WireVarint)
		b = runtime.AppendVarint(b, uint64(*x.Level))
	}
	if x.Verified != nil {
		b = runtime.AppendTag(b, 8, runtime.WireVarint)
		b = runtime.AppendBool(b, *x.Verified)
	}
	if x.Score != nil {
		b = runtime.AppendTag(b, 9, runtime.WireFixed32)
		b = runtime.AppendFloat(b, *x.Score)
	}
	if x.UpdatedAt != nil {
		b = runtime.AppendTag(b, 10, runtime.WireVarint)
		b = runtime.AppendVarint(b, uint64(*x.UpdatedAt))
	}
	if x.PrevStatus != nil {
		b = runtime.AppendTag(b, 11, runtime.WireVarint)
		b = runtime.AppendVarint(b, uint64(*x.PrevStatus))
	}
	if x.Email != nil {
		b = runtime.AppendTag(b, 12, runtime.WireBytes)
		b = runtime.AppendString(b, *x.Email)
	}
	if x.Role != nil {
		b = runtime.AppendTag(b, 13, runtime.WireBytes)
		b = runtime.AppendString(b, *x.Role)
	}
	if x.TypeId != nil {
		b = runtime.AppendTag(b, 14, runtime.WireVarint)
		b = runtime.AppendVarint(b, uint64(*x.TypeId))
	}
	return b, nil
}

// unmarshalFrom decodes a protobuf wire-format message from b.
// Returns the number of bytes consumed.
// If lenient is true, duplicate non-repeated fields use last-one-wins.
// depth is the remaining nesting budget; callers pass runtime.DefaultRecursionLimit.
func (x *PersonCreate) unmarshalFrom(b []byte, lenient bool, depth int) (int, error) {
	if depth <= 0 {
		return 0, runtime.ErrNestingDepth
	}
	var seen [2]uint64
	off := 0
	for off < len(b) {
		fieldNum, wireType, n := runtime.ConsumeTag(b[off:])
		if n < 0 {
			if n == -2 {
				return 0, fmt.Errorf("field tag: %w", runtime.ErrOverflow)
			}
			return 0, fmt.Errorf("field tag: %w", runtime.ErrTruncated)
		}
		off += n

		switch fieldNum {
		case 1:
			if seen[0]&1 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 1: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 1
			if wireType != runtime.WireBytes {
				return 0, fmt.Errorf("field 1: %w", runtime.ErrWireType)
			}
			payload, n := runtime.ConsumeBytes(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 1: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 1: %w", runtime.ErrTruncated)
			}
			tmp := string(payload)
			x.Name = &tmp
			off += n
		case 2:
			if seen[0]&2 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 2: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 2
			if wireType != runtime.WireVarint {
				return 0, fmt.Errorf("field 2: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeVarint(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 2: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 2: %w", runtime.ErrTruncated)
			}
			tmp := int32(v)
			x.Age = &tmp
			off += n
		case 3:
			if seen[0]&4 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 3: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 4
			if wireType != runtime.WireVarint {
				return 0, fmt.Errorf("field 3: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeVarint(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 3: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 3: %w", runtime.ErrTruncated)
			}
			tmp := v != 0
			x.Active = &tmp
			off += n
		case 4:
			if seen[0]&8 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 4: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 8
			if wireType != runtime.WireVarint {
				return 0, fmt.Errorf("field 4: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeVarint(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 4: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 4: %w", runtime.ErrTruncated)
			}
			tmp := Status(v)
			x.Status = &tmp
			off += n
		case 5:
			if seen[0]&16 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 5: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 16
			if wireType != runtime.WireFixed32 {
				return 0, fmt.Errorf("field 5: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeFixed32(b[off:])
			if n < 0 {
				return 0, fmt.Errorf("field 5: %w", runtime.ErrTruncated)
			}
			tmp := math.Float32frombits(v)
			x.Rating = &tmp
			off += n
		case 6:
			if seen[0]&32 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 6: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 32
			if wireType != runtime.WireBytes {
				return 0, fmt.Errorf("field 6: %w", runtime.ErrWireType)
			}
			payload, n := runtime.ConsumeBytes(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 6: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 6: %w", runtime.ErrTruncated)
			}
			x.Nickname = string(payload)
			off += n
		case 7:
			if seen[0]&64 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 7: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 64
			if wireType != runtime.WireVarint {
				return 0, fmt.Errorf("field 7: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeVarint(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 7: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 7: %w", runtime.ErrTruncated)
			}
			tmp := int32(v)
			x.Level = &tmp
			off += n
		case 8:
			if seen[0]&128 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 8: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 128
			if wireType != runtime.WireVarint {
				return 0, fmt.Errorf("field 8: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeVarint(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 8: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 8: %w", runtime.ErrTruncated)
			}
			tmp := v != 0
			x.Verified = &tmp
			off += n
		case 9:
			if seen[0]&256 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 9: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 256
			if wireType != runtime.WireFixed32 {
				return 0, fmt.Errorf("field 9: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeFixed32(b[off:])
			if n < 0 {
				return 0, fmt.Errorf("field 9: %w", runtime.ErrTruncated)
			}
			tmp := math.Float32frombits(v)
			x.Score = &tmp
			off += n
		case 10:
			if seen[0]&512 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 10: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 512
			if wireType != runtime.WireVarint {
				return 0, fmt.Errorf("field 10: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeVarint(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 10: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 10: %w", runtime.ErrTruncated)
			}
			tmp := int64(v)
			x.UpdatedAt = &tmp
			off += n
		case 11:
			if seen[0]&1024 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 11: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 1024
			if wireType != runtime.WireVarint {
				return 0, fmt.Errorf("field 11: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeVarint(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 11: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 11: %w", runtime.ErrTruncated)
			}
			tmp := Status(v)
			x.PrevStatus = &tmp
			off += n
		case 12:
			if seen[0]&2048 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 12: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 2048
			if wireType != runtime.WireBytes {
				return 0, fmt.Errorf("field 12: %w", runtime.ErrWireType)
			}
			payload, n := runtime.ConsumeBytes(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 12: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 12: %w", runtime.ErrTruncated)
			}
			tmp := string(payload)
			x.Email = &tmp
			off += n
		case 13:
			if seen[0]&4096 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 13: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 4096
			if wireType != runtime.WireBytes {
				return 0, fmt.Errorf("field 13: %w", runtime.ErrWireType)
			}
			payload, n := runtime.ConsumeBytes(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 13: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 13: %w", runtime.ErrTruncated)
			}
			tmp := string(payload)
			x.Role = &tmp
			off += n
		case 14:
			if seen[0]&8192 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 14: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 8192
			if wireType != runtime.WireVarint {
				return 0, fmt.Errorf("field 14: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeVarint(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 14: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 14: %w", runtime.ErrTruncated)
			}
			tmp := int32(v)
			x.TypeId = &tmp
			off += n
		default:
			n = runtime.SkipField(b[off:], wireType)
			if n < 0 {
				if n == -3 {
					return 0, fmt.Errorf("unknown field %d: %w", fieldNum, runtime.ErrUnknownWireType)
				}
				return 0, fmt.Errorf("unknown field %d (wire type %d): %w", fieldNum, wireType, runtime.ErrTruncated)
			}
			off += n
		}
	}
	return off, nil
}

// UnmarshalBinary implements encoding.BinaryUnmarshaler.
// Duplicate non-repeated fields return an error.
func (x *PersonCreate) UnmarshalBinary(data []byte) error {
	_, err := x.unmarshalFrom(data, false, runtime.DefaultRecursionLimit)
	return err
}

// UnmarshalBinaryLenient unmarshals like UnmarshalBinary but allows
// duplicate non-repeated fields, keeping the last value.
func (x *PersonCreate) UnmarshalBinaryLenient(data []byte) error {
	_, err := x.unmarshalFrom(data, true, runtime.DefaultRecursionLimit)
	return err
}
