// Code generated by gcode. DO NOT EDIT.
// source: person.update.proto

package dao

import (
	"fmt"
	"github.com/pinealctx/gcode/runtime"
	"math"
)

type PersonUpdateByName struct {
	Name       string   `json:"name"`
	Age        *int32   `json:"age"`
	Active     *bool    `json:"active"`
	Status     *Status  `json:"status"`
	Rating     *float32 `json:"rating"`
	CreatedAt  *int64   `json:"createdAt"`
	Nickname   *string  `json:"nickname"`
	Level      *int32   `json:"level"`
	Verified   *bool    `json:"verified"`
	Score      *float32 `json:"score"`
	UpdatedAt  *int64   `json:"updatedAt"`
	PrevStatus *Status  `json:"prevStatus"`
	Email      *string  `json:"email"`
	Role       *string  `json:"role"`
	TypeId     *int32   `json:"typeId"`
}

// Size returns the protobuf wire size of PersonUpdateByName.
func (p *PersonUpdateByName) Size() int {
	if p == nil {
		return 0
	}
	var n int
	if len(p.Name) > 0 {
		n += 1 + runtime.SizeString(p.Name)
	}
	if p.Age != nil {
		n += 1 + runtime.SizeInt32(*p.Age)
	}
	if p.Active != nil {
		n += 1 + 1
	}
	if p.Status != nil {
		n += 1 + runtime.SizeEnum(int32(*p.Status))
	}
	if p.Rating != nil {
		n += 1 + 4
	}
	if p.CreatedAt != nil {
		n += 1 + runtime.SizeInt64(*p.CreatedAt)
	}
	if p.Nickname != nil {
		n += 1 + runtime.SizeString(*p.Nickname)
	}
	if p.Level != nil {
		n += 1 + runtime.SizeInt32(*p.Level)
	}
	if p.Verified != nil {
		n += 1 + 1
	}
	if p.Score != nil {
		n += 1 + 4
	}
	if p.UpdatedAt != nil {
		n += 1 + runtime.SizeInt64(*p.UpdatedAt)
	}
	if p.PrevStatus != nil {
		n += 1 + runtime.SizeEnum(int32(*p.PrevStatus))
	}
	if p.Email != nil {
		n += 1 + runtime.SizeString(*p.Email)
	}
	if p.Role != nil {
		n += 1 + runtime.SizeString(*p.Role)
	}
	if p.TypeId != nil {
		n += 1 + runtime.SizeInt32(*p.TypeId)
	}
	return n
}

// MarshalBinary implements encoding.BinaryMarshaler.
func (p *PersonUpdateByName) MarshalBinary() ([]byte, error) {
	return p.MarshalAppend(make([]byte, 0, p.Size()))
}

// MarshalAppend appends the protobuf wire encoding of PersonUpdateByName to b.
func (p *PersonUpdateByName) MarshalAppend(b []byte) ([]byte, error) {
	if len(p.Name) > 0 {
		b = runtime.AppendTag(b, 1, runtime.WireBytes)
		b = runtime.AppendString(b, p.Name)
	}
	if p.Age != nil {
		b = runtime.AppendTag(b, 2, runtime.WireVarint)
		b = runtime.AppendVarint(b, uint64(*p.Age))
	}
	if p.Active != nil {
		b = runtime.AppendTag(b, 3, runtime.WireVarint)
		b = runtime.AppendBool(b, *p.Active)
	}
	if p.Status != nil {
		b = runtime.AppendTag(b, 4, runtime.WireVarint)
		b = runtime.AppendVarint(b, uint64(*p.Status))
	}
	if p.Rating != nil {
		b = runtime.AppendTag(b, 5, runtime.WireFixed32)
		b = runtime.AppendFloat(b, *p.Rating)
	}
	if p.CreatedAt != nil {
		b = runtime.AppendTag(b, 6, runtime.WireVarint)
		b = runtime.AppendVarint(b, uint64(*p.CreatedAt))
	}
	if p.Nickname != nil {
		b = runtime.AppendTag(b, 7, runtime.WireBytes)
		b = runtime.AppendString(b, *p.Nickname)
	}
	if p.Level != nil {
		b = runtime.AppendTag(b, 8, runtime.WireVarint)
		b = runtime.AppendVarint(b, uint64(*p.Level))
	}
	if p.Verified != nil {
		b = runtime.AppendTag(b, 9, runtime.WireVarint)
		b = runtime.AppendBool(b, *p.Verified)
	}
	if p.Score != nil {
		b = runtime.AppendTag(b, 10, runtime.WireFixed32)
		b = runtime.AppendFloat(b, *p.Score)
	}
	if p.UpdatedAt != nil {
		b = runtime.AppendTag(b, 11, runtime.WireVarint)
		b = runtime.AppendVarint(b, uint64(*p.UpdatedAt))
	}
	if p.PrevStatus != nil {
		b = runtime.AppendTag(b, 12, runtime.WireVarint)
		b = runtime.AppendVarint(b, uint64(*p.PrevStatus))
	}
	if p.Email != nil {
		b = runtime.AppendTag(b, 13, runtime.WireBytes)
		b = runtime.AppendString(b, *p.Email)
	}
	if p.Role != nil {
		b = runtime.AppendTag(b, 14, runtime.WireBytes)
		b = runtime.AppendString(b, *p.Role)
	}
	if p.TypeId != nil {
		b = runtime.AppendTag(b, 15, runtime.WireVarint)
		b = runtime.AppendVarint(b, uint64(*p.TypeId))
	}
	return b, nil
}

// unmarshalFrom decodes a protobuf wire-format message from b.
// Returns the number of bytes consumed.
// If lenient is true, duplicate non-repeated fields use last-one-wins.
func (p *PersonUpdateByName) unmarshalFrom(b []byte, lenient bool) (int, error) {
	var seen [2]uint64
	off := 0
	for off < len(b) {
		fieldNum, wireType, n := runtime.ConsumeTag(b[off:])
		if n < 0 {
			if n == -2 {
				return 0, fmt.Errorf("field tag: %w", runtime.ErrOverflow)
			}
			return 0, fmt.Errorf("field tag: %w", runtime.ErrTruncated)
		}
		off += n

		switch fieldNum {
		case 1:
			if seen[0]&1 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 1: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 1
			if wireType != runtime.WireBytes {
				return 0, fmt.Errorf("field 1: %w", runtime.ErrWireType)
			}
			payload, n := runtime.ConsumeBytes(b[off:])
			if n < 0 {
				return 0, fmt.Errorf("field 1: %w", runtime.ErrTruncated)
			}
			p.Name = string(payload)
			off += n
		case 2:
			if seen[0]&2 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 2: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 2
			if wireType != runtime.WireVarint {
				return 0, fmt.Errorf("field 2: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeVarint(b[off:])
			if n < 0 {
				return 0, fmt.Errorf("field 2: %w", runtime.ErrTruncated)
			}
			tmp := int32(v)
			p.Age = &tmp
			off += n
		case 3:
			if seen[0]&4 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 3: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 4
			if wireType != runtime.WireVarint {
				return 0, fmt.Errorf("field 3: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeVarint(b[off:])
			if n < 0 {
				return 0, fmt.Errorf("field 3: %w", runtime.ErrTruncated)
			}
			tmp := v != 0
			p.Active = &tmp
			off += n
		case 4:
			if seen[0]&8 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 4: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 8
			if wireType != runtime.WireVarint {
				return 0, fmt.Errorf("field 4: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeVarint(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 4: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 4: %w", runtime.ErrTruncated)
			}
			tmp := Status(v)
			p.Status = &tmp
			off += n
		case 5:
			if seen[0]&16 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 5: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 16
			if wireType != runtime.WireFixed32 {
				return 0, fmt.Errorf("field 5: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeFixed32(b[off:])
			if n < 0 {
				return 0, fmt.Errorf("field 5: %w", runtime.ErrTruncated)
			}
			tmp := math.Float32frombits(v)
			p.Rating = &tmp
			off += n
		case 6:
			if seen[0]&32 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 6: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 32
			if wireType != runtime.WireVarint {
				return 0, fmt.Errorf("field 6: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeVarint(b[off:])
			if n < 0 {
				return 0, fmt.Errorf("field 6: %w", runtime.ErrTruncated)
			}
			tmp := int64(v)
			p.CreatedAt = &tmp
			off += n
		case 7:
			if seen[0]&64 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 7: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 64
			if wireType != runtime.WireBytes {
				return 0, fmt.Errorf("field 7: %w", runtime.ErrWireType)
			}
			payload, n := runtime.ConsumeBytes(b[off:])
			if n < 0 {
				return 0, fmt.Errorf("field 7: %w", runtime.ErrTruncated)
			}
			tmp := string(payload)
			p.Nickname = &tmp
			off += n
		case 8:
			if seen[0]&128 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 8: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 128
			if wireType != runtime.WireVarint {
				return 0, fmt.Errorf("field 8: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeVarint(b[off:])
			if n < 0 {
				return 0, fmt.Errorf("field 8: %w", runtime.ErrTruncated)
			}
			tmp := int32(v)
			p.Level = &tmp
			off += n
		case 9:
			if seen[0]&256 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 9: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 256
			if wireType != runtime.WireVarint {
				return 0, fmt.Errorf("field 9: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeVarint(b[off:])
			if n < 0 {
				return 0, fmt.Errorf("field 9: %w", runtime.ErrTruncated)
			}
			tmp := v != 0
			p.Verified = &tmp
			off += n
		case 10:
			if seen[0]&512 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 10: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 512
			if wireType != runtime.WireFixed32 {
				return 0, fmt.Errorf("field 10: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeFixed32(b[off:])
			if n < 0 {
				return 0, fmt.Errorf("field 10: %w", runtime.ErrTruncated)
			}
			tmp := math.Float32frombits(v)
			p.Score = &tmp
			off += n
		case 11:
			if seen[0]&1024 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 11: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 1024
			if wireType != runtime.WireVarint {
				return 0, fmt.Errorf("field 11: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeVarint(b[off:])
			if n < 0 {
				return 0, fmt.Errorf("field 11: %w", runtime.ErrTruncated)
			}
			tmp := int64(v)
			p.UpdatedAt = &tmp
			off += n
		case 12:
			if seen[0]&2048 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 12: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 2048
			if wireType != runtime.WireVarint {
				return 0, fmt.Errorf("field 12: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeVarint(b[off:])
			if n < 0 {
				if n == -2 {
					return 0, fmt.Errorf("field 12: %w", runtime.ErrOverflow)
				}
				return 0, fmt.Errorf("field 12: %w", runtime.ErrTruncated)
			}
			tmp := Status(v)
			p.PrevStatus = &tmp
			off += n
		case 13:
			if seen[0]&4096 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 13: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 4096
			if wireType != runtime.WireBytes {
				return 0, fmt.Errorf("field 13: %w", runtime.ErrWireType)
			}
			payload, n := runtime.ConsumeBytes(b[off:])
			if n < 0 {
				return 0, fmt.Errorf("field 13: %w", runtime.ErrTruncated)
			}
			tmp := string(payload)
			p.Email = &tmp
			off += n
		case 14:
			if seen[0]&8192 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 14: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 8192
			if wireType != runtime.WireBytes {
				return 0, fmt.Errorf("field 14: %w", runtime.ErrWireType)
			}
			payload, n := runtime.ConsumeBytes(b[off:])
			if n < 0 {
				return 0, fmt.Errorf("field 14: %w", runtime.ErrTruncated)
			}
			tmp := string(payload)
			p.Role = &tmp
			off += n
		case 15:
			if seen[0]&16384 != 0 {
				if !lenient {
					return 0, fmt.Errorf("field 15: %w", runtime.ErrDuplicateField)
				}
			}
			seen[0] |= 16384
			if wireType != runtime.WireVarint {
				return 0, fmt.Errorf("field 15: %w", runtime.ErrWireType)
			}
			v, n := runtime.ConsumeVarint(b[off:])
			if n < 0 {
				return 0, fmt.Errorf("field 15: %w", runtime.ErrTruncated)
			}
			tmp := int32(v)
			p.TypeId = &tmp
			off += n
		default:
			n = runtime.SkipField(b[off:], wireType)
			if n < 0 {
				return 0, fmt.Errorf("unknown field %d: %w", fieldNum, runtime.ErrTruncated)
			}
			off += n
		}
	}
	return off, nil
}

// UnmarshalBinary implements encoding.BinaryUnmarshaler.
// Duplicate non-repeated fields return an error.
func (p *PersonUpdateByName) UnmarshalBinary(data []byte) error {
	_, err := p.unmarshalFrom(data, false)
	return err
}

// UnmarshalBinaryLenient unmarshals like UnmarshalBinary but allows
// duplicate non-repeated fields, keeping the last value.
func (p *PersonUpdateByName) UnmarshalBinaryLenient(data []byte) error {
	_, err := p.unmarshalFrom(data, true)
	return err
}

// ToMap converts PersonUpdateByName to map[string]any for partial update APIs (e.g. GORM Updates).
// Only non-nil fields are included.
func (p *PersonUpdateByName) ToMap() map[string]any {
	um := make(map[string]any)
	if p.Age != nil {
		um["age"] = *p.Age
	}
	if p.Active != nil {
		um["active"] = *p.Active
	}
	if p.Status != nil {
		um["status"] = *p.Status
	}
	if p.Rating != nil {
		um["rating"] = *p.Rating
	}
	if p.CreatedAt != nil {
		um["created_ts"] = *p.CreatedAt
	}
	if p.Nickname != nil {
		um["nickname"] = *p.Nickname
	}
	if p.Level != nil {
		um["level"] = *p.Level
	}
	if p.Verified != nil {
		um["verified"] = *p.Verified
	}
	if p.Score != nil {
		um["score"] = *p.Score
	}
	if p.UpdatedAt != nil {
		um["updated_at"] = *p.UpdatedAt
	}
	if p.PrevStatus != nil {
		um["prev_status"] = *p.PrevStatus
	}
	if p.Email != nil {
		um["email"] = *p.Email
	}
	if p.Role != nil {
		um["role"] = *p.Role
	}
	if p.TypeId != nil {
		um["type_id"] = *p.TypeId
	}
	return um
}
