// Code generated by gcode. DO NOT EDIT.
// source: person_service.proto

package dao

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/pinealctx/gcode/httpruntime"
)

// CreatePerson creates a new person record.
func CreatePersonHandler(svc PersonService) gin.HandlerFunc {
	return func(c *gin.Context) {
		var req PersonCreate
		if err := c.ShouldBind(&req); err != nil {
			_ = c.Error(err)
			return
		}
		if err := req.Validate(); err != nil {
			_ = c.Error(err)
			return
		}
		resp, err := svc.CreatePerson(c.Request.Context(), &req)
		if err != nil {
			_ = c.Error(err)
			return
		}
		c.JSON(http.StatusOK, httpruntime.OKResponse(resp))
	}
}

func GetPersonHandler(svc PersonService) gin.HandlerFunc {
	return func(c *gin.Context) {
		var req GetPersonRequest
		if err := c.ShouldBind(&req); err != nil {
			_ = c.Error(err)
			return
		}
		if err := req.Validate(); err != nil {
			_ = c.Error(err)
			return
		}
		resp, err := svc.GetPerson(c.Request.Context(), &req)
		if err != nil {
			_ = c.Error(err)
			return
		}
		c.JSON(http.StatusOK, httpruntime.OKResponse(resp))
	}
}

// UpdatePerson updates an existing person record by name.
func UpdatePersonHandler(svc PersonService) gin.HandlerFunc {
	return func(c *gin.Context) {
		var req PersonUpdateByName
		if err := c.ShouldBind(&req); err != nil {
			_ = c.Error(err)
			return
		}
		if err := req.Validate(); err != nil {
			_ = c.Error(err)
			return
		}
		resp, err := svc.UpdatePerson(c.Request.Context(), &req)
		if err != nil {
			_ = c.Error(err)
			return
		}
		c.JSON(http.StatusOK, httpruntime.OKResponse(resp))
	}
}

func DeletePersonHandler(svc PersonService) gin.HandlerFunc {
	return func(c *gin.Context) {
		var req DeletePersonRequest
		if err := c.ShouldBind(&req); err != nil {
			_ = c.Error(err)
			return
		}
		if err := req.Validate(); err != nil {
			_ = c.Error(err)
			return
		}
		resp, err := svc.DeletePerson(c.Request.Context(), &req)
		if err != nil {
			_ = c.Error(err)
			return
		}
		c.JSON(http.StatusOK, httpruntime.OKResponse(resp))
	}
}
