// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: all_types.proto

package pbgo

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/pinealctx/gcode/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AllScalars covers every scalar wire type not present in person.proto.
type AllScalars struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	FSint32   int32                  `protobuf:"zigzag32,1,opt,name=f_sint32,json=fSint32,proto3" json:"f_sint32,omitempty"`
	FSint64   int64                  `protobuf:"zigzag64,2,opt,name=f_sint64,json=fSint64,proto3" json:"f_sint64,omitempty"`
	FSfixed32 int32                  `protobuf:"fixed32,3,opt,name=f_sfixed32,json=fSfixed32,proto3" json:"f_sfixed32,omitempty"`
	FSfixed64 int64                  `protobuf:"fixed64,4,opt,name=f_sfixed64,json=fSfixed64,proto3" json:"f_sfixed64,omitempty"`
	FDouble   float64                `protobuf:"fixed64,5,opt,name=f_double,json=fDouble,proto3" json:"f_double,omitempty"`
	FFixed32  uint32                 `protobuf:"fixed32,6,opt,name=f_fixed32,json=fFixed32,proto3" json:"f_fixed32,omitempty"`
	FFixed64  uint64                 `protobuf:"fixed64,7,opt,name=f_fixed64,json=fFixed64,proto3" json:"f_fixed64,omitempty"`
	FUint32   uint32                 `protobuf:"varint,8,opt,name=f_uint32,json=fUint32,proto3" json:"f_uint32,omitempty"`
	FUint64   uint64                 `protobuf:"varint,9,opt,name=f_uint64,json=fUint64,proto3" json:"f_uint64,omitempty"`
	// float scalar: covers AppendFloat/IsZeroFloat/SizeFloat paths distinct from double.
	FFloat float32 `protobuf:"fixed32,10,opt,name=f_float,json=fFloat,proto3" json:"f_float,omitempty"`
	// bytes scalar: covers bytes two-phase generation path (bytes in update/create proto).
	FBytes        []byte `protobuf:"bytes,11,opt,name=f_bytes,json=fBytes,proto3" json:"f_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllScalars) Reset() {
	*x = AllScalars{}
	mi := &file_all_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllScalars) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllScalars) ProtoMessage() {}

func (x *AllScalars) ProtoReflect() protoreflect.Message {
	mi := &file_all_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllScalars.ProtoReflect.Descriptor instead.
func (*AllScalars) Descriptor() ([]byte, []int) {
	return file_all_types_proto_rawDescGZIP(), []int{0}
}

func (x *AllScalars) GetFSint32() int32 {
	if x != nil {
		return x.FSint32
	}
	return 0
}

func (x *AllScalars) GetFSint64() int64 {
	if x != nil {
		return x.FSint64
	}
	return 0
}

func (x *AllScalars) GetFSfixed32() int32 {
	if x != nil {
		return x.FSfixed32
	}
	return 0
}

func (x *AllScalars) GetFSfixed64() int64 {
	if x != nil {
		return x.FSfixed64
	}
	return 0
}

func (x *AllScalars) GetFDouble() float64 {
	if x != nil {
		return x.FDouble
	}
	return 0
}

func (x *AllScalars) GetFFixed32() uint32 {
	if x != nil {
		return x.FFixed32
	}
	return 0
}

func (x *AllScalars) GetFFixed64() uint64 {
	if x != nil {
		return x.FFixed64
	}
	return 0
}

func (x *AllScalars) GetFUint32() uint32 {
	if x != nil {
		return x.FUint32
	}
	return 0
}

func (x *AllScalars) GetFUint64() uint64 {
	if x != nil {
		return x.FUint64
	}
	return 0
}

func (x *AllScalars) GetFFloat() float32 {
	if x != nil {
		return x.FFloat
	}
	return 0
}

func (x *AllScalars) GetFBytes() []byte {
	if x != nil {
		return x.FBytes
	}
	return nil
}

// AllRepeated covers repeated field wire types not present in person.proto.
type AllRepeated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RSint32       []int32                `protobuf:"zigzag32,1,rep,packed,name=r_sint32,json=rSint32,proto3" json:"r_sint32,omitempty"`
	RSfixed32     []int32                `protobuf:"fixed32,2,rep,packed,name=r_sfixed32,json=rSfixed32,proto3" json:"r_sfixed32,omitempty"`
	RDouble       []float64              `protobuf:"fixed64,3,rep,packed,name=r_double,json=rDouble,proto3" json:"r_double,omitempty"`
	RBytes        [][]byte               `protobuf:"bytes,4,rep,name=r_bytes,json=rBytes,proto3" json:"r_bytes,omitempty"`
	RMessage      []*Address             `protobuf:"bytes,5,rep,name=r_message,json=rMessage,proto3" json:"r_message,omitempty"`
	REnum         []Status               `protobuf:"varint,6,rep,packed,name=r_enum,json=rEnum,proto3,enum=compat.Status" json:"r_enum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllRepeated) Reset() {
	*x = AllRepeated{}
	mi := &file_all_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllRepeated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllRepeated) ProtoMessage() {}

func (x *AllRepeated) ProtoReflect() protoreflect.Message {
	mi := &file_all_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllRepeated.ProtoReflect.Descriptor instead.
func (*AllRepeated) Descriptor() ([]byte, []int) {
	return file_all_types_proto_rawDescGZIP(), []int{1}
}

func (x *AllRepeated) GetRSint32() []int32 {
	if x != nil {
		return x.RSint32
	}
	return nil
}

func (x *AllRepeated) GetRSfixed32() []int32 {
	if x != nil {
		return x.RSfixed32
	}
	return nil
}

func (x *AllRepeated) GetRDouble() []float64 {
	if x != nil {
		return x.RDouble
	}
	return nil
}

func (x *AllRepeated) GetRBytes() [][]byte {
	if x != nil {
		return x.RBytes
	}
	return nil
}

func (x *AllRepeated) GetRMessage() []*Address {
	if x != nil {
		return x.RMessage
	}
	return nil
}

func (x *AllRepeated) GetREnum() []Status {
	if x != nil {
		return x.REnum
	}
	return nil
}

// AllValidate covers validate constraint types not present in person.proto.
type AllValidate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UGte          uint32                 `protobuf:"varint,1,opt,name=u_gte,json=uGte,proto3" json:"u_gte,omitempty"`
	ULte          uint64                 `protobuf:"varint,2,opt,name=u_lte,json=uLte,proto3" json:"u_lte,omitempty"`
	UIn           uint32                 `protobuf:"varint,3,opt,name=u_in,json=uIn,proto3" json:"u_in,omitempty"`
	UNotIn        uint32                 `protobuf:"varint,4,opt,name=u_not_in,json=uNotIn,proto3" json:"u_not_in,omitempty"`
	FGt           float32                `protobuf:"fixed32,5,opt,name=f_gt,json=fGt,proto3" json:"f_gt,omitempty"`
	DLte          float64                `protobuf:"fixed64,6,opt,name=d_lte,json=dLte,proto3" json:"d_lte,omitempty"`
	SIn           string                 `protobuf:"bytes,7,opt,name=s_in,json=sIn,proto3" json:"s_in,omitempty"`
	SNotIn        string                 `protobuf:"bytes,8,opt,name=s_not_in,json=sNotIn,proto3" json:"s_not_in,omitempty"`
	IIn           int32                  `protobuf:"varint,9,opt,name=i_in,json=iIn,proto3" json:"i_in,omitempty"`
	SUri          string                 `protobuf:"bytes,10,opt,name=s_uri,json=sUri,proto3" json:"s_uri,omitempty"`
	OStatus       *Status                `protobuf:"varint,11,opt,name=o_status,json=oStatus,proto3,enum=compat.Status,oneof" json:"o_status,omitempty"`
	BMinmax       []byte                 `protobuf:"bytes,12,opt,name=b_minmax,json=bMinmax,proto3" json:"b_minmax,omitempty"`
	RItems        []int32                `protobuf:"varint,13,rep,packed,name=r_items,json=rItems,proto3" json:"r_items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllValidate) Reset() {
	*x = AllValidate{}
	mi := &file_all_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllValidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllValidate) ProtoMessage() {}

func (x *AllValidate) ProtoReflect() protoreflect.Message {
	mi := &file_all_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllValidate.ProtoReflect.Descriptor instead.
func (*AllValidate) Descriptor() ([]byte, []int) {
	return file_all_types_proto_rawDescGZIP(), []int{2}
}

func (x *AllValidate) GetUGte() uint32 {
	if x != nil {
		return x.UGte
	}
	return 0
}

func (x *AllValidate) GetULte() uint64 {
	if x != nil {
		return x.ULte
	}
	return 0
}

func (x *AllValidate) GetUIn() uint32 {
	if x != nil {
		return x.UIn
	}
	return 0
}

func (x *AllValidate) GetUNotIn() uint32 {
	if x != nil {
		return x.UNotIn
	}
	return 0
}

func (x *AllValidate) GetFGt() float32 {
	if x != nil {
		return x.FGt
	}
	return 0
}

func (x *AllValidate) GetDLte() float64 {
	if x != nil {
		return x.DLte
	}
	return 0
}

func (x *AllValidate) GetSIn() string {
	if x != nil {
		return x.SIn
	}
	return ""
}

func (x *AllValidate) GetSNotIn() string {
	if x != nil {
		return x.SNotIn
	}
	return ""
}

func (x *AllValidate) GetIIn() int32 {
	if x != nil {
		return x.IIn
	}
	return 0
}

func (x *AllValidate) GetSUri() string {
	if x != nil {
		return x.SUri
	}
	return ""
}

func (x *AllValidate) GetOStatus() Status {
	if x != nil && x.OStatus != nil {
		return *x.OStatus
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *AllValidate) GetBMinmax() []byte {
	if x != nil {
		return x.BMinmax
	}
	return nil
}

func (x *AllValidate) GetRItems() []int32 {
	if x != nil {
		return x.RItems
	}
	return nil
}

var File_all_types_proto protoreflect.FileDescriptor

const file_all_types_proto_rawDesc = "" +
	"\n" +
	"\x0fall_types.proto\x12\x06compat\x1a\x1bbuf/validate/validate.proto\x1a\x13gcode/options.proto\x1a\fperson.proto\"\xa7\x03\n" +
	"\n" +
	"AllScalars\x12\x19\n" +
	"\bf_sint32\x18\x01 \x01(\x11R\afSint32\x12\x19\n" +
	"\bf_sint64\x18\x02 \x01(\x12R\afSint64\x12\x1d\n" +
	"\n" +
	"f_sfixed32\x18\x03 \x01(\x0fR\tfSfixed32\x12\x1d\n" +
	"\n" +
	"f_sfixed64\x18\x04 \x01(\x10R\tfSfixed64\x12\x19\n" +
	"\bf_double\x18\x05 \x01(\x01R\afDouble\x12\x1b\n" +
	"\tf_fixed32\x18\x06 \x01(\aR\bfFixed32\x12\x1b\n" +
	"\tf_fixed64\x18\a \x01(\x06R\bfFixed64\x12\x19\n" +
	"\bf_uint32\x18\b \x01(\rR\afUint32\x12\x19\n" +
	"\bf_uint64\x18\t \x01(\x04R\afUint64\x12\x17\n" +
	"\af_float\x18\n" +
	" \x01(\x02R\x06fFloat\x12,\n" +
	"\af_bytes\x18\v \x01(\fB\x13\x92\xb5\x18\x0f\n" +
	"\r\n" +
	"\vf_bytes_colR\x06fBytes:S\x8a\xb5\x18\x0f\n" +
	"\r\n" +
	"\vall_scalars\x9a\xb5\x18\x1c\n" +
	"\x10AllScalarsUpdate\x12\bf_sint32\xa2\xb5\x18\x1c\n" +
	"\x10AllScalarsCreate\x12\bf_double\"\xd0\x01\n" +
	"\vAllRepeated\x12\x19\n" +
	"\br_sint32\x18\x01 \x03(\x11R\arSint32\x12\x1d\n" +
	"\n" +
	"r_sfixed32\x18\x02 \x03(\x0fR\trSfixed32\x12\x19\n" +
	"\br_double\x18\x03 \x03(\x01R\arDouble\x12\x17\n" +
	"\ar_bytes\x18\x04 \x03(\fR\x06rBytes\x12,\n" +
	"\tr_message\x18\x05 \x03(\v2\x0f.compat.AddressR\brMessage\x12%\n" +
	"\x06r_enum\x18\x06 \x03(\x0e2\x0e.compat.StatusR\x05rEnum\"\xf7\x03\n" +
	"\vAllValidate\x12\x1c\n" +
	"\x05u_gte\x18\x01 \x01(\rB\a\xbaH\x04*\x02(\x01R\x04uGte\x12\x1d\n" +
	"\x05u_lte\x18\x02 \x01(\x04B\b\xbaH\x052\x03\x18\xe8\aR\x04uLte\x12\x1e\n" +
	"\x04u_in\x18\x03 \x01(\rB\v\xbaH\b*\x060\x010\x020\x03R\x03uIn\x12!\n" +
	"\bu_not_in\x18\x04 \x01(\rB\a\xbaH\x04*\x028\x00R\x06uNotIn\x12\x1d\n" +
	"\x04f_gt\x18\x05 \x01(\x02B\n" +
	"\xbaH\a\n" +
	"\x05%\x00\x00\x00\x00R\x03fGt\x12#\n" +
	"\x05d_lte\x18\x06 \x01(\x01B\x0e\xbaH\v\x12\t\x19\x00\x00\x00\x00\x00\x00\xf0?R\x04dLte\x12!\n" +
	"\x04s_in\x18\a \x01(\tB\x0e\xbaH\vr\tR\x01aR\x01bR\x01cR\x03sIn\x12%\n" +
	"\bs_not_in\x18\b \x01(\tB\v\xbaH\br\x06Z\x01xZ\x01yR\x06sNotIn\x12'\n" +
	"\x04i_in\x18\t \x01(\x05B\x14\xbaH\x11\x1a\x0f0\x010\x020\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01R\x03iIn\x12\x1d\n" +
	"\x05s_uri\x18\n" +
	" \x01(\tB\b\xbaH\x05r\x03\x88\x01\x01R\x04sUri\x128\n" +
	"\bo_status\x18\v \x01(\x0e2\x0e.compat.StatusB\b\xbaH\x05\x82\x01\x02\x10\x01H\x00R\aoStatus\x88\x01\x01\x12$\n" +
	"\bb_minmax\x18\f \x01(\fB\t\xbaH\x06z\x04\x10\x01\x18dR\abMinmax\x12%\n" +
	"\ar_items\x18\r \x03(\x05B\f\xbaH\t\x92\x01\x06\"\x04\x1a\x02(\x00R\x06rItemsB\v\n" +
	"\t_o_statusB4Z2github.com/pinealctx/gcode/testdata/compat/dao;daob\x06proto3"

var (
	file_all_types_proto_rawDescOnce sync.Once
	file_all_types_proto_rawDescData []byte
)

func file_all_types_proto_rawDescGZIP() []byte {
	file_all_types_proto_rawDescOnce.Do(func() {
		file_all_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_all_types_proto_rawDesc), len(file_all_types_proto_rawDesc)))
	})
	return file_all_types_proto_rawDescData
}

var file_all_types_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_all_types_proto_goTypes = []any{
	(*AllScalars)(nil),  // 0: compat.AllScalars
	(*AllRepeated)(nil), // 1: compat.AllRepeated
	(*AllValidate)(nil), // 2: compat.AllValidate
	(*Address)(nil),     // 3: compat.Address
	(Status)(0),         // 4: compat.Status
}
var file_all_types_proto_depIdxs = []int32{
	3, // 0: compat.AllRepeated.r_message:type_name -> compat.Address
	4, // 1: compat.AllRepeated.r_enum:type_name -> compat.Status
	4, // 2: compat.AllValidate.o_status:type_name -> compat.Status
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_all_types_proto_init() }
func file_all_types_proto_init() {
	if File_all_types_proto != nil {
		return
	}
	file_person_proto_init()
	file_all_types_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_all_types_proto_rawDesc), len(file_all_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_all_types_proto_goTypes,
		DependencyIndexes: file_all_types_proto_depIdxs,
		MessageInfos:      file_all_types_proto_msgTypes,
	}.Build()
	File_all_types_proto = out.File
	file_all_types_proto_goTypes = nil
	file_all_types_proto_depIdxs = nil
}
