package render

import (
	"strings"
	"testing"

	"github.com/pinealctx/gcode/internal/model"
	"github.com/pinealctx/gcode/internal/transform"
)

const testModulePath = "github.com/pinealctx/gcode"

func TestHTTPFileSingleServiceSingleRPC(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:  "user_service.proto",
		Package: "dao",
		Services: []transform.GoService{
			{
				GoName: "UserService",
				Methods: []transform.GoRPCMethod{
					{
						GoName:       "CreateUser",
						RequestType:  "CreateUserRequest",
						ResponseType: "CreateUserResponse",
					},
				},
			},
		},
	}

	got, err := HTTPFile(gf, testModulePath)
	if err != nil {
		t.Fatalf("HTTPFile() error: %v", err)
	}
	src := string(got)

	containsAll(t, src, map[string]string{
		"header":             "// Code generated by gcode. DO NOT EDIT.",
		"source":             "// source: user_service.proto",
		"package":            "package dao",
		"import gin":         `"github.com/gin-gonic/gin"`,
		"import handlerx":    `"github.com/pinealctx/x/handlerx"`,
		"import httpruntime": `"github.com/pinealctx/gcode/httpruntime"`,
		"handler func":       "func CreateUserHandler(svc UserService, interceptors ...handlerx.Interceptor[*CreateUserRequest, *CreateUserResponse]) gin.HandlerFunc",
		"NewHandler call":    "return httpruntime.NewHandler(svc.CreateUser, interceptors...)",
	})
}

func TestHTTPFileMultipleServicesMultipleRPCs(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:  "services.proto",
		Package: "dao",
		Services: []transform.GoService{
			{
				GoName: "UserService",
				Methods: []transform.GoRPCMethod{
					{GoName: "CreateUser", RequestType: "CreateUserRequest", ResponseType: "CreateUserResponse"},
					{GoName: "GetUser", RequestType: "GetUserRequest", ResponseType: "GetUserResponse"},
				},
			},
			{
				GoName: "OrderService",
				Methods: []transform.GoRPCMethod{
					{GoName: "PlaceOrder", RequestType: "PlaceOrderRequest", ResponseType: "PlaceOrderResponse"},
				},
			},
		},
	}

	got, err := HTTPFile(gf, testModulePath)
	if err != nil {
		t.Fatalf("HTTPFile() error: %v", err)
	}
	src := string(got)

	containsAll(t, src, map[string]string{
		"CreateUserHandler": "func CreateUserHandler(svc UserService, interceptors ...handlerx.Interceptor[*CreateUserRequest, *CreateUserResponse]) gin.HandlerFunc",
		"GetUserHandler":    "func GetUserHandler(svc UserService, interceptors ...handlerx.Interceptor[*GetUserRequest, *GetUserResponse]) gin.HandlerFunc",
		"PlaceOrderHandler": "func PlaceOrderHandler(svc OrderService, interceptors ...handlerx.Interceptor[*PlaceOrderRequest, *PlaceOrderResponse]) gin.HandlerFunc",
	})
}

func TestHTTPFileNoServicesEmptyBody(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:   "messages.proto",
		Package:  "dao",
		Services: nil,
	}

	got, err := HTTPFile(gf, testModulePath)
	if err != nil {
		t.Fatalf("HTTPFile() error: %v", err)
	}
	src := string(got)

	// Header and package present.
	containsAll(t, src, map[string]string{
		"header":  "// Code generated by gcode. DO NOT EDIT.",
		"package": "package dao",
	})
	// No handler functions generated.
	if strings.Contains(src, "HandlerFunc") {
		t.Errorf("expected no HandlerFunc for empty services, got:\n%s", src)
	}
}

func TestHTTPFileImportsPresent(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:  "svc.proto",
		Package: "mypkg",
		Services: []transform.GoService{
			{
				GoName: "FooService",
				Methods: []transform.GoRPCMethod{
					{GoName: "DoFoo", RequestType: "FooRequest", ResponseType: "FooResponse"},
				},
			},
		},
	}

	got, err := HTTPFile(gf, testModulePath)
	if err != nil {
		t.Fatalf("HTTPFile() error: %v", err)
	}
	src := string(got)

	for _, imp := range []string{
		`"github.com/gin-gonic/gin"`,
		`"github.com/pinealctx/x/handlerx"`,
		`"github.com/pinealctx/gcode/httpruntime"`,
	} {
		if !strings.Contains(src, imp) {
			t.Errorf("expected import %s in output:\n%s", imp, src)
		}
	}
	// net/http is no longer used directly in generated handlers.
	if strings.Contains(src, `"net/http"`) {
		t.Errorf("unexpected import \"net/http\" in output:\n%s", src)
	}
}

func TestHTTPFileHandlerSignatureFormat(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:  "svc.proto",
		Package: "dao",
		Services: []transform.GoService{
			{
				GoName: "PersonService",
				Methods: []transform.GoRPCMethod{
					{GoName: "GetPerson", RequestType: "GetPersonRequest", ResponseType: "GetPersonResponse"},
				},
			},
		},
	}

	got, err := HTTPFile(gf, testModulePath)
	if err != nil {
		t.Fatalf("HTTPFile() error: %v", err)
	}
	src := string(got)

	if !strings.Contains(src, "func GetPersonHandler(svc PersonService, interceptors ...handlerx.Interceptor[*GetPersonRequest, *GetPersonResponse]) gin.HandlerFunc") {
		t.Errorf("expected handler signature in output:\n%s", src)
	}
}

// TestHTTPFileHandlerDelegation verifies that the generated handler delegates to
// httpruntime.NewHandler and contains no inline bind/validate/error/response logic.
func TestHTTPFileHandlerDelegation(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:  "svc.proto",
		Package: "dao",
		Services: []transform.GoService{
			{
				GoName: "FooService",
				Methods: []transform.GoRPCMethod{
					{GoName: "DoFoo", RequestType: "FooRequest", ResponseType: "FooResponse"},
				},
			},
		},
	}

	got, err := HTTPFile(gf, testModulePath)
	if err != nil {
		t.Fatalf("HTTPFile() error: %v", err)
	}
	src := string(got)

	// Generated handler must delegate to NewHandler.
	if !strings.Contains(src, "httpruntime.NewHandler(svc.DoFoo, interceptors...)") {
		t.Errorf("expected NewHandler delegation in output:\n%s", src)
	}
	// Inline logic and direct response helpers must NOT appear — all handled inside NewHandler.
	for _, token := range []string{
		"ShouldBindJSON(",
		"req.Validate()",
		"c.Error(err)",
		"httpruntime.ErrResponse",
		"httpruntime.OKResponse",
	} {
		if strings.Contains(src, token) {
			t.Errorf("token %q should not appear in generated handler (delegated to NewHandler):\n%s", token, src)
		}
	}
}

func TestHTTPFileWithMethodComment(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:  "svc.proto",
		Package: "dao",
		Services: []transform.GoService{
			{
				GoName: "UserService",
				Methods: []transform.GoRPCMethod{
					{
						GoName:       "CreateUser",
						RequestType:  "CreateUserRequest",
						ResponseType: "CreateUserResponse",
						Comment:      model.Comment{Lines: []string{"CreateUser creates a new user."}},
					},
				},
			},
		},
	}

	got, err := HTTPFile(gf, testModulePath)
	if err != nil {
		t.Fatalf("HTTPFile() error: %v", err)
	}
	src := string(got)

	if !strings.Contains(src, "// CreateUser creates a new user.") {
		t.Errorf("expected method comment in output:\n%s", src)
	}
}

// TestHTTPFileServiceCommentNotWritten verifies that service-level comments are NOT
// written to the handler file. Handler functions have no service-level Go declaration
// to attach a doc comment to, so service comments are intentionally omitted.
func TestHTTPFileServiceCommentNotWritten(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:  "svc.proto",
		Package: "dao",
		Services: []transform.GoService{
			{
				GoName:  "UserService",
				Comment: model.Comment{Lines: []string{"UserService manages users."}},
				Methods: []transform.GoRPCMethod{
					{
						GoName:       "GetUser",
						RequestType:  "GetUserRequest",
						ResponseType: "GetUserResponse",
						Comment:      model.Comment{Lines: []string{"GetUser retrieves a user."}},
					},
				},
			},
		},
	}

	got, err := HTTPFile(gf, testModulePath)
	if err != nil {
		t.Fatalf("HTTPFile() error: %v", err)
	}
	src := string(got)

	// Service comment must NOT appear — no service-level declaration in handler file.
	if strings.Contains(src, "// UserService manages users.") {
		t.Errorf("service comment should not appear in handler file:\n%s", src)
	}
	// Method comment must appear; handler function must be generated.
	containsAll(t, src, map[string]string{
		"method comment": "// GetUser retrieves a user.",
		"handler func":   "func GetUserHandler(svc UserService, interceptors ...handlerx.Interceptor[*GetUserRequest, *GetUserResponse]) gin.HandlerFunc",
	})
}

// TestHTTPFileEmptyServicesSlice verifies that an empty (non-nil) Services slice
// behaves identically to nil — no handlers and no imports generated.
func TestHTTPFileEmptyServicesSlice(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:   "messages.proto",
		Package:  "dao",
		Services: []transform.GoService{},
	}

	got, err := HTTPFile(gf, testModulePath)
	if err != nil {
		t.Fatalf("HTTPFile() error: %v", err)
	}
	src := string(got)

	if strings.Contains(src, "HandlerFunc") {
		t.Errorf("expected no HandlerFunc for empty services slice, got:\n%s", src)
	}
	if strings.Contains(src, `"github.com/gin-gonic/gin"`) {
		t.Errorf("expected no gin import for empty services slice, got:\n%s", src)
	}
	if strings.Contains(src, `"github.com/pinealctx/gcode/httpruntime"`) {
		t.Errorf("expected no httpruntime import for empty services slice, got:\n%s", src)
	}
}
