package render

import (
	"strings"
	"testing"

	"github.com/pinealctx/gcode/internal/model"
	"github.com/pinealctx/gcode/internal/transform"
)

const testModulePath = "github.com/pinealctx/gcode"

func TestHTTPFileSingleServiceSingleRPC(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:  "user_service.proto",
		Package: "dao",
		Services: []transform.GoService{
			{
				GoName: "UserService",
				Methods: []transform.GoRPCMethod{
					{
						GoName:       "CreateUser",
						RequestType:  "CreateUserRequest",
						ResponseType: "CreateUserResponse",
					},
				},
			},
		},
	}

	got, err := HTTPFile(gf, testModulePath)
	if err != nil {
		t.Fatalf("HTTPFile() error: %v", err)
	}
	src := string(got)

	containsAll(t, src, map[string]string{
		"header":             "// Code generated by gcode. DO NOT EDIT.",
		"source":             "// source: user_service.proto",
		"package":            "package dao",
		"import gin":         `"github.com/gin-gonic/gin"`,
		"import httpruntime": `"github.com/pinealctx/gcode/httpruntime"`,
		"handler func":       "func CreateUserHandler(svc UserService) gin.HandlerFunc",
		"request context":    "c.Request.Context()",
	})
}

func TestHTTPFileMultipleServicesMultipleRPCs(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:  "services.proto",
		Package: "dao",
		Services: []transform.GoService{
			{
				GoName: "UserService",
				Methods: []transform.GoRPCMethod{
					{GoName: "CreateUser", RequestType: "CreateUserRequest", ResponseType: "CreateUserResponse"},
					{GoName: "GetUser", RequestType: "GetUserRequest", ResponseType: "GetUserResponse"},
				},
			},
			{
				GoName: "OrderService",
				Methods: []transform.GoRPCMethod{
					{GoName: "PlaceOrder", RequestType: "PlaceOrderRequest", ResponseType: "PlaceOrderResponse"},
				},
			},
		},
	}

	got, err := HTTPFile(gf, testModulePath)
	if err != nil {
		t.Fatalf("HTTPFile() error: %v", err)
	}
	src := string(got)

	containsAll(t, src, map[string]string{
		"CreateUserHandler": "func CreateUserHandler(svc UserService) gin.HandlerFunc",
		"GetUserHandler":    "func GetUserHandler(svc UserService) gin.HandlerFunc",
		"PlaceOrderHandler": "func PlaceOrderHandler(svc OrderService) gin.HandlerFunc",
	})
}

func TestHTTPFileNoServicesEmptyBody(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:   "messages.proto",
		Package:  "dao",
		Services: nil,
	}

	got, err := HTTPFile(gf, testModulePath)
	if err != nil {
		t.Fatalf("HTTPFile() error: %v", err)
	}
	src := string(got)

	// Header and package present.
	containsAll(t, src, map[string]string{
		"header":  "// Code generated by gcode. DO NOT EDIT.",
		"package": "package dao",
	})
	// No handler functions generated.
	if strings.Contains(src, "HandlerFunc") {
		t.Errorf("expected no HandlerFunc for empty services, got:\n%s", src)
	}
}

func TestHTTPFileImportsPresent(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:  "svc.proto",
		Package: "mypkg",
		Services: []transform.GoService{
			{
				GoName: "FooService",
				Methods: []transform.GoRPCMethod{
					{GoName: "DoFoo", RequestType: "FooRequest", ResponseType: "FooResponse"},
				},
			},
		},
	}

	got, err := HTTPFile(gf, testModulePath)
	if err != nil {
		t.Fatalf("HTTPFile() error: %v", err)
	}
	src := string(got)

	for _, imp := range []string{
		`"net/http"`,
		`"github.com/gin-gonic/gin"`,
		`"github.com/pinealctx/gcode/httpruntime"`,
	} {
		if !strings.Contains(src, imp) {
			t.Errorf("expected import %s in output:\n%s", imp, src)
		}
	}
}

func TestHTTPFileHandlerSignatureFormat(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:  "svc.proto",
		Package: "dao",
		Services: []transform.GoService{
			{
				GoName: "PersonService",
				Methods: []transform.GoRPCMethod{
					{GoName: "GetPerson", RequestType: "GetPersonRequest", ResponseType: "GetPersonResponse"},
				},
			},
		},
	}

	got, err := HTTPFile(gf, testModulePath)
	if err != nil {
		t.Fatalf("HTTPFile() error: %v", err)
	}
	src := string(got)

	if !strings.Contains(src, "func GetPersonHandler(svc PersonService) gin.HandlerFunc") {
		t.Errorf("expected handler signature in output:\n%s", src)
	}
}

// TestHTTPFileErrorPaths verifies that the generated handler contains the correct
// error-handling structure: ShouldBindJSON → req.Validate() → svc call, with all error
// paths using c.Error(err)+return (not ErrResponse), in the correct order.
func TestHTTPFileErrorPaths(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:  "svc.proto",
		Package: "dao",
		Services: []transform.GoService{
			{
				GoName: "FooService",
				Methods: []transform.GoRPCMethod{
					{GoName: "DoFoo", RequestType: "FooRequest", ResponseType: "FooResponse"},
				},
			},
		},
	}

	got, err := HTTPFile(gf, testModulePath)
	if err != nil {
		t.Fatalf("HTTPFile() error: %v", err)
	}
	src := string(got)

	// All three steps must be present.
	containsAll(t, src, map[string]string{
		"ShouldBindJSON": "ShouldBindJSON(",
		"req.Validate":   "req.Validate()",
		"c.Error":        "c.Error(err)",
	})
	// ErrResponse must NOT appear — errors are forwarded via c.Error.
	if strings.Contains(src, "httpruntime.ErrResponse") {
		t.Errorf("ErrResponse should not appear in generated handler (use c.Error instead):\n%s", src)
	}
	// Order: ShouldBindJSON < req.Validate() < svc call.
	// Search within the handler body (after the opening brace) to avoid matching
	// "svc" in the import path "github.com/pinealctx/gcode/httpruntime".
	handlerStart := strings.Index(src, "return func(c *gin.Context)")
	if handlerStart < 0 {
		t.Fatalf("handler body not found in:\n%s", src)
	}
	body := src[handlerStart:]
	bindPos := strings.Index(body, "ShouldBindJSON(")
	validatePos := strings.Index(body, "req.Validate()")
	svcPos := strings.Index(body, "svc.")
	if bindPos >= validatePos || validatePos >= svcPos {
		t.Errorf("expected order ShouldBindJSON(%d) < Validate(%d) < svc(%d) in handler body:\n%s",
			bindPos, validatePos, svcPos, body)
	}
}

func TestHTTPFileSuccessPath(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:  "svc.proto",
		Package: "dao",
		Services: []transform.GoService{
			{
				GoName: "FooService",
				Methods: []transform.GoRPCMethod{
					{GoName: "DoFoo", RequestType: "FooRequest", ResponseType: "FooResponse"},
				},
			},
		},
	}

	got, err := HTTPFile(gf, testModulePath)
	if err != nil {
		t.Fatalf("HTTPFile() error: %v", err)
	}
	src := string(got)

	// OKResponse must be present for success path.
	if !strings.Contains(src, "httpruntime.OKResponse(resp)") {
		t.Errorf("expected OKResponse in success path:\n%s", src)
	}
}

func TestHTTPFileWithMethodComment(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:  "svc.proto",
		Package: "dao",
		Services: []transform.GoService{
			{
				GoName: "UserService",
				Methods: []transform.GoRPCMethod{
					{
						GoName:       "CreateUser",
						RequestType:  "CreateUserRequest",
						ResponseType: "CreateUserResponse",
						Comment:      model.Comment{Lines: []string{"CreateUser creates a new user."}},
					},
				},
			},
		},
	}

	got, err := HTTPFile(gf, testModulePath)
	if err != nil {
		t.Fatalf("HTTPFile() error: %v", err)
	}
	src := string(got)

	if !strings.Contains(src, "// CreateUser creates a new user.") {
		t.Errorf("expected method comment in output:\n%s", src)
	}
}

// TestHTTPFileServiceCommentNotWritten verifies that service-level comments are NOT
// written to the handler file. Handler functions have no service-level Go declaration
// to attach a doc comment to, so service comments are intentionally omitted.
func TestHTTPFileServiceCommentNotWritten(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:  "svc.proto",
		Package: "dao",
		Services: []transform.GoService{
			{
				GoName:  "UserService",
				Comment: model.Comment{Lines: []string{"UserService manages users."}},
				Methods: []transform.GoRPCMethod{
					{
						GoName:       "GetUser",
						RequestType:  "GetUserRequest",
						ResponseType: "GetUserResponse",
						Comment:      model.Comment{Lines: []string{"GetUser retrieves a user."}},
					},
				},
			},
		},
	}

	got, err := HTTPFile(gf, testModulePath)
	if err != nil {
		t.Fatalf("HTTPFile() error: %v", err)
	}
	src := string(got)

	// Service comment must NOT appear — no service-level declaration in handler file.
	if strings.Contains(src, "// UserService manages users.") {
		t.Errorf("service comment should not appear in handler file:\n%s", src)
	}
	// Method comment must appear; handler function must be generated.
	containsAll(t, src, map[string]string{
		"method comment": "// GetUser retrieves a user.",
		"handler func":   "func GetUserHandler(svc UserService) gin.HandlerFunc",
	})
}

// TestHTTPFileEmptyServicesSlice verifies that an empty (non-nil) Services slice
// behaves identically to nil — no handlers and no imports generated.
func TestHTTPFileEmptyServicesSlice(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:   "messages.proto",
		Package:  "dao",
		Services: []transform.GoService{},
	}

	got, err := HTTPFile(gf, testModulePath)
	if err != nil {
		t.Fatalf("HTTPFile() error: %v", err)
	}
	src := string(got)

	if strings.Contains(src, "HandlerFunc") {
		t.Errorf("expected no HandlerFunc for empty services slice, got:\n%s", src)
	}
	if strings.Contains(src, `"github.com/gin-gonic/gin"`) {
		t.Errorf("expected no gin import for empty services slice, got:\n%s", src)
	}
	if strings.Contains(src, `"github.com/pinealctx/gcode/httpruntime"`) {
		t.Errorf("expected no httpruntime import for empty services slice, got:\n%s", src)
	}
}
