package render

import (
	"errors"
	"fmt"
	"strings"
	"testing"

	"github.com/pinealctx/gcode/internal/model"
	"github.com/pinealctx/gcode/internal/transform"
)

const testModule = "github.com/pinealctx/gcode"

// containsAll checks that src contains all the given substrings.
func containsAll(t *testing.T, src string, checks map[string]string) {
	t.Helper()
	for label, substr := range checks {
		if !strings.Contains(src, substr) {
			t.Errorf("missing %s: %q not found in output:\n%s", label, substr, src)
		}
	}
}

func TestFileBasic(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:  "person.proto",
		Package: "foopb",
		Messages: []transform.GoMessage{
			{
				GoName: "Person",
				Fields: []transform.GoField{
					{
						Field:  model.Field{Name: "name", Number: 1, Cardinality: model.CardinalitySingular, Type: model.FieldType{Kind: model.FieldKindScalar, Scalar: model.ScalarString}, JSONName: "name"},
						GoName: "Name", GoType: "string",
					},
					{
						Field:  model.Field{Name: "age", Number: 2, Cardinality: model.CardinalitySingular, Type: model.FieldType{Kind: model.FieldKindScalar, Scalar: model.ScalarInt32}, JSONName: "age"},
						GoName: "Age", GoType: "int32",
					},
				},
			},
		},
	}

	got, err := File(gf, testModule, Context{})
	if err != nil {
		t.Fatalf("File() error: %v", err)
	}

	src := string(got)

	containsAll(t, src, map[string]string{
		"header":  "// Code generated by gcode. DO NOT EDIT.",
		"source":  "// source: person.proto",
		"package": "package foopb",
		"struct":  "type Person struct",
		"name":    `json:"name"`,
		"age":     `json:"age"`,
	})

	// Verify field names and types are present.
	if !strings.Contains(src, "Name") || !strings.Contains(src, "string") {
		t.Error("missing Name string field")
	}
	if !strings.Contains(src, "Age") || !strings.Contains(src, "int32") {
		t.Error("missing Age int32 field")
	}

	// Verify marshal methods are generated.
	containsAll(t, src, map[string]string{
		"Size method":          "func (x *Person) Size() int",
		"MarshalBinary method": "func (x *Person) MarshalBinary() ([]byte, error)",
		"MarshalAppend method": "func (x *Person) MarshalAppend(b []byte) ([]byte, error)",
		"runtime import":       `"github.com/pinealctx/gcode/runtime"`,
	})
}

func TestFileEnum(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:  "status.proto",
		Package: "foopb",
		Enums: []transform.GoEnum{
			{
				GoName: "Status",
				Values: []transform.GoEnumValue{
					{GoName: "Status_STATUS_UNSPECIFIED", Number: 0},
					{GoName: "Status_STATUS_ACTIVE", Number: 1},
					{GoName: "Status_STATUS_INACTIVE", Number: 2},
				},
			},
		},
	}

	got, err := File(gf, testModule, Context{})
	if err != nil {
		t.Fatalf("File() error: %v", err)
	}

	src := string(got)

	containsAll(t, src, map[string]string{
		"type":        "type Status int32",
		"unspecified": "Status_STATUS_UNSPECIFIED",
		"active":      "Status_STATUS_ACTIVE",
		"inactive":    "Status_STATUS_INACTIVE",
	})

	// Enum-only file should not import runtime.
	if strings.Contains(src, "runtime") {
		t.Error("enum-only file should not import runtime")
	}
}

func TestFileWithComments(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:  "commented.proto",
		Package: "foopb",
		Messages: []transform.GoMessage{
			{
				GoName:  "Person",
				Comment: model.Comment{Lines: []string{"Person represents a human."}},
				Fields: []transform.GoField{
					{
						Field:  model.Field{Name: "name", Number: 1, Cardinality: model.CardinalitySingular, Type: model.FieldType{Kind: model.FieldKindScalar, Scalar: model.ScalarString}, JSONName: "name", LeadingComment: model.Comment{Lines: []string{"The person's full name."}}},
						GoName: "Name",
						GoType: "string",
					},
				},
			},
		},
	}

	got, err := File(gf, testModule, Context{})
	if err != nil {
		t.Fatalf("File() error: %v", err)
	}

	src := string(got)

	containsAll(t, src, map[string]string{
		"msg comment":   "// Person represents a human.",
		"field comment": "// The person's full name.",
	})
}

func TestFileWithMultiLineComment(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:  "multiline.proto",
		Package: "foopb",
		Messages: []transform.GoMessage{
			{
				GoName:  "Order",
				Comment: model.Comment{Lines: []string{"Order represents a purchase order.", "", "It contains line items and a total."}},
				Fields:  []transform.GoField{},
			},
		},
	}

	got, err := File(gf, testModule, Context{})
	if err != nil {
		t.Fatalf("File() error: %v", err)
	}
	src := string(got)

	containsAll(t, src, map[string]string{
		"first line": "// Order represents a purchase order.",
		"blank line": "//\n",
		"third line": "// It contains line items and a total.",
	})
}

func TestFileEnumWithComments(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:  "status.proto",
		Package: "foopb",
		Enums: []transform.GoEnum{
			{
				GoName:  "Status",
				Comment: model.Comment{Lines: []string{"Status represents the lifecycle state."}},
				Values: []transform.GoEnumValue{
					{GoName: "Status_UNKNOWN", Number: 0, Comment: model.Comment{Lines: []string{"UNKNOWN is the default unset value."}}},
					{GoName: "Status_ACTIVE", Number: 1},
				},
			},
		},
	}

	got, err := File(gf, testModule, Context{})
	if err != nil {
		t.Fatalf("File() error: %v", err)
	}
	src := string(got)

	containsAll(t, src, map[string]string{
		"enum comment":  "// Status represents the lifecycle state.",
		"value comment": "// UNKNOWN is the default unset value.",
	})
}

func TestFileStability(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:  "stable.proto",
		Package: "foopb",
		Messages: []transform.GoMessage{
			{
				GoName: "Msg",
				Fields: []transform.GoField{
					{
						Field:  model.Field{Name: "a", Number: 1, Cardinality: model.CardinalitySingular, Type: model.FieldType{Kind: model.FieldKindScalar, Scalar: model.ScalarString}, JSONName: "a"},
						GoName: "A", GoType: "string",
					},
					{
						Field:  model.Field{Name: "b", Number: 2, Cardinality: model.CardinalitySingular, Type: model.FieldType{Kind: model.FieldKindScalar, Scalar: model.ScalarInt32}, JSONName: "b"},
						GoName: "B", GoType: "int32",
					},
				},
			},
		},
		Enums: []transform.GoEnum{
			{
				GoName: "E",
				Values: []transform.GoEnumValue{
					{GoName: "E_X", Number: 0},
					{GoName: "E_Y", Number: 1},
				},
			},
		},
	}

	out1, err := File(gf, testModule, Context{})
	if err != nil {
		t.Fatalf("File() first call error: %v", err)
	}
	out2, err := File(gf, testModule, Context{})
	if err != nil {
		t.Fatalf("File() second call error: %v", err)
	}

	if string(out1) != string(out2) {
		t.Error("File() output is not stable across calls")
	}
}

func TestFileMarshalAllScalars(t *testing.T) {
	t.Parallel()

	// Test that marshal generation handles all scalar types.
	fields := []transform.GoField{
		{Field: model.Field{Name: "f_bool", Number: 1, Cardinality: model.CardinalitySingular, Type: model.FieldType{Kind: model.FieldKindScalar, Scalar: model.ScalarBool}, JSONName: "fBool"}, GoName: "FBool", GoType: "bool"},
		{Field: model.Field{Name: "f_int32", Number: 2, Cardinality: model.CardinalitySingular, Type: model.FieldType{Kind: model.FieldKindScalar, Scalar: model.ScalarInt32}, JSONName: "fInt32"}, GoName: "FInt32", GoType: "int32"},
		{Field: model.Field{Name: "f_int64", Number: 3, Cardinality: model.CardinalitySingular, Type: model.FieldType{Kind: model.FieldKindScalar, Scalar: model.ScalarInt64}, JSONName: "fInt64"}, GoName: "FInt64", GoType: "int64"},
		{Field: model.Field{Name: "f_uint32", Number: 4, Cardinality: model.CardinalitySingular, Type: model.FieldType{Kind: model.FieldKindScalar, Scalar: model.ScalarUint32}, JSONName: "fUint32"}, GoName: "FUint32", GoType: "uint32"},
		{Field: model.Field{Name: "f_uint64", Number: 5, Cardinality: model.CardinalitySingular, Type: model.FieldType{Kind: model.FieldKindScalar, Scalar: model.ScalarUint64}, JSONName: "fUint64"}, GoName: "FUint64", GoType: "uint64"},
		{Field: model.Field{Name: "f_sint32", Number: 6, Cardinality: model.CardinalitySingular, Type: model.FieldType{Kind: model.FieldKindScalar, Scalar: model.ScalarSint32}, JSONName: "fSint32"}, GoName: "FSint32", GoType: "int32"},
		{Field: model.Field{Name: "f_sint64", Number: 7, Cardinality: model.CardinalitySingular, Type: model.FieldType{Kind: model.FieldKindScalar, Scalar: model.ScalarSint64}, JSONName: "fSint64"}, GoName: "FSint64", GoType: "int64"},
		{Field: model.Field{Name: "f_fixed32", Number: 8, Cardinality: model.CardinalitySingular, Type: model.FieldType{Kind: model.FieldKindScalar, Scalar: model.ScalarFixed32}, JSONName: "fFixed32"}, GoName: "FFixed32", GoType: "uint32"},
		{Field: model.Field{Name: "f_fixed64", Number: 9, Cardinality: model.CardinalitySingular, Type: model.FieldType{Kind: model.FieldKindScalar, Scalar: model.ScalarFixed64}, JSONName: "fFixed64"}, GoName: "FFixed64", GoType: "uint64"},
		{Field: model.Field{Name: "f_sfixed32", Number: 10, Cardinality: model.CardinalitySingular, Type: model.FieldType{Kind: model.FieldKindScalar, Scalar: model.ScalarSfixed32}, JSONName: "fSfixed32"}, GoName: "FSfixed32", GoType: "int32"},
		{Field: model.Field{Name: "f_sfixed64", Number: 11, Cardinality: model.CardinalitySingular, Type: model.FieldType{Kind: model.FieldKindScalar, Scalar: model.ScalarSfixed64}, JSONName: "fSfixed64"}, GoName: "FSfixed64", GoType: "int64"},
		{Field: model.Field{Name: "f_float", Number: 12, Cardinality: model.CardinalitySingular, Type: model.FieldType{Kind: model.FieldKindScalar, Scalar: model.ScalarFloat}, JSONName: "fFloat"}, GoName: "FFloat", GoType: "float32"},
		{Field: model.Field{Name: "f_double", Number: 13, Cardinality: model.CardinalitySingular, Type: model.FieldType{Kind: model.FieldKindScalar, Scalar: model.ScalarDouble}, JSONName: "fDouble"}, GoName: "FDouble", GoType: "float64"},
		{Field: model.Field{Name: "f_string", Number: 14, Cardinality: model.CardinalitySingular, Type: model.FieldType{Kind: model.FieldKindScalar, Scalar: model.ScalarString}, JSONName: "fString"}, GoName: "FString", GoType: "string"},
		{Field: model.Field{Name: "f_bytes", Number: 15, Cardinality: model.CardinalitySingular, Type: model.FieldType{Kind: model.FieldKindScalar, Scalar: model.ScalarBytes}, JSONName: "fBytes"}, GoName: "FBytes", GoType: "[]byte"},
	}

	gf := transform.GoFile{
		Source:  "all_scalars.proto",
		Package: "foopb",
		Messages: []transform.GoMessage{
			{GoName: "AllScalars", Fields: fields},
		},
	}

	got, err := File(gf, testModule, Context{})
	if err != nil {
		t.Fatalf("File() error: %v", err)
	}

	src := string(got)

	// Verify the generated code contains Size, MarshalBinary, MarshalAppend.
	containsAll(t, src, map[string]string{
		"Size":          "func (x *AllScalars) Size() int",
		"MarshalBinary": "func (x *AllScalars) MarshalBinary() ([]byte, error)",
		"MarshalAppend": "func (x *AllScalars) MarshalAppend(b []byte) ([]byte, error)",
	})

	// Verify runtime calls for various wire types.
	containsAll(t, src, map[string]string{
		"varint":  "runtime.AppendVarint",
		"bool":    "runtime.AppendBool",
		"float":   "runtime.AppendFloat",
		"double":  "runtime.AppendDouble",
		"fixed32": "runtime.AppendFixed32",
		"fixed64": "runtime.AppendFixed64",
		"string":  "runtime.AppendString",
		"bytes":   "runtime.AppendBytes",
		"sint32":  "runtime.AppendSint32",
		"sint64":  "runtime.AppendSint64",
		"tag":     "runtime.AppendTag",
	})
}

func TestFileMarshalRepeatedPacked(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:  "repeated.proto",
		Package: "foopb",
		Messages: []transform.GoMessage{
			{
				GoName: "Container",
				Fields: []transform.GoField{
					{
						Field:  model.Field{Name: "ids", Number: 1, Cardinality: model.CardinalityRepeated, Type: model.FieldType{Kind: model.FieldKindScalar, Scalar: model.ScalarInt32}, JSONName: "ids"},
						GoName: "Ids", GoType: "[]int32", ElemGoType: "int32",
					},
					{
						Field:  model.Field{Name: "names", Number: 2, Cardinality: model.CardinalityRepeated, Type: model.FieldType{Kind: model.FieldKindScalar, Scalar: model.ScalarString}, JSONName: "names"},
						GoName: "Names", GoType: "[]string", ElemGoType: "string",
					},
				},
			},
		},
	}

	got, err := File(gf, testModule, Context{})
	if err != nil {
		t.Fatalf("File() error: %v", err)
	}

	src := string(got)

	// Packed repeated int32 should use WireBytes for the packed encoding.
	if !strings.Contains(src, "runtime.WireBytes") {
		t.Error("packed repeated should use WireBytes")
	}

	// Repeated string should use per-element tag+LEN.
	if !strings.Contains(src, "runtime.AppendString") {
		t.Error("repeated string should use AppendString")
	}
}

func TestFileUnmarshalMethods(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:  "person.proto",
		Package: "foopb",
		Messages: []transform.GoMessage{
			{
				GoName: "Person",
				Fields: []transform.GoField{
					{
						Field:  model.Field{Name: "name", Number: 1, Cardinality: model.CardinalitySingular, Type: model.FieldType{Kind: model.FieldKindScalar, Scalar: model.ScalarString}, JSONName: "name"},
						GoName: "Name", GoType: "string",
					},
					{
						Field:  model.Field{Name: "age", Number: 2, Cardinality: model.CardinalitySingular, Type: model.FieldType{Kind: model.FieldKindScalar, Scalar: model.ScalarInt32}, JSONName: "age"},
						GoName: "Age", GoType: "int32",
					},
				},
			},
		},
	}

	got, err := File(gf, testModule, Context{})
	if err != nil {
		t.Fatalf("File() error: %v", err)
	}

	src := string(got)

	containsAll(t, src, map[string]string{
		"unmarshalFrom":          "func (x *Person) unmarshalFrom(b []byte, lenient bool, depth int) (int, error)",
		"UnmarshalBinary":        "func (x *Person) UnmarshalBinary(data []byte) error",
		"UnmarshalBinaryLenient": "func (x *Person) UnmarshalBinaryLenient(data []byte) error",
		"ConsumeTag":             "runtime.ConsumeTag",
		"ConsumeVarint":          "runtime.ConsumeVarint",
		"ConsumeBytes":           "runtime.ConsumeBytes",
		"SkipField":              "runtime.SkipField",
		"ErrWireType":            "runtime.ErrWireType",
		"ErrTruncated":           "runtime.ErrTruncated",
		"fmt import":             `"fmt"`,
	})
}

func TestFileUnmarshalDuplicateTracking(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:  "dup.proto",
		Package: "foopb",
		Messages: []transform.GoMessage{
			{
				GoName: "Msg",
				Fields: []transform.GoField{
					{
						Field:  model.Field{Name: "x", Number: 1, Cardinality: model.CardinalitySingular, Type: model.FieldType{Kind: model.FieldKindScalar, Scalar: model.ScalarInt32}, JSONName: "x"},
						GoName: "X", GoType: "int32",
					},
				},
			},
		},
	}

	got, err := File(gf, testModule, Context{})
	if err != nil {
		t.Fatalf("File() error: %v", err)
	}

	src := string(got)

	// Strict mode should check for duplicates.
	containsAll(t, src, map[string]string{
		"seen bitmap":     "var seen [2]uint64",
		"duplicate check": "runtime.ErrDuplicateField",
		"lenient check":   "!lenient",
	})
}

func TestFileTooManyNonRepeatedFields(t *testing.T) {
	t.Parallel()

	// Build a message with 129 non-repeated fields — must exceed the 128-field limit.
	fields := make([]transform.GoField, 129)
	for i := range fields {
		fields[i] = transform.GoField{
			Field:  model.Field{Name: fmt.Sprintf("f%d", i+1), Number: i + 1, Cardinality: model.CardinalitySingular, Type: model.FieldType{Kind: model.FieldKindScalar, Scalar: model.ScalarInt32}, JSONName: fmt.Sprintf("f%d", i+1)},
			GoName: fmt.Sprintf("F%d", i+1), GoType: "int32",
		}
	}
	gf := transform.GoFile{
		Source:  "big.proto",
		Package: "foopb",
		Messages: []transform.GoMessage{
			{GoName: "Big", Fields: fields},
		},
	}

	_, err := File(gf, testModule, Context{})
	if err == nil {
		t.Fatal("File() expected error for >128 non-repeated fields, got nil")
	}
	if !errors.Is(err, ErrTooManyFields) {
		t.Fatalf("expected ErrTooManyFields, got: %v", err)
	}
}

func TestFileUnmarshalRepeatedPacked(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:  "repeated.proto",
		Package: "foopb",
		Messages: []transform.GoMessage{
			{
				GoName: "Container",
				Fields: []transform.GoField{
					{
						Field:  model.Field{Name: "ids", Number: 1, Cardinality: model.CardinalityRepeated, Type: model.FieldType{Kind: model.FieldKindScalar, Scalar: model.ScalarInt32}, JSONName: "ids"},
						GoName: "Ids", GoType: "[]int32", ElemGoType: "int32",
					},
					{
						Field:  model.Field{Name: "names", Number: 2, Cardinality: model.CardinalityRepeated, Type: model.FieldType{Kind: model.FieldKindScalar, Scalar: model.ScalarString}, JSONName: "names"},
						GoName: "Names", GoType: "[]string", ElemGoType: "string",
					},
				},
			},
		},
	}

	got, err := File(gf, testModule, Context{})
	if err != nil {
		t.Fatalf("File() error: %v", err)
	}

	src := string(got)

	// Packed repeated int32: must require WireBytes and iterate packed payload.
	containsAll(t, src, map[string]string{
		"packed wire check": "runtime.WireBytes",
		"packed loop":       "ConsumeBytes",
		"append ids":        "append(x.Ids",
		"append names":      "append(x.Names",
	})

	// Repeated scalars should NOT have a seen/duplicate check.
	if strings.Contains(src, "var seen") {
		t.Error("repeated-only message should not have seen bitmap")
	}
}

func TestFileUnmarshalFloat(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:  "floats.proto",
		Package: "foopb",
		Messages: []transform.GoMessage{
			{
				GoName: "Floats",
				Fields: []transform.GoField{
					{
						Field:  model.Field{Name: "f", Number: 1, Cardinality: model.CardinalitySingular, Type: model.FieldType{Kind: model.FieldKindScalar, Scalar: model.ScalarFloat}, JSONName: "f"},
						GoName: "F", GoType: "float32",
					},
					{
						Field:  model.Field{Name: "d", Number: 2, Cardinality: model.CardinalitySingular, Type: model.FieldType{Kind: model.FieldKindScalar, Scalar: model.ScalarDouble}, JSONName: "d"},
						GoName: "D", GoType: "float64",
					},
				},
			},
		},
	}

	got, err := File(gf, testModule, Context{})
	if err != nil {
		t.Fatalf("File() error: %v", err)
	}

	src := string(got)

	// Float fields require math package.
	containsAll(t, src, map[string]string{
		"math import":     `"math"`,
		"fmt import":      `"fmt"`,
		"Float32frombits": "math.Float32frombits",
		"Float64frombits": "math.Float64frombits",
	})
}

// --- Deviation tests (template layer) ---

// TestDeviationPackedOnlyEnforced verifies that the generated unmarshal template
// for a packed repeated scalar field checks for WireBytes and rejects other wire types.
func TestDeviationPackedOnlyEnforced(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:  "packed.proto",
		Package: "foopb",
		Messages: []transform.GoMessage{
			{
				GoName: "Msg",
				Fields: []transform.GoField{
					{
						Field:  model.Field{Name: "ids", Number: 1, Cardinality: model.CardinalityRepeated, Type: model.FieldType{Kind: model.FieldKindScalar, Scalar: model.ScalarInt32}, JSONName: "ids"},
						GoName: "Ids", GoType: "[]int32", ElemGoType: "int32",
					},
				},
			},
		},
	}

	got, err := File(gf, testModule, Context{})
	if err != nil {
		t.Fatalf("File() error: %v", err)
	}
	src := string(got)

	// The generated unmarshal code must require WireBytes for packed repeated int32.
	// Any other wire type must return ErrWireType.
	containsAll(t, src, map[string]string{
		"packed wire check": "runtime.WireBytes",
		"wire type error":   "runtime.ErrWireType",
	})

	// Must NOT accept WireVarint for this field (no unpacked path).
	if strings.Contains(src, "WireVarint") {
		// WireVarint may appear in other contexts (e.g. tag decode), but the
		// field-specific check must be WireBytes only. We verify by checking
		// that the packed decode path uses ConsumeBytes, not ConsumeVarint directly.
		if !strings.Contains(src, "ConsumeBytes") {
			t.Error("packed repeated field must use ConsumeBytes for the packed payload")
		}
	}
}

// TestDeviationDuplicateFieldErrorInTemplate verifies that the generated
// unmarshal template for singular fields includes duplicate detection logic
// that returns ErrDuplicateField in strict mode.
func TestDeviationDuplicateFieldErrorInTemplate(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:  "singular.proto",
		Package: "foopb",
		Messages: []transform.GoMessage{
			{
				GoName: "Msg",
				Fields: []transform.GoField{
					{
						Field:  model.Field{Name: "name", Number: 1, Cardinality: model.CardinalitySingular, Type: model.FieldType{Kind: model.FieldKindScalar, Scalar: model.ScalarString}, JSONName: "name"},
						GoName: "Name", GoType: "string",
					},
					{
						Field:  model.Field{Name: "age", Number: 2, Cardinality: model.CardinalitySingular, Type: model.FieldType{Kind: model.FieldKindScalar, Scalar: model.ScalarInt32}, JSONName: "age"},
						GoName: "Age", GoType: "int32",
					},
				},
			},
		},
	}

	got, err := File(gf, testModule, Context{})
	if err != nil {
		t.Fatalf("File() error: %v", err)
	}
	src := string(got)

	// Must have seen bitmap and duplicate check.
	containsAll(t, src, map[string]string{
		"seen bitmap":       "var seen [2]uint64",
		"duplicate error":   "runtime.ErrDuplicateField",
		"lenient condition": "!lenient",
	})

	// Lenient path must NOT return error (it just skips the check).
	// Verify the pattern: if !lenient { return error }
	if !strings.Contains(src, "if !lenient") {
		t.Error("generated code must have 'if !lenient' guard for duplicate check")
	}
}

// --- TagProvider / annotation tests ---

// TestFileGormTag verifies that a message with GormMessageOptions generates
// gorm struct tags with the correct column name.
func TestFileGormTag(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:  "user.proto",
		Package: "foopb",
		Messages: []transform.GoMessage{
			{
				GoName: "User",
				Fields: []transform.GoField{
					{
						Field: model.Field{
							Name: "email", Number: 1,
							Cardinality: model.CardinalitySingular,
							Type:        model.FieldType{Kind: model.FieldKindScalar, Scalar: model.ScalarString},
							JSONName:    "email",
						},
						GoName:             "Email",
						GoType:             "string",
						GormMessageOptions: &model.GormMessageOptions{Table: "users"},
					},
					{
						Field: model.Field{
							Name:        "phone",
							Number:      2,
							Cardinality: model.CardinalitySingular,
							Type:        model.FieldType{Kind: model.FieldKindScalar, Scalar: model.ScalarString},
							JSONName:    "phone",
							GormOptions: &model.GormFieldOptions{Column: "phone_number"},
						},
						GoName:             "Phone",
						GoType:             "string",
						GormMessageOptions: &model.GormMessageOptions{Table: "users"},
					},
				},
			},
		},
	}

	got, err := File(gf, testModule, Context{})
	if err != nil {
		t.Fatalf("File() error: %v", err)
	}
	src := string(got)

	containsAll(t, src, map[string]string{
		"email gorm default column":  `gorm:"column:email"`,
		"phone gorm override column": `gorm:"column:phone_number"`,
		"email json":                 `json:"email"`,
		"phone json":                 `json:"phone"`,
	})
}

// TestFileNoGormTagWithoutAnnotation verifies that fields without
// GormMessageOptions do not get a gorm tag.
func TestFileNoGormTagWithoutAnnotation(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:  "plain.proto",
		Package: "foopb",
		Messages: []transform.GoMessage{
			{
				GoName: "Plain",
				Fields: []transform.GoField{
					{
						Field:  model.Field{Name: "name", Number: 1, Cardinality: model.CardinalitySingular, Type: model.FieldType{Kind: model.FieldKindScalar, Scalar: model.ScalarString}, JSONName: "name"},
						GoName: "Name",
						GoType: "string",
					},
				},
			},
		},
	}

	got, err := File(gf, testModule, Context{})
	if err != nil {
		t.Fatalf("File() error: %v", err)
	}
	src := string(got)

	if strings.Contains(src, "gorm:") {
		t.Error("field without GormMessageOptions must not have gorm tag")
	}
	if !strings.Contains(src, `json:"name"`) {
		t.Error("json tag must still be present")
	}
}

// TestFileJSONOmitempty verifies that json omitempty annotation generates
// the correct json tag.
func TestFileJSONOmitempty(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:  "omit.proto",
		Package: "foopb",
		Messages: []transform.GoMessage{
			{
				GoName: "Msg",
				Fields: []transform.GoField{
					{
						Field: model.Field{
							Name: "phone", Number: 1,
							Cardinality: model.CardinalitySingular,
							Type:        model.FieldType{Kind: model.FieldKindScalar, Scalar: model.ScalarString},
							JSONName:    "phone",
							JSONOptions: &model.JSONFieldOptions{Omitempty: true},
						},
						GoName: "Phone",
						GoType: "string",
					},
				},
			},
		},
	}

	got, err := File(gf, testModule, Context{})
	if err != nil {
		t.Fatalf("File() error: %v", err)
	}
	src := string(got)

	if !strings.Contains(src, `json:"phone,omitempty"`) {
		t.Errorf("expected json:\"phone,omitempty\" in output:\n%s", src)
	}
}

// TestFileJSONIgnore verifies that json ignore annotation generates json:"-".
func TestFileJSONIgnore(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:  "ignore.proto",
		Package: "foopb",
		Messages: []transform.GoMessage{
			{
				GoName: "Msg",
				Fields: []transform.GoField{
					{
						Field: model.Field{
							Name: "token", Number: 1,
							Cardinality: model.CardinalitySingular,
							Type:        model.FieldType{Kind: model.FieldKindScalar, Scalar: model.ScalarString},
							JSONName:    "token",
							JSONOptions: &model.JSONFieldOptions{Ignore: true},
						},
						GoName: "Token",
						GoType: "string",
					},
				},
			},
		},
	}

	got, err := File(gf, testModule, Context{})
	if err != nil {
		t.Fatalf("File() error: %v", err)
	}
	src := string(got)

	if !strings.Contains(src, `json:"-"`) {
		t.Errorf("expected json:\"-\" in output:\n%s", src)
	}
}

// TestFileJSONIgnorePrecedence verifies that when both omitempty and ignore
// are set, ignore takes precedence and generates json:"-".
func TestFileJSONIgnorePrecedence(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:  "precedence.proto",
		Package: "foopb",
		Messages: []transform.GoMessage{
			{
				GoName: "Msg",
				Fields: []transform.GoField{
					{
						Field: model.Field{
							Name: "secret", Number: 1,
							Cardinality: model.CardinalitySingular,
							Type:        model.FieldType{Kind: model.FieldKindScalar, Scalar: model.ScalarString},
							JSONName:    "secret",
							JSONOptions: &model.JSONFieldOptions{Omitempty: true, Ignore: true},
						},
						GoName: "Secret",
						GoType: "string",
					},
				},
			},
		},
	}

	got, err := File(gf, testModule, Context{})
	if err != nil {
		t.Fatalf("File() error: %v", err)
	}
	src := string(got)

	if !strings.Contains(src, `json:"-"`) {
		t.Errorf("expected json:\"-\" (ignore precedence) in output:\n%s", src)
	}
	if strings.Contains(src, "omitempty") {
		t.Error("omitempty must not appear when ignore is set")
	}
}

// TestFileMarshalOptionalField verifies that optional scalar fields generate
// nil-check guards and dereference the pointer when writing wire bytes.
func TestFileMarshalOptionalField(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:  "optional.proto",
		Package: "foopb",
		Messages: []transform.GoMessage{
			{
				GoName: "Opt",
				Fields: []transform.GoField{
					{
						Field: model.Field{
							Name: "score", Number: 1,
							Cardinality: model.CardinalitySingular,
							Optional:    true,
							Type:        model.FieldType{Kind: model.FieldKindScalar, Scalar: model.ScalarInt32},
							JSONName:    "score",
						},
						GoName: "Score",
						GoType: "*int32",
					},
					{
						Field: model.Field{
							Name: "label", Number: 2,
							Cardinality: model.CardinalitySingular,
							Optional:    true,
							Type:        model.FieldType{Kind: model.FieldKindScalar, Scalar: model.ScalarString},
							JSONName:    "label",
						},
						GoName: "Label",
						GoType: "*string",
					},
					// Non-optional field for contrast.
					{
						Field: model.Field{
							Name: "count", Number: 3,
							Cardinality: model.CardinalitySingular,
							Optional:    false,
							Type:        model.FieldType{Kind: model.FieldKindScalar, Scalar: model.ScalarInt32},
							JSONName:    "count",
						},
						GoName: "Count",
						GoType: "int32",
					},
				},
			},
		},
	}

	got, err := File(gf, testModule, Context{})
	if err != nil {
		t.Fatalf("File() error: %v", err)
	}
	src := string(got)

	// Optional fields must use nil check.
	containsAll(t, src, map[string]string{
		"score nil check": "x.Score != nil",
		"label nil check": "x.Label != nil",
		"score deref":     "*x.Score",
		"label deref":     "*x.Label",
	})

	// Non-optional int32 must use != 0 check, not nil.
	if !strings.Contains(src, "x.Count != 0") {
		t.Error("non-optional int32 must use != 0 check")
	}
}

// TestFileUnmarshalOptionalField verifies that optional scalar fields generate
// tmp-variable pointer assignment in the unmarshal code.
func TestFileUnmarshalOptionalField(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:  "optional.proto",
		Package: "foopb",
		Messages: []transform.GoMessage{
			{
				GoName: "Opt",
				Fields: []transform.GoField{
					{
						Field: model.Field{
							Name: "score", Number: 1,
							Cardinality: model.CardinalitySingular,
							Optional:    true,
							Type:        model.FieldType{Kind: model.FieldKindScalar, Scalar: model.ScalarInt32},
							JSONName:    "score",
						},
						GoName: "Score",
						GoType: "*int32",
					},
				},
			},
		},
	}

	got, err := File(gf, testModule, Context{})
	if err != nil {
		t.Fatalf("File() error: %v", err)
	}
	src := string(got)

	// Must use tmp variable and pointer assignment.
	containsAll(t, src, map[string]string{
		"tmp assign": "tmp := int32(v)",
		"ptr assign": "x.Score = &tmp",
	})

	// Must NOT use direct assignment like "x.Score = int32(v)".
	if strings.Contains(src, "x.Score = int32(v)") {
		t.Error("optional field must not use direct assignment")
	}
}

// TestFileMarshalOptionalBytes verifies that optional bytes fields generate
// nil-check guards and dereference the pointer (*[]byte) when writing wire bytes.
func TestFileMarshalOptionalBytes(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:  "optional_bytes.proto",
		Package: "foopb",
		Messages: []transform.GoMessage{
			{
				GoName: "Msg",
				Fields: []transform.GoField{
					{
						Field: model.Field{
							Name: "data", Number: 1,
							Cardinality: model.CardinalitySingular,
							Optional:    true,
							Type:        model.FieldType{Kind: model.FieldKindScalar, Scalar: model.ScalarBytes},
							JSONName:    "data",
						},
						GoName: "Data",
						GoType: "*[]byte",
					},
				},
			},
		},
	}

	got, err := File(gf, testModule, Context{})
	if err != nil {
		t.Fatalf("File() error: %v", err)
	}
	src := string(got)

	// Optional bytes must use nil check and dereference.
	containsAll(t, src, map[string]string{
		"nil check": "x.Data != nil",
		"deref":     "*x.Data",
	})
}

// TestFileUnmarshalOptionalBytes verifies that optional bytes fields generate
// tmp-variable pointer assignment (*[]byte) in the unmarshal code.
func TestFileUnmarshalOptionalBytes(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:  "optional_bytes.proto",
		Package: "foopb",
		Messages: []transform.GoMessage{
			{
				GoName: "Msg",
				Fields: []transform.GoField{
					{
						Field: model.Field{
							Name: "data", Number: 1,
							Cardinality: model.CardinalitySingular,
							Optional:    true,
							Type:        model.FieldType{Kind: model.FieldKindScalar, Scalar: model.ScalarBytes},
							JSONName:    "data",
						},
						GoName: "Data",
						GoType: "*[]byte",
					},
				},
			},
		},
	}

	got, err := File(gf, testModule, Context{})
	if err != nil {
		t.Fatalf("File() error: %v", err)
	}
	src := string(got)

	// Must use tmp variable and pointer assignment (not direct m.Data = tmp).
	containsAll(t, src, map[string]string{
		"tmp make":   "tmp := make([]byte",
		"copy":       "copy(tmp, payload)",
		"ptr assign": "x.Data = &tmp",
	})

	// Must NOT use direct assignment like "x.Data = tmp".
	if strings.Contains(src, "x.Data = tmp\n") {
		t.Error("optional bytes must not use direct assignment; must use &tmp")
	}
}

// --- ValidateFile tests ---

func ptr[T any](v T) *T { return &v }

func TestValidateFileEmpty(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:  "empty.proto",
		Package: "foopb",
		Messages: []transform.GoMessage{
			{
				GoName: "Empty",
				Fields: []transform.GoField{
					{
						Field:  model.Field{Name: "name", Number: 1, Cardinality: model.CardinalitySingular, Type: model.FieldType{Kind: model.FieldKindScalar, Scalar: model.ScalarString}, JSONName: "name"},
						GoName: "Name", GoType: "string",
					},
				},
			},
		},
	}

	got, err := ValidateFile(gf, testModule, Context{})
	if err != nil {
		t.Fatalf("ValidateFile() error: %v", err)
	}
	src := string(got)

	containsAll(t, src, map[string]string{
		"header":          "// Code generated by gcode. DO NOT EDIT.",
		"validate method": "func (x *Empty) Validate() error",
		"return nil":      "return nil",
	})
	// No imports needed for a file with no constraints.
	if strings.Contains(src, `"fmt"`) {
		t.Error("empty validate file must not import fmt")
	}
	if strings.Contains(src, "validateruntime") {
		t.Error("empty validate file must not import validateruntime")
	}
}

func TestValidateFileStringConstraints(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:  "user.proto",
		Package: "foopb",
		Messages: []transform.GoMessage{
			{
				GoName: "User",
				Fields: []transform.GoField{
					{
						Field: model.Field{
							Name: "email", Number: 1,
							Cardinality:     model.CardinalitySingular,
							Type:            model.FieldType{Kind: model.FieldKindScalar, Scalar: model.ScalarString},
							JSONName:        "email",
							ValidateOptions: &model.ValidateFieldOptions{Email: true},
						},
						GoName: "Email", GoType: "string",
					},
					{
						Field: model.Field{
							Name: "name", Number: 2,
							Cardinality: model.CardinalitySingular,
							Type:        model.FieldType{Kind: model.FieldKindScalar, Scalar: model.ScalarString},
							JSONName:    "name",
							ValidateOptions: &model.ValidateFieldOptions{
								Required: true,
								MinLen:   ptr(uint64(1)),
								MaxLen:   ptr(uint64(100)),
							},
						},
						GoName: "Name", GoType: "string",
					},
				},
			},
		},
	}

	got, err := ValidateFile(gf, testModule, Context{})
	if err != nil {
		t.Fatalf("ValidateFile() error: %v", err)
	}
	src := string(got)

	containsAll(t, src, map[string]string{
		"email check":    "IsEmail",
		"required check": `x.Name == ""`,
		"min_len check":  "len(x.Name) < 1",
		"max_len check":  "len(x.Name) > 100",
		"rule required":  `Rule: "required"`,
		"rule email":     `Rule: "email"`,
		"rule min_len":   `Rule: "min_len"`,
	})
}

func TestValidateFileNumericConstraints(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:  "product.proto",
		Package: "foopb",
		Messages: []transform.GoMessage{
			{
				GoName: "Product",
				Fields: []transform.GoField{
					{
						Field: model.Field{
							Name: "age", Number: 1,
							Cardinality: model.CardinalitySingular,
							Type:        model.FieldType{Kind: model.FieldKindScalar, Scalar: model.ScalarInt32},
							JSONName:    "age",
							ValidateOptions: &model.ValidateFieldOptions{
								GTEInt: ptr(int64(0)),
								LTEInt: ptr(int64(150)),
							},
						},
						GoName: "Age", GoType: "int32",
					},
					{
						Field: model.Field{
							Name: "status", Number: 2,
							Cardinality:     model.CardinalitySingular,
							Type:            model.FieldType{Kind: model.FieldKindScalar, Scalar: model.ScalarInt32},
							JSONName:        "status",
							ValidateOptions: &model.ValidateFieldOptions{NotInInt: []int64{0, -1}},
						},
						GoName: "Status", GoType: "int32",
					},
				},
			},
		},
	}

	got, err := ValidateFile(gf, testModule, Context{})
	if err != nil {
		t.Fatalf("ValidateFile() error: %v", err)
	}
	src := string(got)

	containsAll(t, src, map[string]string{
		"gte check":   "x.Age < 0",
		"lte check":   "x.Age > 150",
		"not_in loop": "for _, v := range []int32{0, -1}",
		"not_in rule": `Rule: "not_in"`,
	})
}

func TestValidateFileRepeatedConstraints(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:  "order.proto",
		Package: "foopb",
		Messages: []transform.GoMessage{
			{
				GoName: "Order",
				Fields: []transform.GoField{
					{
						Field: model.Field{
							Name: "tags", Number: 1,
							Cardinality: model.CardinalityRepeated,
							Type:        model.FieldType{Kind: model.FieldKindScalar, Scalar: model.ScalarString},
							JSONName:    "tags",
							ValidateOptions: &model.ValidateFieldOptions{
								MinItems: ptr(uint64(1)),
								MaxItems: ptr(uint64(10)),
								Items:    &model.ValidateFieldOptions{MinLen: ptr(uint64(1))},
							},
						},
						GoName: "Tags", GoType: "[]string", ElemGoType: "string",
					},
				},
			},
		},
	}

	got, err := ValidateFile(gf, testModule, Context{})
	if err != nil {
		t.Fatalf("ValidateFile() error: %v", err)
	}
	src := string(got)

	containsAll(t, src, map[string]string{
		"min_items":    "len(x.Tags) < 1",
		"max_items":    "len(x.Tags) > 10",
		"items loop":   "for i, v := range x.Tags",
		"items minlen": "len(v) < 1",
		"fmt import":   `"fmt"`,
		"sprintf":      "fmt.Sprintf",
	})
}

func TestValidateFileMessageRequired(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:  "order.proto",
		Package: "foopb",
		Messages: []transform.GoMessage{
			{
				GoName: "Order",
				Fields: []transform.GoField{
					{
						Field: model.Field{
							Name: "address", Number: 1,
							Cardinality:     model.CardinalitySingular,
							Type:            model.FieldType{Kind: model.FieldKindMessage, FullName: ".foopb.Address"},
							JSONName:        "address",
							ValidateOptions: &model.ValidateFieldOptions{Required: true},
						},
						GoName: "Address", GoType: "*Address",
					},
				},
			},
		},
	}

	got, err := ValidateFile(gf, testModule, Context{})
	if err != nil {
		t.Fatalf("ValidateFile() error: %v", err)
	}
	src := string(got)

	containsAll(t, src, map[string]string{
		"nil check": "x.Address == nil",
		"required":  `Rule: "required"`,
		"recursive": "x.Address.Validate()",
	})
}

func TestValidateFileEnumDefinedOnly(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:  "status.proto",
		Package: "foopb",
		Messages: []transform.GoMessage{
			{
				GoName: "Msg",
				Fields: []transform.GoField{
					{
						Field: model.Field{
							Name: "status", Number: 1,
							Cardinality:     model.CardinalitySingular,
							Type:            model.FieldType{Kind: model.FieldKindEnum, FullName: ".foopb.Status"},
							JSONName:        "status",
							ValidateOptions: &model.ValidateFieldOptions{DefinedOnly: true, NotInEnum: []int32{0, 2}},
						},
						GoName: "Status", GoType: "Status",
					},
				},
			},
		},
		Enums: []transform.GoEnum{
			{
				GoName: "Status",
				Values: []transform.GoEnumValue{
					{GoName: "Status_STATUS_ACTIVE", Number: 1},
					{GoName: "Status_STATUS_INACTIVE", Number: 2},
				},
			},
		},
	}

	got, err := ValidateFile(gf, testModule, Context{})
	if err != nil {
		t.Fatalf("ValidateFile() error: %v", err)
	}
	src := string(got)

	containsAll(t, src, map[string]string{
		"switch":        "switch x.Status",
		"not_in loop":   "for _, v := range []int32{0, 2}",
		"not_in cast":   "if int32(x.Status) == v",
		"not_in rule":   `Rule: "not_in"`,
		"active case":   "Status_STATUS_ACTIVE",
		"inactive case": "Status_STATUS_INACTIVE",
		"defined_only":  `Rule: "defined_only"`,
	})
}

func TestValidateFileBytesConstraints(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:  "blob.proto",
		Package: "foopb",
		Messages: []transform.GoMessage{
			{
				GoName: "Blob",
				Fields: []transform.GoField{
					{
						Field: model.Field{
							Name: "data", Number: 1,
							Cardinality: model.CardinalitySingular,
							Type:        model.FieldType{Kind: model.FieldKindScalar, Scalar: model.ScalarBytes},
							JSONName:    "data",
							ValidateOptions: &model.ValidateFieldOptions{
								Required: true,
								MinLen:   ptr(uint64(1)),
							},
						},
						GoName: "Data", GoType: "[]byte",
					},
				},
			},
		},
	}

	got, err := ValidateFile(gf, testModule, Context{})
	if err != nil {
		t.Fatalf("ValidateFile() error: %v", err)
	}
	src := string(got)

	containsAll(t, src, map[string]string{
		"nil check": "x.Data == nil",
		"required":  `Rule: "required"`,
		"min_len":   "len(x.Data) < 1",
	})
}

func TestValidateFileValidateMessage(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:  "custom.proto",
		Package: "foopb",
		Messages: []transform.GoMessage{
			{
				GoName: "Custom",
				Fields: []transform.GoField{
					{
						Field: model.Field{
							Name: "email", Number: 1,
							Cardinality:     model.CardinalitySingular,
							Type:            model.FieldType{Kind: model.FieldKindScalar, Scalar: model.ScalarString},
							JSONName:        "email",
							ValidateOptions: &model.ValidateFieldOptions{Email: true},
							ValidateMessage: "请输入有效的邮箱地址",
						},
						GoName: "Email", GoType: "string",
					},
				},
			},
		},
	}

	got, err := ValidateFile(gf, testModule, Context{})
	if err != nil {
		t.Fatalf("ValidateFile() error: %v", err)
	}
	src := string(got)

	if !strings.Contains(src, "请输入有效的邮箱地址") {
		t.Error("custom validate_message must appear in generated code")
	}
	if !strings.Contains(src, "validateruntime.MsgOr") {
		t.Error("validateruntime.MsgOr must be used for validate_message override")
	}
}

// TestFileGormTableName verifies that a message with GormMessageOptions.Table
// generates a TableName() method returning the configured table name.
func TestFileGormTableName(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:  "user.proto",
		Package: "foopb",
		Messages: []transform.GoMessage{
			{
				GoName:             "User",
				GormMessageOptions: &model.GormMessageOptions{Table: "sys_users"},
				Fields: []transform.GoField{
					{
						Field:              model.Field{Name: "name", Number: 1, Cardinality: model.CardinalitySingular, Type: model.FieldType{Kind: model.FieldKindScalar, Scalar: model.ScalarString}, JSONName: "name"},
						GoName:             "Name",
						GoType:             "string",
						GormMessageOptions: &model.GormMessageOptions{Table: "sys_users"},
					},
				},
			},
		},
	}

	got, err := File(gf, testModule, Context{})
	if err != nil {
		t.Fatalf("File() error: %v", err)
	}
	src := string(got)

	if !strings.Contains(src, `func (User) TableName() string { return "sys_users" }`) {
		t.Errorf("expected TableName() method in generated source, got:\n%s", src)
	}
}

// TestFileNoGormTableNameWithoutAnnotation verifies that a message without
// GormMessageOptions does not generate a TableName() method.
func TestFileNoGormTableNameWithoutAnnotation(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:  "plain.proto",
		Package: "foopb",
		Messages: []transform.GoMessage{
			{
				GoName: "Plain",
				Fields: []transform.GoField{
					{
						Field:  model.Field{Name: "name", Number: 1, Cardinality: model.CardinalitySingular, Type: model.FieldType{Kind: model.FieldKindScalar, Scalar: model.ScalarString}, JSONName: "name"},
						GoName: "Name",
						GoType: "string",
					},
				},
			},
		},
	}

	got, err := File(gf, testModule, Context{})
	if err != nil {
		t.Fatalf("File() error: %v", err)
	}
	if strings.Contains(string(got), "TableName") {
		t.Error("message without GormMessageOptions must not generate TableName()")
	}
}

// TestToMapUsesGormColumn verifies that ToMap() uses the gorm column name as
// the map key when a field has a gorm.column override.
func TestToMapUsesGormColumn(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:  "item.update.proto",
		Package: "foopb",
		Messages: []transform.GoMessage{
			{
				GoName:       "ItemUpdate",
				UpdateSource: "Item",
				Fields: []transform.GoField{
					{
						Field: model.Field{
							Name: "created_at", Number: 1,
							Cardinality: model.CardinalitySingular,
							Type:        model.FieldType{Kind: model.FieldKindScalar, Scalar: model.ScalarInt64},
							JSONName:    "createdAt",
							GormOptions: &model.GormFieldOptions{Column: "created_ts"},
						},
						GoName: "CreatedAt",
						GoType: "*int64",
					},
					{
						Field: model.Field{
							Name: "name", Number: 2,
							Cardinality: model.CardinalitySingular,
							Type:        model.FieldType{Kind: model.FieldKindScalar, Scalar: model.ScalarString},
							JSONName:    "name",
						},
						GoName: "Name",
						GoType: "string",
					},
				},
			},
		},
	}

	got, err := File(gf, testModule, Context{})
	if err != nil {
		t.Fatalf("File() error: %v", err)
	}
	src := string(got)

	// gorm column override: key must be "created_ts", not "created_at" or "createdAt"
	if !strings.Contains(src, `um["created_ts"]`) {
		t.Errorf("ToMap() must use gorm column name 'created_ts' as key, got:\n%s", src)
	}
	if strings.Contains(src, `um["created_at"]`) || strings.Contains(src, `um["createdAt"]`) {
		t.Errorf("ToMap() must not use proto field name or json name as key, got:\n%s", src)
	}
	// no override: key must be proto field name "name"
	if !strings.Contains(src, `um["name"]`) {
		t.Errorf("ToMap() must use proto field name 'name' when no gorm column override, got:\n%s", src)
	}
}

// TestFileCreateMessageInheritsGormOptionsFromContext verifies that File()
// propagates GormMessageOptions from the source message (via Context.MessageIndex)
// to a create derived message, generating TableName() and gorm struct tags.
func TestFileCreateMessageInheritsGormOptionsFromContext(t *testing.T) {
	t.Parallel()

	gormOpts := &model.GormMessageOptions{Table: "persons"}
	srcMsg := transform.GoMessage{
		GoName:             "Person",
		GormMessageOptions: gormOpts,
		Fields: []transform.GoField{
			{
				Field:              model.Field{Name: "name", Number: 1, Cardinality: model.CardinalitySingular, Type: model.FieldType{Kind: model.FieldKindScalar, Scalar: model.ScalarString}, JSONName: "name"},
				GoName:             "Name",
				GoType:             "string",
				GormMessageOptions: gormOpts,
			},
		},
	}

	createMsg := transform.GoMessage{
		GoName:       "PersonCreate",
		CreateSource: "Person",
		Fields: []transform.GoField{
			{
				Field:  model.Field{Name: "name", Number: 1, Cardinality: model.CardinalitySingular, Type: model.FieldType{Kind: model.FieldKindScalar, Scalar: model.ScalarString}, JSONName: "name"},
				GoName: "Name",
				GoType: "*string",
			},
		},
	}

	gf := transform.GoFile{
		Source:   "person.create.proto",
		Package:  "foopb",
		Messages: []transform.GoMessage{createMsg},
	}
	ctx := Context{MessageIndex: map[string]*transform.GoMessage{"Person": &srcMsg}}

	got, err := File(gf, testModule, ctx)
	if err != nil {
		t.Fatalf("File() error: %v", err)
	}
	src := string(got)

	if !strings.Contains(src, `func (PersonCreate) TableName() string { return "persons" }`) {
		t.Errorf("PersonCreate must inherit TableName() from source message, got:\n%s", src)
	}
	if !strings.Contains(src, `gorm:"column:name"`) {
		t.Errorf("PersonCreate fields must inherit gorm tags from source message, got:\n%s", src)
	}
}

// TestFileCreateMessageInheritsGormColumnOverride verifies that a create derived
// message inherits the gorm column override from the source message's field-level
// GormOptions, so that fields with (gcode.field).gorm.column annotations generate
// the correct gorm struct tag in the derived struct.
func TestFileCreateMessageInheritsGormColumnOverride(t *testing.T) {
	t.Parallel()

	gormOpts := &model.GormMessageOptions{Table: "persons"}
	srcMsg := transform.GoMessage{
		GoName:             "Person",
		GormMessageOptions: gormOpts,
		Fields: []transform.GoField{
			{
				Field: model.Field{
					Name: "created_at", Number: 1,
					Cardinality: model.CardinalitySingular,
					Type:        model.FieldType{Kind: model.FieldKindScalar, Scalar: model.ScalarInt64},
					JSONName:    "createdAt",
					GormOptions: &model.GormFieldOptions{Column: "created_ts"},
				},
				GoName:             "CreatedAt",
				GoType:             "int64",
				GormMessageOptions: gormOpts,
			},
		},
	}

	createMsg := transform.GoMessage{
		GoName:       "PersonCreate",
		CreateSource: "Person",
		Fields: []transform.GoField{
			{
				// GormOptions is intentionally nil here: the render layer must
				// inject it from Context.MessageIndex (the source message's field).
				Field: model.Field{
					Name: "created_at", Number: 1,
					Cardinality: model.CardinalitySingular,
					Type:        model.FieldType{Kind: model.FieldKindScalar, Scalar: model.ScalarInt64},
					JSONName:    "createdAt",
					GormOptions: &model.GormFieldOptions{Column: "created_ts"},
				},
				GoName:             "CreatedAt",
				GoType:             "*int64",
				GormMessageOptions: nil, // no gorm annotation on the derived message itself
			},
		},
	}

	gf := transform.GoFile{
		Source:   "person.create.proto",
		Package:  "foopb",
		Messages: []transform.GoMessage{createMsg},
	}
	ctx := Context{MessageIndex: map[string]*transform.GoMessage{"Person": &srcMsg}}

	got, err := File(gf, testModule, ctx)
	if err != nil {
		t.Fatalf("File() error: %v", err)
	}
	src := string(got)

	if !strings.Contains(src, `gorm:"column:created_ts"`) {
		t.Errorf("PersonCreate must inherit gorm column override 'created_ts', got:\n%s", src)
	}
}
