package render

import (
	"strings"
	"testing"

	"github.com/pinealctx/gcode/internal/model"
	"github.com/pinealctx/gcode/internal/transform"
)

func TestRPCFileSingleServiceSingleMethod(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:  "user_service.proto",
		Package: "dao",
		Services: []transform.GoService{
			{
				GoName: "UserService",
				Methods: []transform.GoRPCMethod{
					{
						GoName:       "CreateUser",
						RequestType:  "CreateUserRequest",
						ResponseType: "CreateUserResponse",
					},
				},
			},
		},
	}

	got, err := RPCFile(gf)
	if err != nil {
		t.Fatalf("RPCFile() error: %v", err)
	}
	src := string(got)

	containsAll(t, src, map[string]string{
		"header":         "// Code generated by gcode. DO NOT EDIT.",
		"source":         "// source: user_service.proto",
		"package":        "package dao",
		"import context": `"context"`,
		"interface":      "type UserService interface",
		"method sig":     "CreateUser(ctx context.Context, req *CreateUserRequest) (*CreateUserResponse, error)",
	})
}

func TestRPCFileMultipleServicesMultipleMethods(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:  "services.proto",
		Package: "dao",
		Services: []transform.GoService{
			{
				GoName: "UserService",
				Methods: []transform.GoRPCMethod{
					{GoName: "CreateUser", RequestType: "CreateUserRequest", ResponseType: "CreateUserResponse"},
					{GoName: "GetUser", RequestType: "GetUserRequest", ResponseType: "GetUserResponse"},
				},
			},
			{
				GoName: "OrderService",
				Methods: []transform.GoRPCMethod{
					{GoName: "PlaceOrder", RequestType: "PlaceOrderRequest", ResponseType: "PlaceOrderResponse"},
				},
			},
		},
	}

	got, err := RPCFile(gf)
	if err != nil {
		t.Fatalf("RPCFile() error: %v", err)
	}
	src := string(got)

	containsAll(t, src, map[string]string{
		"UserService interface":  "type UserService interface",
		"OrderService interface": "type OrderService interface",
		"CreateUser":             "CreateUser(ctx context.Context, req *CreateUserRequest) (*CreateUserResponse, error)",
		"GetUser":                "GetUser(ctx context.Context, req *GetUserRequest) (*GetUserResponse, error)",
		"PlaceOrder":             "PlaceOrder(ctx context.Context, req *PlaceOrderRequest) (*PlaceOrderResponse, error)",
	})
}

func TestRPCFileImportContextPresent(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:  "svc.proto",
		Package: "mypkg",
		Services: []transform.GoService{
			{
				GoName: "FooService",
				Methods: []transform.GoRPCMethod{
					{GoName: "DoFoo", RequestType: "FooRequest", ResponseType: "FooResponse"},
				},
			},
		},
	}

	got, err := RPCFile(gf)
	if err != nil {
		t.Fatalf("RPCFile() error: %v", err)
	}
	src := string(got)

	if !strings.Contains(src, `"context"`) {
		t.Errorf("expected import context in output:\n%s", src)
	}
	// context.Context must appear in method signatures
	if !strings.Contains(src, "context.Context") {
		t.Errorf("expected context.Context in method signature:\n%s", src)
	}
}

func TestRPCFileWithComments(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:  "svc.proto",
		Package: "dao",
		Services: []transform.GoService{
			{
				GoName:  "UserService",
				Comment: model.Comment{Lines: []string{"UserService handles user operations."}},
				Methods: []transform.GoRPCMethod{
					{
						GoName:       "CreateUser",
						RequestType:  "CreateUserRequest",
						ResponseType: "CreateUserResponse",
						Comment:      model.Comment{Lines: []string{"CreateUser creates a new user."}},
					},
				},
			},
		},
	}

	got, err := RPCFile(gf)
	if err != nil {
		t.Fatalf("RPCFile() error: %v", err)
	}
	src := string(got)

	containsAll(t, src, map[string]string{
		"service comment": "// UserService handles user operations.",
		"method comment":  "// CreateUser creates a new user.",
	})
}

func TestRPCFileMethodSignatureFormat(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:  "svc.proto",
		Package: "dao",
		Services: []transform.GoService{
			{
				GoName: "PersonService",
				Methods: []transform.GoRPCMethod{
					{GoName: "GetPerson", RequestType: "GetPersonRequest", ResponseType: "GetPersonResponse"},
				},
			},
		},
	}

	got, err := RPCFile(gf)
	if err != nil {
		t.Fatalf("RPCFile() error: %v", err)
	}
	src := string(got)

	// Verify exact method signature format
	expected := "GetPerson(ctx context.Context, req *GetPersonRequest) (*GetPersonResponse, error)"
	if !strings.Contains(src, expected) {
		t.Errorf("expected method signature %q in output:\n%s", expected, src)
	}
}

func TestRPCFileNoServices(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:   "messages.proto",
		Package:  "dao",
		Services: nil,
	}

	got, err := RPCFile(gf)
	if err != nil {
		t.Fatalf("RPCFile() error: %v", err)
	}
	src := string(got)

	// Header and package should still be present.
	containsAll(t, src, map[string]string{
		"header":  "// Code generated by gcode. DO NOT EDIT.",
		"package": "package dao",
	})
	// No interface definitions should be generated.
	if strings.Contains(src, "interface") {
		t.Errorf("expected no interface in output for empty services, got:\n%s", src)
	}
	// No context import should be generated when there are no services.
	if strings.Contains(src, `"context"`) {
		t.Errorf("expected no context import for empty services, got:\n%s", src)
	}
}

func TestRPCFileCommentCombinations(t *testing.T) {
	t.Parallel()

	// P4: service has comment, method has no comment
	gf := transform.GoFile{
		Source:  "svc.proto",
		Package: "dao",
		Services: []transform.GoService{
			{
				GoName:  "UserService",
				Comment: model.Comment{Lines: []string{"UserService comment."}},
				Methods: []transform.GoRPCMethod{
					{GoName: "GetUser", RequestType: "GetUserRequest", ResponseType: "GetUserResponse"},
				},
			},
		},
	}
	got, err := RPCFile(gf)
	if err != nil {
		t.Fatalf("RPCFile() P4 error: %v", err)
	}
	src := string(got)
	if !strings.Contains(src, "// UserService comment.") {
		t.Errorf("P4: expected service comment in output:\n%s", src)
	}

	// P5: service has no comment, method has comment
	gf2 := transform.GoFile{
		Source:  "svc.proto",
		Package: "dao",
		Services: []transform.GoService{
			{
				GoName: "OrderService",
				Methods: []transform.GoRPCMethod{
					{
						GoName:       "PlaceOrder",
						RequestType:  "PlaceOrderRequest",
						ResponseType: "PlaceOrderResponse",
						Comment:      model.Comment{Lines: []string{"PlaceOrder method comment."}},
					},
				},
			},
		},
	}
	got2, err := RPCFile(gf2)
	if err != nil {
		t.Fatalf("RPCFile() P5 error: %v", err)
	}
	src2 := string(got2)
	if !strings.Contains(src2, "// PlaceOrder method comment.") {
		t.Errorf("P5: expected method comment in output:\n%s", src2)
	}
}

func TestRPCFileFormatError(t *testing.T) {
	t.Parallel()

	// Inject an invalid Go identifier as Package to trigger format.Source failure.
	gf := transform.GoFile{
		Source:  "svc.proto",
		Package: "123invalid",
		Services: []transform.GoService{
			{
				GoName: "FooService",
				Methods: []transform.GoRPCMethod{
					{GoName: "DoFoo", RequestType: "FooRequest", ResponseType: "FooResponse"},
				},
			},
		},
	}
	_, err := RPCFile(gf)
	if err == nil {
		t.Fatal("RPCFile() expected error for invalid package name, got nil")
	}
}
