// Package tsrender generates TypeScript source code from the Go-oriented
// intermediate representation produced by the transform package. It outputs
// .ts files containing interfaces, enums, enum name mappings, and (later)
// validation metadata.
package tsrender

import (
	"fmt"
	"strings"

	"github.com/pinealctx/gcode/internal/model"
	"github.com/pinealctx/gcode/internal/naming"
	"github.com/pinealctx/gcode/internal/transform"
)

// TSFile generates a complete TypeScript file from a GoFile intermediate
// representation. The returned bytes are ready to write to disk as a .pb.ts file.
func TSFile(gf transform.GoFile) ([]byte, error) {
	var b strings.Builder

	writeHeader(&b, gf.Source)

	for _, enum := range gf.Enums {
		writeTSEnum(&b, enum)
	}

	for _, msg := range gf.Messages {
		writeTSInterface(&b, msg, gf.Package)
	}

	for _, msg := range gf.Messages {
		writeTSValidationRules(&b, msg)
	}

	return []byte(b.String()), nil
}

// tsScalarType maps a protobuf scalar kind to its TypeScript type.
func tsScalarType(kind model.ScalarKind) string {
	switch kind {
	case model.ScalarInt32, model.ScalarSint32, model.ScalarSfixed32,
		model.ScalarUint32, model.ScalarFixed32,
		model.ScalarFloat, model.ScalarDouble:
		return "number"
	case model.ScalarInt64, model.ScalarSint64, model.ScalarSfixed64,
		model.ScalarUint64, model.ScalarFixed64:
		return "string"
	case model.ScalarBool:
		return "boolean"
	case model.ScalarString, model.ScalarBytes:
		return "string"
	default:
		return "unknown"
	}
}

// tsFieldType resolves the TypeScript type string for a GoField.
// It handles scalars, enums, message references, and repeated cardinality.
func tsFieldType(f transform.GoField, pkgName string) string {
	var base string
	switch f.Type.Kind {
	case model.FieldKindScalar:
		base = tsScalarType(f.Type.Scalar)
	case model.FieldKindEnum, model.FieldKindMessage:
		base = naming.GoTypeName(f.Type.FullName, pkgName)
	default:
		base = "unknown"
	}

	if f.Cardinality == model.CardinalityRepeated {
		return base + "[]"
	}
	return base
}

// tsIsOptional returns true if the field should be marked optional in the
// TypeScript interface (using the `?:` syntax). This covers both proto3
// explicit optional fields and fields with presence semantics (e.g. optional bytes).
func tsIsOptional(f transform.GoField) bool {
	return f.Optional || f.HasPresence
}

// writeHeader writes the generated-file header comment.
func writeHeader(b *strings.Builder, source string) {
	b.WriteString("// Code generated by gcode. DO NOT EDIT.\n")
	fmt.Fprintf(b, "// source: %s\n\n", source)
}

// writeTSComment writes a JSDoc-style comment block. Single-line comments
// use the `/** ... */` form; multi-line comments use the indented form.
func writeTSComment(b *strings.Builder, comment model.Comment) {
	if len(comment.Lines) == 0 {
		return
	}
	if len(comment.Lines) == 1 {
		fmt.Fprintf(b, "/** %s */\n", comment.Lines[0])
		return
	}
	b.WriteString("/**\n")
	for _, line := range comment.Lines {
		fmt.Fprintf(b, " * %s\n", line)
	}
	b.WriteString(" */\n")
}

// writeTSEnum writes a TypeScript enum declaration followed by its
// name mapping Record. Enum value names are extracted from the GoName
// by stripping the parent enum name prefix.
//
// Example output:
//
//	export enum Status {
//	  STATUS_UNSPECIFIED = 0,
//	  STATUS_ACTIVE = 1,
//	}
//
//	export const StatusName: Record<Status, string> = {
//	  [Status.STATUS_UNSPECIFIED]: "STATUS_UNSPECIFIED",
//	  [Status.STATUS_ACTIVE]: "STATUS_ACTIVE",
//	} as const
func writeTSEnum(b *strings.Builder, enum transform.GoEnum) {
	writeTSComment(b, enum.Comment)
	fmt.Fprintf(b, "export enum %s {\n", enum.GoName)
	for _, v := range enum.Values {
		protoName := strings.TrimPrefix(v.GoName, enum.GoName+"_")
		fmt.Fprintf(b, "  %s = %d,\n", protoName, v.Number)
	}
	b.WriteString("}\n\n")

	fmt.Fprintf(b, "export const %sName: Record<%s, string> = {\n", enum.GoName, enum.GoName)
	for _, v := range enum.Values {
		protoName := strings.TrimPrefix(v.GoName, enum.GoName+"_")
		fmt.Fprintf(b, "  [%s.%s]: \"%s\",\n", enum.GoName, protoName, protoName)
	}
	b.WriteString("} as const\n\n")
}

// writeTSInterface writes a TypeScript interface declaration for a message.
// Field names use the proto JSONName (camelCase). Optional fields use the
// `?:` syntax; repeated fields use `T[]`.
//
// Example output:
//
//	/** Comment from proto. */
//	export interface Person {
//	  name: string
//	  age: number
//	  address?: Address
//	  scores: number[]
//	}
func writeTSInterface(b *strings.Builder, msg transform.GoMessage, pkgName string) {
	writeTSComment(b, msg.Comment)
	fmt.Fprintf(b, "export interface %s {\n", msg.GoName)
	for _, f := range msg.Fields {
		fieldName := f.JSONName
		fieldType := tsFieldType(f, pkgName)
		if tsIsOptional(f) {
			fmt.Fprintf(b, "  %s?: %s\n", fieldName, fieldType)
		} else {
			fmt.Fprintf(b, "  %s: %s\n", fieldName, fieldType)
		}
	}
	b.WriteString("}\n\n")
}

// tsValidationType returns the TS metadata "type" value for a GoField.
// This differs from tsScalarType/tsFieldType which produce interface types.
func tsValidationType(f transform.GoField) string {
	if f.Cardinality == model.CardinalityRepeated {
		return "array"
	}
	switch f.Type.Kind {
	case model.FieldKindScalar:
		switch f.Type.Scalar {
		case model.ScalarString, model.ScalarBytes:
			return "string"
		case model.ScalarInt32, model.ScalarSint32, model.ScalarSfixed32,
			model.ScalarUint32, model.ScalarFixed32,
			model.ScalarInt64, model.ScalarSint64, model.ScalarSfixed64,
			model.ScalarUint64, model.ScalarFixed64:
			return "integer"
		case model.ScalarFloat, model.ScalarDouble:
			return "number"
		case model.ScalarBool:
			return "boolean"
		default:
			return "unknown"
		}
	case model.FieldKindEnum:
		return "enum"
	case model.FieldKindMessage:
		return "object"
	default:
		return "unknown"
	}
}

// writeTSValidationRules generates a validation rules constant for a message.
// Only fields with ValidateOptions produce entries; others are silently omitted.
//
// Example output:
//
//	export const PersonRules = {
//	  name: { required: true, type: "string", minLength: 1 } },
//	} as const
func writeTSValidationRules(b *strings.Builder, msg transform.GoMessage) {
	// Collect fields that have validation rules.
	type fieldEntry struct {
		name  string
		field transform.GoField
	}
	var entries []fieldEntry
	for _, f := range msg.Fields {
		if f.ValidateOptions != nil {
			entries = append(entries, fieldEntry{name: f.JSONName, field: f})
		}
	}
	if len(entries) == 0 {
		return
	}

	fmt.Fprintf(b, "export const %sRules = {\n", msg.GoName)
	for i, e := range entries {
		writeTSFieldRules(b, e.name, e.field, "  ")
		if i < len(entries)-1 {
			b.WriteString(",\n")
		} else {
			b.WriteString("\n")
		}
	}
	b.WriteString("} as const\n\n")
}

// writeTSFieldRules writes all validation rules for a single field.
func writeTSFieldRules(b *strings.Builder, jsonName string, f transform.GoField, indent string) {
	vo := f.ValidateOptions

	fmt.Fprintf(b, "%s%s: { ", indent, jsonName)

	// required
	fmt.Fprintf(b, "required: %t", vo.Required)

	// type
	fmt.Fprintf(b, ", type: %q", tsValidationType(f))

	// String constraints
	if vo.MinLen != nil {
		fmt.Fprintf(b, ", minLength: %d", *vo.MinLen)
	}
	if vo.MaxLen != nil {
		fmt.Fprintf(b, ", maxLength: %d", *vo.MaxLen)
	}
	if vo.Pattern != "" {
		fmt.Fprintf(b, ", pattern: %q", vo.Pattern)
	}
	if vo.Email {
		fmt.Fprintf(b, ", format: %q", "email")
	}
	if vo.URI {
		fmt.Fprintf(b, ", format: %q", "uri")
	}
	if len(vo.InStr) > 0 {
		b.WriteString(", enum: [")
		for i, v := range vo.InStr {
			if i > 0 {
				b.WriteString(", ")
			}
			fmt.Fprintf(b, "%q", v)
		}
		b.WriteString("]")
	}
	if len(vo.NotInStr) > 0 {
		b.WriteString(", notIn: [")
		for i, v := range vo.NotInStr {
			if i > 0 {
				b.WriteString(", ")
			}
			fmt.Fprintf(b, "%q", v)
		}
		b.WriteString("]")
	}

	// Signed integer constraints
	if vo.GTEInt != nil {
		fmt.Fprintf(b, ", minimum: %d", *vo.GTEInt)
	}
	if vo.LTEInt != nil {
		fmt.Fprintf(b, ", maximum: %d", *vo.LTEInt)
	}
	if vo.GTInt != nil {
		fmt.Fprintf(b, ", exclusiveMinimum: %d", *vo.GTInt)
	}
	if vo.LTInt != nil {
		fmt.Fprintf(b, ", exclusiveMaximum: %d", *vo.LTInt)
	}
	if len(vo.InInt) > 0 {
		b.WriteString(", enum: [")
		for i, v := range vo.InInt {
			if i > 0 {
				b.WriteString(", ")
			}
			fmt.Fprintf(b, "%d", v)
		}
		b.WriteString("]")
	}
	if len(vo.NotInInt) > 0 {
		b.WriteString(", notIn: [")
		for i, v := range vo.NotInInt {
			if i > 0 {
				b.WriteString(", ")
			}
			fmt.Fprintf(b, "%d", v)
		}
		b.WriteString("]")
	}

	// Unsigned integer constraints
	if vo.GTEUint != nil {
		fmt.Fprintf(b, ", minimum: %d", *vo.GTEUint)
	}
	if vo.LTEUint != nil {
		fmt.Fprintf(b, ", maximum: %d", *vo.LTEUint)
	}
	if vo.GTUint != nil {
		fmt.Fprintf(b, ", exclusiveMinimum: %d", *vo.GTUint)
	}
	if vo.LTUint != nil {
		fmt.Fprintf(b, ", exclusiveMaximum: %d", *vo.LTUint)
	}
	if len(vo.InUint) > 0 {
		b.WriteString(", enum: [")
		for i, v := range vo.InUint {
			if i > 0 {
				b.WriteString(", ")
			}
			fmt.Fprintf(b, "%d", v)
		}
		b.WriteString("]")
	}
	if len(vo.NotInUint) > 0 {
		b.WriteString(", notIn: [")
		for i, v := range vo.NotInUint {
			if i > 0 {
				b.WriteString(", ")
			}
			fmt.Fprintf(b, "%d", v)
		}
		b.WriteString("]")
	}

	// Float constraints
	if vo.GTEFloat != nil {
		fmt.Fprintf(b, ", minimum: %g", *vo.GTEFloat)
	}
	if vo.LTEFloat != nil {
		fmt.Fprintf(b, ", maximum: %g", *vo.LTEFloat)
	}
	if vo.GTFloat != nil {
		fmt.Fprintf(b, ", exclusiveMinimum: %g", *vo.GTFloat)
	}
	if vo.LTFloat != nil {
		fmt.Fprintf(b, ", exclusiveMaximum: %g", *vo.LTFloat)
	}

	// Enum constraints
	if vo.DefinedOnly {
		b.WriteString(", definedOnly: true")
	}

	// Repeated constraints
	if vo.MinItems != nil {
		fmt.Fprintf(b, ", minItems: %d", *vo.MinItems)
	}
	if vo.MaxItems != nil {
		fmt.Fprintf(b, ", maxItems: %d", *vo.MaxItems)
	}
	if vo.Items != nil {
		b.WriteString(", items: { ")
		writeItemRules(b, vo.Items)
		b.WriteString(" }")
	}

	b.WriteString(" }")
}

// writeItemRules writes validation rules for repeated field items (inner constraints).
// These are simpler than top-level field rules: no required/type prefix, no nested items.
func writeItemRules(b *strings.Builder, vo *model.ValidateFieldOptions) {
	// type is always emitted for items
	// Items inherit the element scalar type, but we don't have the field here.
	// The caller should handle type; for items we write constraints only.

	if vo.MinLen != nil {
		fmt.Fprintf(b, "minLength: %d", *vo.MinLen)
	}
	if vo.MaxLen != nil {
		if vo.MinLen != nil {
			b.WriteString(", ")
		}
		fmt.Fprintf(b, "maxLength: %d", *vo.MaxLen)
	}
	if vo.Pattern != "" {
		if vo.MinLen != nil || vo.MaxLen != nil {
			b.WriteString(", ")
		}
		fmt.Fprintf(b, "pattern: %q", vo.Pattern)
	}
	if vo.Email {
		if vo.MinLen != nil || vo.MaxLen != nil || vo.Pattern != "" {
			b.WriteString(", ")
		}
		b.WriteString("format: \"email\"")
	}
	if vo.URI {
		if vo.MinLen != nil || vo.MaxLen != nil || vo.Pattern != "" || vo.Email {
			b.WriteString(", ")
		}
		b.WriteString("format: \"uri\"")
	}

	// Integer constraints
	needsComma := vo.MinLen != nil || vo.MaxLen != nil || vo.Pattern != "" || vo.Email || vo.URI
	if vo.GTEInt != nil {
		if needsComma {
			b.WriteString(", ")
		}
		fmt.Fprintf(b, "minimum: %d", *vo.GTEInt)
		needsComma = true
	}
	if vo.LTEInt != nil {
		if needsComma {
			b.WriteString(", ")
		}
		fmt.Fprintf(b, "maximum: %d", *vo.LTEInt)
		needsComma = true
	}
	if vo.GTInt != nil {
		if needsComma {
			b.WriteString(", ")
		}
		fmt.Fprintf(b, "exclusiveMinimum: %d", *vo.GTInt)
		needsComma = true
	}
	if vo.LTInt != nil {
		if needsComma {
			b.WriteString(", ")
		}
		fmt.Fprintf(b, "exclusiveMaximum: %d", *vo.LTInt)
		needsComma = true
	}
	if len(vo.InInt) > 0 {
		if needsComma {
			b.WriteString(", ")
		}
		b.WriteString("enum: [")
		for i, v := range vo.InInt {
			if i > 0 {
				b.WriteString(", ")
			}
			fmt.Fprintf(b, "%d", v)
		}
		b.WriteString("]")
		needsComma = true
	}
	if len(vo.NotInInt) > 0 {
		if needsComma {
			b.WriteString(", ")
		}
		b.WriteString("notIn: [")
		for i, v := range vo.NotInInt {
			if i > 0 {
				b.WriteString(", ")
			}
			fmt.Fprintf(b, "%d", v)
		}
		b.WriteString("]")
		needsComma = true
	}

	// Unsigned integer constraints
	if vo.GTEUint != nil {
		if needsComma {
			b.WriteString(", ")
		}
		fmt.Fprintf(b, "minimum: %d", *vo.GTEUint)
		needsComma = true
	}
	if vo.LTEUint != nil {
		if needsComma {
			b.WriteString(", ")
		}
		fmt.Fprintf(b, "maximum: %d", *vo.LTEUint)
		needsComma = true
	}
	if vo.GTUint != nil {
		if needsComma {
			b.WriteString(", ")
		}
		fmt.Fprintf(b, "exclusiveMinimum: %d", *vo.GTUint)
		needsComma = true
	}
	if vo.LTUint != nil {
		if needsComma {
			b.WriteString(", ")
		}
		fmt.Fprintf(b, "exclusiveMaximum: %d", *vo.LTUint)
		needsComma = true
	}
	if len(vo.InUint) > 0 {
		if needsComma {
			b.WriteString(", ")
		}
		b.WriteString("enum: [")
		for i, v := range vo.InUint {
			if i > 0 {
				b.WriteString(", ")
			}
			fmt.Fprintf(b, "%d", v)
		}
		b.WriteString("]")
		needsComma = true
	}
	if len(vo.NotInUint) > 0 {
		if needsComma {
			b.WriteString(", ")
		}
		b.WriteString("notIn: [")
		for i, v := range vo.NotInUint {
			if i > 0 {
				b.WriteString(", ")
			}
			fmt.Fprintf(b, "%d", v)
		}
		b.WriteString("]")
		needsComma = true
	}

	// Float constraints
	if vo.GTEFloat != nil {
		if needsComma {
			b.WriteString(", ")
		}
		fmt.Fprintf(b, "minimum: %g", *vo.GTEFloat)
		needsComma = true
	}
	if vo.LTEFloat != nil {
		if needsComma {
			b.WriteString(", ")
		}
		fmt.Fprintf(b, "maximum: %g", *vo.LTEFloat)
		needsComma = true
	}
	if vo.GTFloat != nil {
		if needsComma {
			b.WriteString(", ")
		}
		fmt.Fprintf(b, "exclusiveMinimum: %g", *vo.GTFloat)
		needsComma = true
	}
	if vo.LTFloat != nil {
		if needsComma {
			b.WriteString(", ")
		}
		fmt.Fprintf(b, "exclusiveMaximum: %g", *vo.LTFloat)
		needsComma = true
	}

	// DefinedOnly for enum items
	if vo.DefinedOnly {
		if needsComma {
			b.WriteString(", ")
		}
		b.WriteString("definedOnly: true")
	}
}
