package tsrender

import (
	"strings"
	"testing"

	"github.com/pinealctx/gcode/internal/model"
	"github.com/pinealctx/gcode/internal/transform"
)

// scalarField is a test helper that creates a singular scalar GoField.
func scalarField(name, jsonName string, scalar model.ScalarKind) transform.GoField {
	return transform.GoField{
		Field: model.Field{
			Name:        name,
			JSONName:    jsonName,
			Cardinality: model.CardinalitySingular,
			Type:        model.FieldType{Kind: model.FieldKindScalar, Scalar: scalar},
		},
	}
}

// enumField is a test helper that creates a singular enum GoField.
func enumField(name, jsonName, fullName string) transform.GoField {
	return transform.GoField{
		Field: model.Field{
			Name:        name,
			JSONName:    jsonName,
			Cardinality: model.CardinalitySingular,
			Type:        model.FieldType{Kind: model.FieldKindEnum, FullName: fullName},
		},
	}
}

// messageField is a test helper that creates a singular message GoField.
func messageField(name, jsonName, fullName string, optional bool) transform.GoField {
	return transform.GoField{
		Field: model.Field{
			Name:        name,
			JSONName:    jsonName,
			Cardinality: model.CardinalitySingular,
			Optional:    optional,
			Type:        model.FieldType{Kind: model.FieldKindMessage, FullName: fullName},
		},
	}
}

// repeatedField is a test helper that creates a repeated GoField.
func repeatedField(name, jsonName string, kind model.FieldKind, scalar model.ScalarKind, fullName string) transform.GoField {
	return transform.GoField{
		Field: model.Field{
			Name:        name,
			JSONName:    jsonName,
			Cardinality: model.CardinalityRepeated,
			Type: model.FieldType{
				Kind:     kind,
				Scalar:   scalar,
				FullName: fullName,
			},
		},
	}
}

func TestTSFileBasic(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:  "person.proto",
		Package: "test",
		Messages: []transform.GoMessage{
			{
				GoName: "Person",
				Fields: []transform.GoField{
					scalarField("name", "name", model.ScalarString),
					scalarField("age", "age", model.ScalarInt32),
				},
			},
		},
	}

	out, err := TSFile(gf)
	if err != nil {
		t.Fatalf("TSFile returned error: %v", err)
	}

	s := string(out)
	assertContains(t, s, "// Code generated by gcode. DO NOT EDIT.")
	assertContains(t, s, "// source: person.proto")
	assertContains(t, s, "export interface Person {\n  name: string\n  age: number\n}\n")
}

func TestTSFileEnum(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:  "status.proto",
		Package: "test",
		Enums: []transform.GoEnum{
			{
				GoName: "Status",
				Values: []transform.GoEnumValue{
					{GoName: "Status_STATUS_UNSPECIFIED", Number: 0},
					{GoName: "Status_STATUS_ACTIVE", Number: 1},
					{GoName: "Status_STATUS_INACTIVE", Number: 2},
				},
			},
		},
	}

	out, err := TSFile(gf)
	if err != nil {
		t.Fatalf("TSFile returned error: %v", err)
	}

	s := string(out)
	assertContains(t, s, "export enum Status {")
	assertContains(t, s, "  STATUS_UNSPECIFIED = 0,")
	assertContains(t, s, "  STATUS_ACTIVE = 1,")
	assertContains(t, s, "  STATUS_INACTIVE = 2,")
	assertContains(t, s, "export const StatusName: Record<Status, string> = {")
	assertContains(t, s, `  [Status.STATUS_UNSPECIFIED]: "STATUS_UNSPECIFIED",`)
	assertContains(t, s, `  [Status.STATUS_ACTIVE]: "STATUS_ACTIVE",`)
	assertContains(t, s, "} as const")
}

func TestTSFileOptionalFields(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:  "optional.proto",
		Package: "test",
		Messages: []transform.GoMessage{
			{
				GoName: "Msg",
				Fields: []transform.GoField{
					{
						Field: model.Field{
							Name:        "name",
							JSONName:    "name",
							Cardinality: model.CardinalitySingular,
							Optional:    true,
							Type:        model.FieldType{Kind: model.FieldKindScalar, Scalar: model.ScalarString},
						},
					},
					{
						Field: model.Field{
							Name:        "count",
							JSONName:    "count",
							Cardinality: model.CardinalitySingular,
							Optional:    true,
							Type:        model.FieldType{Kind: model.FieldKindScalar, Scalar: model.ScalarInt32},
						},
					},
				},
			},
		},
	}

	out, err := TSFile(gf)
	if err != nil {
		t.Fatalf("TSFile returned error: %v", err)
	}

	s := string(out)
	assertContains(t, s, "  name?: string\n")
	assertContains(t, s, "  count?: number\n")
}

func TestTSFileRepeatedFields(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:  "repeated.proto",
		Package: "test",
		Messages: []transform.GoMessage{
			{
				GoName: "Msg",
				Fields: []transform.GoField{
					repeatedField("scores", "scores", model.FieldKindScalar, model.ScalarInt32, ""),
					repeatedField("tags", "tags", model.FieldKindScalar, model.ScalarString, ""),
				},
			},
		},
	}

	out, err := TSFile(gf)
	if err != nil {
		t.Fatalf("TSFile returned error: %v", err)
	}

	s := string(out)
	assertContains(t, s, "  scores: number[]\n")
	assertContains(t, s, "  tags: string[]\n")
}

func TestTSFileMessageField(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:  "nested.proto",
		Package: "test",
		Messages: []transform.GoMessage{
			{
				GoName: "Address",
				Fields: []transform.GoField{
					scalarField("city", "city", model.ScalarString),
				},
			},
			{
				GoName: "Person",
				Fields: []transform.GoField{
					scalarField("name", "name", model.ScalarString),
					messageField("address", "address", "test.Address", true),
				},
			},
		},
	}

	out, err := TSFile(gf)
	if err != nil {
		t.Fatalf("TSFile returned error: %v", err)
	}

	s := string(out)
	assertContains(t, s, "export interface Address {\n  city: string\n}\n")
	assertContains(t, s, "export interface Person {\n  name: string\n  address?: Address\n}\n")
}

func TestTSFileInt64AsString(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:  "int64.proto",
		Package: "test",
		Messages: []transform.GoMessage{
			{
				GoName: "Msg",
				Fields: []transform.GoField{
					scalarField("id", "id", model.ScalarInt64),
					scalarField("uid", "uid", model.ScalarUint64),
					scalarField("sfid", "sfid", model.ScalarSfixed64),
				},
			},
		},
	}

	out, err := TSFile(gf)
	if err != nil {
		t.Fatalf("TSFile returned error: %v", err)
	}

	s := string(out)
	assertContains(t, s, "  id: string\n")
	assertContains(t, s, "  uid: string\n")
	assertContains(t, s, "  sfid: string\n")
}

func TestTSFileBytesAsString(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:  "bytes.proto",
		Package: "test",
		Messages: []transform.GoMessage{
			{
				GoName: "Msg",
				Fields: []transform.GoField{
					scalarField("data", "data", model.ScalarBytes),
				},
			},
		},
	}

	out, err := TSFile(gf)
	if err != nil {
		t.Fatalf("TSFile returned error: %v", err)
	}

	s := string(out)
	assertContains(t, s, "  data: string\n")
}

func TestTSFileOptionalBytes(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:  "optbytes.proto",
		Package: "test",
		Messages: []transform.GoMessage{
			{
				GoName: "Msg",
				Fields: []transform.GoField{
					{
						Field: model.Field{
							Name:        "data",
							JSONName:    "data",
							Cardinality: model.CardinalitySingular,
							HasPresence: true,
							Type:        model.FieldType{Kind: model.FieldKindScalar, Scalar: model.ScalarBytes},
						},
					},
				},
			},
		},
	}

	out, err := TSFile(gf)
	if err != nil {
		t.Fatalf("TSFile returned error: %v", err)
	}

	s := string(out)
	assertContains(t, s, "  data?: string\n")
}

func TestTSFileEmpty(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:  "empty.proto",
		Package: "test",
	}

	out, err := TSFile(gf)
	if err != nil {
		t.Fatalf("TSFile returned error: %v", err)
	}

	s := string(out)
	assertContains(t, s, "// Code generated by gcode. DO NOT EDIT.")
	assertContains(t, s, "// source: empty.proto")
	// No enum or interface content.
	if strings.Contains(s, "export ") {
		t.Errorf("empty file should have no exports, got:\n%s", s)
	}
}

func TestTSFileHeader(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:  "path/to/person.proto",
		Package: "mypackage",
		Messages: []transform.GoMessage{
			{
				GoName: "Empty",
			},
		},
	}

	out, err := TSFile(gf)
	if err != nil {
		t.Fatalf("TSFile returned error: %v", err)
	}

	s := string(out)
	assertContains(t, s, "// Code generated by gcode. DO NOT EDIT.\n// source: path/to/person.proto\n\n")
}

func TestTSFileEnumWithComment(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:  "comment.proto",
		Package: "test",
		Enums: []transform.GoEnum{
			{
				GoName:  "Role",
				Comment: model.Comment{Lines: []string{"User role types."}},
				Values: []transform.GoEnumValue{
					{GoName: "Role_ADMIN", Number: 0},
					{GoName: "Role_USER", Number: 1},
				},
			},
		},
		Messages: []transform.GoMessage{
			{
				GoName:  "Item",
				Comment: model.Comment{Lines: []string{"An item.", "With detail."}},
				Fields: []transform.GoField{
					scalarField("title", "title", model.ScalarString),
				},
			},
		},
	}

	out, err := TSFile(gf)
	if err != nil {
		t.Fatalf("TSFile returned error: %v", err)
	}

	s := string(out)
	assertContains(t, s, "/** User role types. */\nexport enum Role {")
	assertContains(t, s, "/**\n * An item.\n * With detail.\n */\nexport interface Item {")
}

func TestTSFileEnumField(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:  "enumfield.proto",
		Package: "test",
		Enums: []transform.GoEnum{
			{
				GoName: "Status",
				Values: []transform.GoEnumValue{
					{GoName: "Status_UNKNOWN", Number: 0},
					{GoName: "Status_ACTIVE", Number: 1},
				},
			},
		},
		Messages: []transform.GoMessage{
			{
				GoName: "Msg",
				Fields: []transform.GoField{
					enumField("status", "status", "test.Status"),
				},
			},
		},
	}

	out, err := TSFile(gf)
	if err != nil {
		t.Fatalf("TSFile returned error: %v", err)
	}

	s := string(out)
	assertContains(t, s, "  status: Status\n")
}

func TestTSFileJSONName(t *testing.T) {
	t.Parallel()

	// Verify that property names use JSONName (camelCase), not GoName (PascalCase).
	gf := transform.GoFile{
		Source:  "jsonname.proto",
		Package: "test",
		Messages: []transform.GoMessage{
			{
				GoName: "Msg",
				Fields: []transform.GoField{
					{
						Field: model.Field{
							Name:        "created_at",
							JSONName:    "createdAt",
							Cardinality: model.CardinalitySingular,
							Type:        model.FieldType{Kind: model.FieldKindScalar, Scalar: model.ScalarString},
						},
						GoName: "CreatedAt",
					},
				},
			},
		},
	}

	out, err := TSFile(gf)
	if err != nil {
		t.Fatalf("TSFile returned error: %v", err)
	}

	s := string(out)
	assertContains(t, s, "  createdAt: string\n")
	if strings.Contains(s, "CreatedAt") {
		t.Errorf("output should use JSONName (camelCase), not GoName (PascalCase), got:\n%s", s)
	}
}

func TestTSFileRepeatedEnumField(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:  "repenum.proto",
		Package: "test",
		Enums: []transform.GoEnum{
			{
				GoName: "Status",
				Values: []transform.GoEnumValue{
					{GoName: "Status_UNKNOWN", Number: 0},
				},
			},
		},
		Messages: []transform.GoMessage{
			{
				GoName: "Msg",
				Fields: []transform.GoField{
					repeatedField("statuses", "statuses", model.FieldKindEnum, "", "test.Status"),
				},
			},
		},
	}

	out, err := TSFile(gf)
	if err != nil {
		t.Fatalf("TSFile returned error: %v", err)
	}

	s := string(out)
	assertContains(t, s, "  statuses: Status[]\n")
}

func TestTSFileRepeatedMessageField(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:  "repmsg.proto",
		Package: "test",
		Messages: []transform.GoMessage{
			{
				GoName: "Item",
				Fields: []transform.GoField{
					scalarField("name", "name", model.ScalarString),
				},
			},
			{
				GoName: "Cart",
				Fields: []transform.GoField{
					repeatedField("items", "items", model.FieldKindMessage, "", "test.Item"),
				},
			},
		},
	}

	out, err := TSFile(gf)
	if err != nil {
		t.Fatalf("TSFile returned error: %v", err)
	}

	s := string(out)
	assertContains(t, s, "  items: Item[]\n")
}

func TestTSFileNonOptionalMessageField(t *testing.T) {
	t.Parallel()

	gf := transform.GoFile{
		Source:  "reqmsg.proto",
		Package: "test",
		Messages: []transform.GoMessage{
			{
				GoName: "Inner",
				Fields: []transform.GoField{
					scalarField("value", "value", model.ScalarString),
				},
			},
			{
				GoName: "Outer",
				Fields: []transform.GoField{
					messageField("inner", "inner", "test.Inner", false),
				},
			},
		},
	}

	out, err := TSFile(gf)
	if err != nil {
		t.Fatalf("TSFile returned error: %v", err)
	}

	s := string(out)
	assertContains(t, s, "  inner: Inner\n")
}

func TestTSScalarTypeUnknown(t *testing.T) {
	t.Parallel()

	got := tsScalarType(model.ScalarKind("nonexistent"))
	if got != "unknown" {
		t.Errorf("tsScalarType(nonexistent) = %q, want %q", got, "unknown")
	}
}

func TestTSFieldTypeUnknownKind(t *testing.T) {
	t.Parallel()

	f := transform.GoField{
		Field: model.Field{
			Name:        "x",
			JSONName:    "x",
			Cardinality: model.CardinalitySingular,
			Type:        model.FieldType{Kind: model.FieldKind("weird")},
		},
	}
	got := tsFieldType(f, "test")
	if got != "unknown" {
		t.Errorf("tsFieldType(unknown kind) = %q, want %q", got, "unknown")
	}
}

// assertContains is a test helper that checks s contains want.
func assertContains(t *testing.T, s, want string) {
	t.Helper()
	if !strings.Contains(s, want) {
		t.Errorf("output does not contain %q\nfull output:\n%s", want, s)
	}
}
