// Package tsrender generates TypeScript source code from the Go-oriented
// intermediate representation produced by the transform package. It outputs
// .ts files containing interfaces, enums, enum name mappings, and (later)
// validation metadata.
package tsrender

import (
	"fmt"
	"sort"
	"strings"

	"github.com/pinealctx/gcode/internal/model"
	"github.com/pinealctx/gcode/internal/naming"
	"github.com/pinealctx/gcode/internal/transform"
)

// TypeRegistry maps Go type names to their source .pb.ts output file name.
// Used to generate ES module import statements for cross-file type references.
type TypeRegistry map[string]string

// TSFile generates a complete TypeScript file from a GoFile intermediate
// representation. The returned bytes are ready to write to disk as a .pb.ts file.
// The registry maps Go type names to their source .pb.ts output file name,
// used to generate ES module import statements for cross-file references.
// msgIndex maps GoName to GoMessage for validate rule inheritance in create/update messages.
func TSFile(gf transform.GoFile, registry TypeRegistry, msgIndex map[string]*transform.GoMessage) ([]byte, error) {
	var b strings.Builder

	protoPkg := gf.ProtoPackage
	if protoPkg == "" {
		protoPkg = gf.Package
	}

	writeHeader(&b, gf.Source)
	writeImports(&b, gf, protoPkg, registry)

	for _, enum := range gf.Enums {
		writeTSEnum(&b, enum)
	}

	for _, msg := range gf.Messages {
		writeTSInterface(&b, msg, protoPkg)
	}

	for _, msg := range gf.Messages {
		writeTSValidationRules(&b, msg, msgIndex)
	}

	return []byte(b.String()), nil
}

// tsScalarType maps a protobuf scalar kind to its TypeScript type.
func tsScalarType(kind model.ScalarKind) string {
	switch kind {
	case model.ScalarInt32, model.ScalarSint32, model.ScalarSfixed32,
		model.ScalarUint32, model.ScalarFixed32,
		model.ScalarFloat, model.ScalarDouble:
		return "number"
	case model.ScalarInt64, model.ScalarSint64, model.ScalarSfixed64,
		model.ScalarUint64, model.ScalarFixed64:
		return "string"
	case model.ScalarBool:
		return "boolean"
	case model.ScalarString, model.ScalarBytes:
		return "string"
	default:
		return "unknown"
	}
}

// tsFieldType resolves the TypeScript type string for a GoField.
// It handles scalars, enums, message references, and repeated cardinality.
// protoPkg is the proto package name, used to compute the correct short type name.
func tsFieldType(f transform.GoField, protoPkg string) string {
	var base string
	switch f.Type.Kind {
	case model.FieldKindScalar:
		base = tsScalarType(f.Type.Scalar)
	case model.FieldKindEnum, model.FieldKindMessage:
		base = naming.GoTypeName(f.Type.FullName, protoPkg)
	default:
		base = "unknown"
	}

	if f.Cardinality == model.CardinalityRepeated {
		return base + "[]"
	}
	return base
}

// tsIsOptional returns true if the field should be marked optional in the
// TypeScript interface (using the `?:` syntax). This covers both proto3
// explicit optional fields and fields with presence semantics (e.g. optional bytes).
func tsIsOptional(f transform.GoField) bool {
	return f.Optional || f.HasPresence
}

// writeHeader writes the generated-file header comment.
func writeHeader(b *strings.Builder, source string) {
	b.WriteString("// Code generated by gcode. DO NOT EDIT.\n")
	fmt.Fprintf(b, "// source: %s\n\n", source)
}

// writeImports generates ES module import statements for cross-file type
// references. Types defined in the current file are skipped. Import paths
// use the .js extension for maximum moduleResolution compatibility.
func writeImports(b *strings.Builder, gf transform.GoFile, protoPkg string, registry TypeRegistry) {
	// Collect GoNames of types defined in this file.
	localTypes := make(map[string]bool, len(gf.Enums)+len(gf.Messages))
	for _, enum := range gf.Enums {
		localTypes[enum.GoName] = true
	}
	for _, msg := range gf.Messages {
		localTypes[msg.GoName] = true
	}

	// Collect cross-file type dependencies: sourceFile → sorted unique type names.
	deps := make(map[string]map[string]bool)
	for _, msg := range gf.Messages {
		for _, f := range msg.Fields {
			if f.Type.Kind != model.FieldKindEnum && f.Type.Kind != model.FieldKindMessage {
				continue
			}
			typeName := naming.GoTypeName(f.Type.FullName, protoPkg)
			if localTypes[typeName] {
				continue
			}
			srcFile, ok := registry[typeName]
			if !ok {
				continue
			}
			if deps[srcFile] == nil {
				deps[srcFile] = make(map[string]bool)
			}
			deps[srcFile][typeName] = true
		}
	}

	if len(deps) == 0 {
		return
	}

	// Sort source files for deterministic output.
	srcFiles := make([]string, 0, len(deps))
	for sf := range deps {
		srcFiles = append(srcFiles, sf)
	}
	sort.Strings(srcFiles)

	for _, sf := range srcFiles {
		names := make([]string, 0, len(deps[sf]))
		for n := range deps[sf] {
			names = append(names, n)
		}
		sort.Strings(names)

		// Replace .pb.ts with .pb.js for ESM import path.
		importPath := strings.TrimSuffix(sf, ".ts") + ".js"
		fmt.Fprintf(b, "import { %s } from \"./%s\"\n", strings.Join(names, ", "), importPath)
	}
	b.WriteString("\n")
}

// sanitizeTSComment replaces "*/" with "* /" to prevent premature JSDoc block
// termination. Proto comment content is developer-controlled, but a literal
// "*/" would break the generated /** ... */ block and produce invalid TS.
func sanitizeTSComment(s string) string {
	return strings.ReplaceAll(s, "*/", "* /")
}

// writeTSComment writes a JSDoc-style comment block. Single-line comments
// use the `/** ... */` form; multi-line comments use the indented form.
// "*/" sequences in comment text are escaped to "* /" to prevent premature
// block termination.
func writeTSComment(b *strings.Builder, comment model.Comment) {
	if len(comment.Lines) == 0 {
		return
	}
	if len(comment.Lines) == 1 {
		fmt.Fprintf(b, "/** %s */\n", sanitizeTSComment(comment.Lines[0]))
		return
	}
	b.WriteString("/**\n")
	for _, line := range comment.Lines {
		fmt.Fprintf(b, " * %s\n", sanitizeTSComment(line))
	}
	b.WriteString(" */\n")
}

// writeTSEnum writes a TypeScript enum declaration followed by its
// name mapping Record. Enum value names are extracted from the GoName
// by stripping the parent enum name prefix.
//
// Example output:
//
//	export enum Status {
//	  STATUS_UNSPECIFIED = 0,
//	  STATUS_ACTIVE = 1,
//	}
//
//	export const StatusName: Record<Status, string> = {
//	  [Status.STATUS_UNSPECIFIED]: "STATUS_UNSPECIFIED",
//	  [Status.STATUS_ACTIVE]: "STATUS_ACTIVE",
//	} as const
func writeTSEnum(b *strings.Builder, enum transform.GoEnum) {
	writeTSComment(b, enum.Comment)
	fmt.Fprintf(b, "export enum %s {\n", enum.GoName)
	for _, v := range enum.Values {
		protoName := strings.TrimPrefix(v.GoName, enum.GoName+"_")
		fmt.Fprintf(b, "  %s = %d,\n", protoName, v.Number)
	}
	b.WriteString("}\n\n")

	fmt.Fprintf(b, "export const %sName: Record<%s, string> = {\n", enum.GoName, enum.GoName)
	for _, v := range enum.Values {
		protoName := strings.TrimPrefix(v.GoName, enum.GoName+"_")
		fmt.Fprintf(b, "  [%s.%s]: \"%s\",\n", enum.GoName, protoName, protoName)
	}
	b.WriteString("} as const\n\n")
}

// writeTSInterface writes a TypeScript interface declaration for a message.
// Field names use the proto JSONName (camelCase). Optional fields use the
// `?:` syntax; repeated fields use `T[]`.
//
// Example output:
//
//	/** Comment from proto. */
//	export interface Person {
//	  name: string
//	  age: number
//	  address?: Address
//	  scores: number[]
//	}
func writeTSInterface(b *strings.Builder, msg transform.GoMessage, pkgName string) {
	writeTSComment(b, msg.Comment)
	fmt.Fprintf(b, "export interface %s {\n", msg.GoName)
	for _, f := range msg.Fields {
		fieldName := f.JSONName
		fieldType := tsFieldType(f, pkgName)
		if tsIsOptional(f) {
			fmt.Fprintf(b, "  %s?: %s\n", fieldName, fieldType)
		} else {
			fmt.Fprintf(b, "  %s: %s\n", fieldName, fieldType)
		}
	}
	b.WriteString("}\n\n")
}
