// Package compat_test — golden file snapshot tests for gen-proto two-phase generation.
// Verifies that RunGenProto output matches committed golden files in proto/.
// Also verifies: validate annotations not in entity protos, gorm.column preserved in entity protos.
package compat_test

import (
	"context"
	"io"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"

	"github.com/pinealctx/gcode/internal/app"
)

// _genProtoGoldenFiles lists every intermediate proto golden file relative to proto/.
// These are the files generated by RunGenProto from the schema (.meta.proto) files.
var _genProtoGoldenFiles = []string{
	"person.entity.proto",
	"person.update.proto",
	"person.create.proto",
	"all_types.entity.proto",
	"all_types.update.proto",
	"all_types.create.proto",
	"item.entity.proto",
	"item.update.proto",
	"item.create.proto",
}

// TestGenProtoSnapshot verifies that RunGenProto output matches committed golden files.
// RunGenProto writes intermediate protos into the input directory itself, so we copy
// the proto/ directory to a temp dir, run RunGenProto there, then compare generated
// files against the committed golden files.
func TestGenProtoSnapshot(t *testing.T) {
	t.Parallel()

	goldenDir := "proto"

	// Copy proto/ to a temp directory so RunGenProto can write into it without
	// modifying the source tree.
	tmpDir := t.TempDir()
	if err := copyDir(goldenDir, tmpDir); err != nil {
		t.Fatalf("copy proto dir: %v", err)
	}

	// Run gen-proto in the temp directory.
	if err := app.RunGenProto(context.Background(), []string{"-in", tmpDir}); err != nil {
		t.Fatalf("RunGenProto: %v", err)
	}

	// Compare each generated file against the golden.
	for _, name := range _genProtoGoldenFiles {
		t.Run(name, func(t *testing.T) {
			generated, err := os.ReadFile(filepath.Join(tmpDir, name))
			if err != nil {
				t.Fatalf("read generated file %q: %v", name, err)
			}

			golden, err := os.ReadFile(filepath.Join(goldenDir, name))
			if err != nil {
				t.Fatalf("read golden file %q: %v", name, err)
			}

			genStr := string(generated)
			goldStr := string(golden)

			if genStr != goldStr {
				genLines := strings.Split(genStr, "\n")
				goldLines := strings.Split(goldStr, "\n")

				var diff strings.Builder
				maxLines := len(genLines)
				if len(goldLines) > maxLines {
					maxLines = len(goldLines)
				}
				for i := 0; i < maxLines; i++ {
					var gl, dl string
					if i < len(goldLines) {
						gl = goldLines[i]
					}
					if i < len(genLines) {
						dl = genLines[i]
					}
					if gl != dl {
						diff.WriteString("line ")
						diff.WriteString(strconv.Itoa(i+1))
						diff.WriteString(":\n  golden:    ")
						diff.WriteString(gl)
						diff.WriteString("\n  generated: ")
						diff.WriteString(dl)
						diff.WriteString("\n")
					}
				}

				t.Errorf("generated %q does not match golden file:\n%s", name, diff.String())
			}
		})
	}
}

// TestGenProtoValidateNotInEntity verifies that validate annotations from the source
// proto are NOT present in entity proto files.
// Create/update protos SHOULD contain validate annotations.
func TestGenProtoValidateNotInEntity(t *testing.T) {
	t.Parallel()

	entityFiles := []string{
		"proto/person.entity.proto",
		"proto/all_types.entity.proto",
		"proto/item.entity.proto",
	}

	for _, name := range entityFiles {
		content, err := os.ReadFile(name)
		if err != nil {
			t.Fatalf("read %q: %v", name, err)
		}

		if strings.Contains(string(content), "buf.validate") {
			t.Errorf("%q contains buf.validate annotation — entity protos must not carry validate", name)
		}
	}
}

// TestGenProtoGormColumnPreserved verifies that gorm.column annotations from the source
// proto are preserved in the entity proto files (not in create/update protos).
func TestGenProtoGormColumnPreserved(t *testing.T) {
	t.Parallel()

	// person.entity.proto should preserve (gcode.field).gorm.column = "created_ts"
	// from the created_at field.
	content, err := os.ReadFile(filepath.Join("proto", "person.entity.proto"))
	if err != nil {
		t.Fatalf("read person.entity.proto: %v", err)
	}

	if !strings.Contains(string(content), `gorm.column = "created_ts"`) {
		t.Errorf("person.entity.proto should preserve gorm.column annotation for created_at field")
	}

	// all_types.entity.proto should preserve (gcode.field).gorm.column = "f_bytes_col"
	// from the f_bytes field.
	content2, err := os.ReadFile(filepath.Join("proto", "all_types.entity.proto"))
	if err != nil {
		t.Fatalf("read all_types.entity.proto: %v", err)
	}

	if !strings.Contains(string(content2), `gorm.column = "f_bytes_col"`) {
		t.Errorf("all_types.entity.proto should preserve gorm.column annotation for f_bytes field")
	}
}

// copyDir copies all files from src directory to dst directory (non-recursive).
func copyDir(src, dst string) error {
	entries, err := os.ReadDir(src)
	if err != nil {
		return err
	}
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		if err := copyFile(filepath.Join(src, e.Name()), filepath.Join(dst, e.Name())); err != nil {
			return err
		}
	}
	return nil
}

// copyFile copies a single file from src to dst.
func copyFile(src, dst string) error {
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()

	out, err := os.Create(dst)
	if err != nil {
		return err
	}
	defer out.Close()

	_, err = io.Copy(out, in)
	return err
}
