// Code generated by gcode. DO NOT EDIT.
// source: all_types.update.proto

export interface AllScalarsUpdate {
  fSint32: number
  fSint64?: string
  fSfixed32?: number
  fSfixed64?: string
  fDouble?: number
  fFixed32?: number
  fFixed64?: string
  fUint32?: number
  fUint64?: string
  fFloat?: number
  fBytes?: string
}

