// Code generated by gcode. DO NOT EDIT.
// source: all_types.proto

import { Address, Status } from "./person.pb.js"

/** AllScalars covers every scalar wire type not present in person.proto. */
export interface AllScalars {
  fSint32: number
  fSint64: string
  fSfixed32: number
  fSfixed64: string
  fDouble: number
  fFixed32: number
  fFixed64: string
  fUint32: number
  fUint64: string
  fFloat: number
  fBytes: string
}

/** AllRepeated covers repeated field wire types not present in person.proto. */
export interface AllRepeated {
  rSint32: number[]
  rSfixed32: number[]
  rDouble: number[]
  rBytes: string[]
  rMessage: Address[]
  rEnum: Status[]
}

/** AllValidate covers validate constraint types not present in person.proto. */
export interface AllValidate {
  uGte: number
  uLte: string
  uIn: number
  uNotIn: number
  fGt: number
  dLte: number
  sIn: string
  sNotIn: string
  iIn: number
  sUri: string
  oStatus?: Status
  bMinmax: string
  rItems: number[]
}

export const AllValidateRules = {
  uGte: { required: false, type: "integer", minimum: 1 },
  uLte: { required: false, type: "integer", maximum: 1000 },
  uIn: { required: false, type: "integer", enum: [1, 2, 3] },
  uNotIn: { required: false, type: "integer", notIn: [0] },
  fGt: { required: false, type: "number", exclusiveMinimum: 0 },
  dLte: { required: false, type: "number", maximum: 1 },
  sIn: { required: false, type: "string", enum: ["a", "b", "c"] },
  sNotIn: { required: false, type: "string", notIn: ["x", "y"] },
  iIn: { required: false, type: "integer", enum: [1, 2, -1] },
  sUri: { required: false, type: "string", format: "uri" },
  oStatus: { required: false, type: "enum", definedOnly: true },
  bMinmax: { required: false, type: "string", minLength: 1, maxLength: 100 },
  rItems: { required: false, type: "array", items: { type: "integer", minimum: 0 } }
} as const

