// Code generated by gcode. DO NOT EDIT.
// source: all_types.entity.proto

import { Address, Status } from "./person.entity.pb.js"

export interface AllScalars {
  fSint32: number
  fSint64: string
  fSfixed32: number
  fSfixed64: string
  fDouble: number
  fFixed32: number
  fFixed64: string
  fUint32: number
  fUint64: string
  fFloat: number
  fBytes: string
}

export interface AllRepeated {
  rSint32: number[]
  rSfixed32: number[]
  rDouble: number[]
  rBytes: string[]
  rMessage: Address[]
  rEnum: Status[]
}

export interface TreeNode {
  value: string
  child: TreeNode
}

