// Code generated by gcode. DO NOT EDIT.
// source: all_types.create.proto

export interface AllScalarsCreate {
  fSint32?: number
  fSint64?: number
  fSfixed32?: number
  fSfixed64?: number
  fFixed32?: number
  fFixed64?: number
  fUint32?: number
  fUint64?: number
  fFloat?: number
  fBytes?: string
}

