// Code generated by gcode. DO NOT EDIT.
// source: all_validate.proto

import { Status } from "./person.entity.pb.js"

/** AllValidate covers validate constraint types not present in person.proto. */
export interface AllValidate {
  uGte: number
  uLte: string
  uIn: number
  uNotIn: number
  fGt: number
  dLte: number
  sIn: string
  sNotIn: string
  iIn: number
  sUri: string
  oStatus?: Status
  bMinmax: string
  rItems: number[]
  iGtLt: number
  uGtLt: number
  fLt: number
  dGt: number
  sPattern: string
}

export const AllValidateRules = {
  uGte: { required: false, type: "integer", minimum: 1 },
  uLte: { required: false, type: "integer", maximum: 1000 },
  uIn: { required: false, type: "integer", enum: [1, 2, 3] },
  uNotIn: { required: false, type: "integer", notIn: [0] },
  fGt: { required: false, type: "number", exclusiveMinimum: 0 },
  dLte: { required: false, type: "number", maximum: 1 },
  sIn: { required: false, type: "string", enum: ["a", "b", "c"] },
  sNotIn: { required: false, type: "string", notIn: ["x", "y"] },
  iIn: { required: false, type: "integer", enum: [1, 2, -1] },
  sUri: { required: false, type: "string", format: "uri" },
  oStatus: { required: false, type: "enum", definedOnly: true },
  bMinmax: { required: false, type: "string", minLength: 1, maxLength: 100 },
  rItems: { required: false, type: "array", items: { type: "integer", minimum: 0 } },
  iGtLt: { required: false, type: "integer", exclusiveMinimum: -10, exclusiveMaximum: 10 },
  uGtLt: { required: false, type: "integer", exclusiveMinimum: 5, exclusiveMaximum: 100 },
  fLt: { required: false, type: "number", exclusiveMaximum: 99.5 },
  dGt: { required: false, type: "number", exclusiveMinimum: -1 },
  sPattern: { required: false, type: "string", pattern: "^[A-Z][a-z]+$" }
} as const

