// Code generated by gcode. DO NOT EDIT.
// source: common.proto

/**
 * ItemKind categorizes an item by its type.
 * Defined in a separate file to test cross-file enum import in gen-proto.
 */
export enum ItemKind {
  ITEM_KIND_UNSPECIFIED = 0,
  ITEM_KIND_PHYSICAL = 1,
  ITEM_KIND_DIGITAL = 2,
}

export const ItemKindName: Record<ItemKind, string> = {
  [ItemKind.ITEM_KIND_UNSPECIFIED]: "ITEM_KIND_UNSPECIFIED",
  [ItemKind.ITEM_KIND_PHYSICAL]: "ITEM_KIND_PHYSICAL",
  [ItemKind.ITEM_KIND_DIGITAL]: "ITEM_KIND_DIGITAL",
} as const

/**
 * Dimensions holds physical size information shared across item types.
 * Defined in a separate file to test cross-file message import in gen-proto.
 */
export interface Dimensions {
  width: number
  height: number
}

export const DimensionsRules = {
  width: { required: false, type: "number", minimum: 0 },
  height: { required: false, type: "number", minimum: 0 }
} as const

