// Code generated by gcode. DO NOT EDIT.
// source: item.entity.proto

import { Dimensions, ItemKind } from "./common.pb.js"

export interface Item {
  id: string
  name: string
  kind: ItemKind
  dimensions: Dimensions
  createdAt: string
}

