// Code generated by gcode. DO NOT EDIT.
// source: item.update.proto

import { Dimensions, ItemKind } from "./common.pb.js"

export interface ItemUpdate {
  id: string
  name?: string
  kind?: ItemKind
  dimensions: Dimensions
}

export const ItemUpdateRules = {
  name: { required: false, type: "string", minLength: 1, maxLength: 200 },
  kind: { required: false, type: "enum", definedOnly: true },
  dimensions: { required: true, type: "object" }
} as const

