// Code generated by gcode. DO NOT EDIT.
// source: person.update.proto

import { Status } from "./person.pb.js"

export interface PersonUpdateByName {
  name: string
  age?: number
  active?: boolean
  status?: Status
  rating?: number
  createdAt?: string
  nickname?: string
  level?: number
  verified?: boolean
  score?: number
  updatedAt?: string
  prevStatus?: Status
  email?: string
  role?: string
  typeId?: number
}

export const PersonUpdateByNameRules = {
  name: { required: true, type: "string", minLength: 1, maxLength: 100 },
  age: { required: false, type: "integer", minimum: 0, maximum: 150 },
  status: { required: false, type: "enum", definedOnly: true },
  nickname: { required: false, type: "string", minLength: 1, maxLength: 10 },
  email: { required: false, type: "string", format: "email" },
  role: { required: false, type: "string", enum: ["admin", "user", "guest"] },
  typeId: { required: false, type: "integer", notIn: [0, -1] }
} as const

