// Code generated by gcode. DO NOT EDIT.
// source: person.create.proto

export interface PersonCreate {
  name?: string
  age?: number
  active?: boolean
  status?: Compat_Status
  rating?: number
  nickname: string
  level?: number
  verified?: boolean
  score?: number
  updatedAt?: string
  prevStatus?: Compat_Status
  email?: string
  role?: string
  typeId?: number
}

