// Code generated by gcode. DO NOT EDIT.
// source: person.entity.proto

export enum Status {
  STATUS_UNSPECIFIED = 0,
  STATUS_ACTIVE = 1,
  STATUS_INACTIVE = 2,
}

export const StatusName: Record<Status, string> = {
  [Status.STATUS_UNSPECIFIED]: "STATUS_UNSPECIFIED",
  [Status.STATUS_ACTIVE]: "STATUS_ACTIVE",
  [Status.STATUS_INACTIVE]: "STATUS_INACTIVE",
} as const

export interface Address {
  street: string
  city: string
}

export interface Person {
  name: string
  age: number
  active: boolean
  status: Status
  address: Address
  scores: number[]
  tags: string[]
  rating: number
  createdAt: string
  avatar: string
  nickname?: string
  level?: number
  verified?: boolean
  score?: number
  updatedAt?: string
  prevStatus?: Status
  fingerprint?: string
  email: string
  role: string
  typeId: number
}

