// Code generated by gcode. DO NOT EDIT.
// source: person.update.proto

import { Status } from "./person.pb.js"

export interface PersonUpdateByName {
  name: string
  age?: number
  active?: boolean
  status?: Status
  rating?: number
  createdAt?: string
  nickname?: string
  level?: number
  verified?: boolean
  score?: number
  updatedAt?: string
  prevStatus?: Status
  email?: string
  role?: string
  typeId?: number
}

